<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 5 More on thematic maps | Crime Mapping in R</title>
  <meta name="description" content="Worksheets for labs of Crime Mapping course">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 5 More on thematic maps | Crime Mapping in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Worksheets for labs of Crime Mapping course" />
  <meta name="github-repo" content="maczokni/crimemapping_textbook_bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 More on thematic maps | Crime Mapping in R" />
  
  <meta name="twitter:description" content="Worksheets for labs of Crime Mapping course" />
  

<meta name="author" content="Juanjo Medina and Reka Solymosi">


<meta name="date" content="2019-03-04">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="performing-spatial-operations-in-r.html">
<link rel="next" href="studying-spatial-point-patterns.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Crime mapping in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prelude</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i><b>0.1</b> Introduction</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>0.2</b> Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A first lesson about R</a><ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#open-up-and-explore-rstudio"><i class="fa fa-check"></i><b>1.2</b> Open up and explore RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>1.3</b> Customising the RStudio look</a></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>1.4</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="1.5" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#talk-to-your-computer"><i class="fa fa-check"></i><b>1.5</b> Talk to your computer</a></li>
<li class="chapter" data-level="1.6" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-packages"><i class="fa fa-check"></i><b>1.6</b> More on packages</a></li>
<li class="chapter" data-level="1.7" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#using-objects"><i class="fa fa-check"></i><b>1.7</b> Using objects</a></li>
<li class="chapter" data-level="1.8" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-objects"><i class="fa fa-check"></i><b>1.8</b> More on objects</a></li>
<li class="chapter" data-level="1.9" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#vectors"><i class="fa fa-check"></i><b>1.9</b> Vectors</a></li>
<li class="chapter" data-level="1.10" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#on-comments"><i class="fa fa-check"></i><b>1.10</b> On comments</a></li>
<li class="chapter" data-level="1.11" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#factors"><i class="fa fa-check"></i><b>1.11</b> Factors</a></li>
<li class="chapter" data-level="1.12" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#naming-conventions-for-objects-in-r"><i class="fa fa-check"></i><b>1.12</b> Naming conventions for objects in R</a></li>
<li class="chapter" data-level="1.13" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#dataframes"><i class="fa fa-check"></i><b>1.13</b> Dataframes</a></li>
<li class="chapter" data-level="1.14" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#exploring-data"><i class="fa fa-check"></i><b>1.14</b> Exploring data</a></li>
<li class="chapter" data-level="1.15" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#quitting-rstudio"><i class="fa fa-check"></i><b>1.15</b> Quitting RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html"><i class="fa fa-check"></i><b>2</b> Making your first maps in R</a><ul>
<li class="chapter" data-level="2.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#a-quick-introduction-of-terms"><i class="fa fa-check"></i><b>2.1</b> A quick introduction of terms</a><ul>
<li class="chapter" data-level="2.1.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#geospatial-perspective---the-basics"><i class="fa fa-check"></i><b>2.1.1</b> Geospatial Perspective - The Basics</a></li>
<li class="chapter" data-level="2.1.2" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#summary"><i class="fa fa-check"></i><b>2.1.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#getting-some-spatial-data-to-put-on-a-map"><i class="fa fa-check"></i><b>2.2</b> Getting some spatial data to put on a map</a><ul>
<li class="chapter" data-level="2.2.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#a-first-look-at-basemaps"><i class="fa fa-check"></i><b>2.2.1</b> A first look at basemaps</a></li>
<li class="chapter" data-level="2.2.2" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#find-some-relevant-data-to-show-obtaining-data-on-crime"><i class="fa fa-check"></i><b>2.2.2</b> Find some relevant data to show: obtaining data on crime</a></li>
<li class="chapter" data-level="2.2.3" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#add-a-point-layer-to-your-basemap"><i class="fa fa-check"></i><b>2.2.3</b> Add a point layer to your basemap</a></li>
<li class="chapter" data-level="2.2.4" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#homework-1"><i class="fa fa-check"></i><b>2.2.4</b> HOMEWORK 1</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#from-dataframes-to-spatial-objects-finding-shapefiles"><i class="fa fa-check"></i><b>2.3</b> From dataframes to spatial objects: finding shapefiles</a></li>
<li class="chapter" data-level="2.4" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#reading-shapefiles-into-r-the-wonderful-world-of-sf-objects"><i class="fa fa-check"></i><b>2.4</b> Reading shapefiles into R: the wonderful world of sf objects</a><ul>
<li class="chapter" data-level="2.4.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#homework-2"><i class="fa fa-check"></i><b>2.4.1</b> <strong>HOMEWORK 2</strong></a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#add-some-data"><i class="fa fa-check"></i><b>2.5</b> Add some data</a><ul>
<li class="chapter" data-level="2.5.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>2.5.1</b> Data wrangling with dplyr</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#join-data-to-spatial-object"><i class="fa fa-check"></i><b>2.6</b> Join data to spatial object</a></li>
<li class="chapter" data-level="2.7" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#so-left_join-eh"><i class="fa fa-check"></i><b>2.7</b> So left_join(), eh?</a></li>
<li class="chapter" data-level="2.8" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#lets-make-this-prettier-a-quick-glance-at-tmap"><i class="fa fa-check"></i><b>2.8</b> Let’s make this prettier: a quick glance at tmap</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html"><i class="fa fa-check"></i><b>3</b> Thematic maps in R</a><ul>
<li class="chapter" data-level="3.1" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#intro-and-recap"><i class="fa fa-check"></i><b>3.1</b> Intro and recap</a></li>
<li class="chapter" data-level="3.2" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#creating-choropleth-maps"><i class="fa fa-check"></i><b>3.2</b> Creating choropleth maps</a></li>
<li class="chapter" data-level="3.3" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#producing-small-multiples-to-compare-the-effect-of-different-classification-systems"><i class="fa fa-check"></i><b>3.3</b> Producing small multiples to compare the effect of different classification systems</a><ul>
<li class="chapter" data-level="3.3.1" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#homework-3.1"><i class="fa fa-check"></i><b>3.3.1</b> Homework 3.1</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#using-graduated-symbols"><i class="fa fa-check"></i><b>3.4</b> Using graduated symbols</a></li>
<li class="chapter" data-level="3.5" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#bringing-additional-census-data-in"><i class="fa fa-check"></i><b>3.5</b> Bringing additional census data in</a></li>
<li class="chapter" data-level="3.6" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#computing-and-mapping-crime-rates"><i class="fa fa-check"></i><b>3.6</b> Computing and mapping crime rates</a><ul>
<li class="chapter" data-level="3.6.1" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#homework-2-1"><i class="fa fa-check"></i><b>3.6.1</b> Homework 2</a></li>
<li class="chapter" data-level="3.6.2" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#homework-3"><i class="fa fa-check"></i><b>3.6.2</b> Homework 3</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#more-on-small-multiples-and-point-pattern-maps"><i class="fa fa-check"></i><b>3.7</b> More on small multiples and point pattern maps</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html"><i class="fa fa-check"></i><b>4</b> Performing spatial operations in R</a><ul>
<li class="chapter" data-level="4.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#getting-some-more-data"><i class="fa fa-check"></i><b>4.1</b> Getting some (more) data</a><ul>
<li class="chapter" data-level="4.1.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#reading-data-in-from-the-web"><i class="fa fa-check"></i><b>4.1.1</b> Reading data in from the web</a></li>
<li class="chapter" data-level="4.1.2" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#subsetting-using-pattern-matching"><i class="fa fa-check"></i><b>4.1.2</b> Subsetting using pattern matching</a></li>
<li class="chapter" data-level="4.1.3" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#geocoding-from-an-address"><i class="fa fa-check"></i><b>4.1.3</b> Geocoding from an address</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#making-interactive-maps-with-leaflet"><i class="fa fa-check"></i><b>4.2</b> Making interactive maps with leaflet</a><ul>
<li class="chapter" data-level="4.2.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#making-a-map"><i class="fa fa-check"></i><b>4.2.1</b> Making a map</a></li>
<li class="chapter" data-level="4.2.2" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#adding-some-content"><i class="fa fa-check"></i><b>4.2.2</b> Adding some content:</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#adding-points-manually"><i class="fa fa-check"></i><b>4.3</b> Adding points manually:</a><ul>
<li class="chapter" data-level="4.3.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#adding-data-from-elsewhere"><i class="fa fa-check"></i><b>4.3.1</b> Adding data from elsewhere</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#spatial-operations"><i class="fa fa-check"></i><b>4.4</b> Spatial operations</a><ul>
<li class="chapter" data-level="4.4.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#coordinate-reference-systems-revisited"><i class="fa fa-check"></i><b>4.4.1</b> Coordinate reference systems revisited</a></li>
<li class="chapter" data-level="4.4.2" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#meet-a-new-format-of-shapefile-geojson"><i class="fa fa-check"></i><b>4.4.2</b> Meet a new format of shapefile: geojson</a></li>
<li class="chapter" data-level="4.4.3" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#subset-points-to-those-within-a-polygon"><i class="fa fa-check"></i><b>4.4.3</b> Subset points to those within a polygon</a></li>
<li class="chapter" data-level="4.4.4" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#spatial-operations-two-building-buffers"><i class="fa fa-check"></i><b>4.4.4</b> Spatial operations two: building buffers</a></li>
<li class="chapter" data-level="4.4.5" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#points-in-polygon"><i class="fa fa-check"></i><b>4.4.5</b> Points in Polygon</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#recap"><i class="fa fa-check"></i><b>4.5</b> Recap</a></li>
<li class="chapter" data-level="4.6" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#homework"><i class="fa fa-check"></i><b>4.6</b> Homework</a><ul>
<li class="chapter" data-level="4.6.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#geocode-the-addresses"><i class="fa fa-check"></i><b>4.6.1</b> <strong>Geocode the addresses:</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html"><i class="fa fa-check"></i><b>5</b> More on thematic maps</a><ul>
<li class="chapter" data-level="5.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#introduction-1"><i class="fa fa-check"></i><b>5.1</b> Introduction</a><ul>
<li class="chapter" data-level="5.1.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#pro-tip-do-i-need-to-install-this-package"><i class="fa fa-check"></i><b>5.1.1</b> Pro-tip: do I need to install this package?</a></li>
<li class="chapter" data-level="5.1.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#data"><i class="fa fa-check"></i><b>5.1.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#mapping-rates-learning-from-disease-mapping"><i class="fa fa-check"></i><b>5.2</b> Mapping rates, learning from disease mapping</a></li>
<li class="chapter" data-level="5.3" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#binning-points"><i class="fa fa-check"></i><b>5.3</b> Binning points</a><ul>
<li class="chapter" data-level="5.3.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#the-binning-process"><i class="fa fa-check"></i><b>5.3.1</b> The Binning Process</a></li>
<li class="chapter" data-level="5.3.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#different-binning-techniques"><i class="fa fa-check"></i><b>5.3.2</b> Different Binning Techniques</a></li>
<li class="chapter" data-level="5.3.3" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#homework-5.1"><i class="fa fa-check"></i><b>5.3.3</b> Homework 5.1</a></li>
<li class="chapter" data-level="5.3.4" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#multivariate-binning"><i class="fa fa-check"></i><b>5.3.4</b> Multivariate binning</a></li>
<li class="chapter" data-level="5.3.5" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#benefits-of-binning"><i class="fa fa-check"></i><b>5.3.5</b> Benefits of Binning</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#a-note-of-caution-maup"><i class="fa fa-check"></i><b>5.4</b> A note of caution: MAUP</a><ul>
<li class="chapter" data-level="5.4.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#what-is-maup"><i class="fa fa-check"></i><b>5.4.1</b> What is MAUP?</a></li>
<li class="chapter" data-level="5.4.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#why-does-maup-matter"><i class="fa fa-check"></i><b>5.4.2</b> Why does MAUP matter?</a></li>
<li class="chapter" data-level="5.4.3" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#what-can-we-do"><i class="fa fa-check"></i><b>5.4.3</b> What can we do?</a></li>
<li class="chapter" data-level="5.4.4" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#homework-5.2"><i class="fa fa-check"></i><b>5.4.4</b> Homework 5.2</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#replacing-polygons-with-grid-or-hex-shapes"><i class="fa fa-check"></i><b>5.5</b> Replacing polygons with grid or hex shapes</a><ul>
<li class="chapter" data-level="5.5.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#homework-5.3"><i class="fa fa-check"></i><b>5.5.1</b> Homework 5.3</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#cartograms"><i class="fa fa-check"></i><b>5.6</b> Cartograms</a></li>
<li class="chapter" data-level="5.7" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#references-and-further-reading"><i class="fa fa-check"></i><b>5.7</b> References and further reading</a><ul>
<li class="chapter" data-level="5.7.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#binning"><i class="fa fa-check"></i><b>5.7.1</b> Binning</a></li>
<li class="chapter" data-level="5.7.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#maup"><i class="fa fa-check"></i><b>5.7.2</b> MAUP</a></li>
<li class="chapter" data-level="5.7.3" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#transforming-polygons"><i class="fa fa-check"></i><b>5.7.3</b> Transforming polygons</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html"><i class="fa fa-check"></i><b>6</b> Studying spatial point patterns</a><ul>
<li class="chapter" data-level="6.1" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#what-well-do-today"><i class="fa fa-check"></i><b>6.1</b> What we’ll do today</a></li>
<li class="chapter" data-level="6.2" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#getting-the-data"><i class="fa fa-check"></i><b>6.2</b> Getting the data</a></li>
<li class="chapter" data-level="6.3" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#getting-the-data-into-spatstat-the-problem-with-duplicates"><i class="fa fa-check"></i><b>6.3</b> Getting the data into spatstat: the problem with duplicates</a></li>
<li class="chapter" data-level="6.4" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#inspecting-our-data-with-spatstat"><i class="fa fa-check"></i><b>6.4</b> Inspecting our data with spatstat</a></li>
<li class="chapter" data-level="6.5" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#density-estimates"><i class="fa fa-check"></i><b>6.5</b> Density estimates</a></li>
<li class="chapter" data-level="6.6" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#adding-some-context"><i class="fa fa-check"></i><b>6.6</b> Adding some context</a><ul>
<li class="chapter" data-level="6.6.1" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#homework-1-1"><i class="fa fa-check"></i><b>6.6.1</b> Homework 1</a></li>
<li class="chapter" data-level="6.6.2" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#homework-2-2"><i class="fa fa-check"></i><b>6.6.2</b> Homework 2</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#spatial-point-patterns-along-networks"><i class="fa fa-check"></i><b>6.7</b> Spatial point patterns along networks</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html"><i class="fa fa-check"></i><b>7</b> Global and local spatial autocorrelation</a><ul>
<li class="chapter" data-level="7.1" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#get-data"><i class="fa fa-check"></i><b>7.1</b> Get data</a></li>
<li class="chapter" data-level="7.2" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#what-is-a-neighbour"><i class="fa fa-check"></i><b>7.2</b> What is a neighbour?</a><ul>
<li class="chapter" data-level="7.2.1" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#homework-1-2"><i class="fa fa-check"></i><b>7.2.1</b> Homework 1</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#creating-a-list-of-neighbours"><i class="fa fa-check"></i><b>7.3</b> Creating a list of neighbours</a></li>
<li class="chapter" data-level="7.4" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#generating-the-weight-matrix"><i class="fa fa-check"></i><b>7.4</b> Generating the weight matrix</a><ul>
<li class="chapter" data-level="7.4.1" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#homework-2-3"><i class="fa fa-check"></i><b>7.4.1</b> Homework 2</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#compute-morans-i"><i class="fa fa-check"></i><b>7.5</b> Compute Moran’s I</a><ul>
<li class="chapter" data-level="7.5.1" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#homework-3-optional-practice"><i class="fa fa-check"></i><b>7.5.1</b> Homework 3 (Optional Practice)</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#week-7-local-spatial-autocorrelation"><i class="fa fa-check"></i><b>7.6</b> Week 7 : Local spatial autocorrelation</a></li>
<li class="chapter" data-level="7.7" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#prelude-1"><i class="fa fa-check"></i><b>7.7</b> Prelude</a></li>
<li class="chapter" data-level="7.8" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#get-data-and-built-the-weight-matrix"><i class="fa fa-check"></i><b>7.8</b> Get data and built the weight matrix</a></li>
<li class="chapter" data-level="7.9" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#generating-and-visualising-the-lisa-measures"><i class="fa fa-check"></i><b>7.9</b> Generating and visualising the LISA measures</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html"><i class="fa fa-check"></i><b>8</b> Regression analysis (a refresher)</a><ul>
<li class="chapter" data-level="8.1" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#introduction-2"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#motivating-regression"><i class="fa fa-check"></i><b>8.2</b> Motivating regression</a></li>
<li class="chapter" data-level="8.3" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#fitting-a-simple-regression-model"><i class="fa fa-check"></i><b>8.3</b> Fitting a simple regression model</a></li>
<li class="chapter" data-level="8.4" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#residuals-revisited-r-squared"><i class="fa fa-check"></i><b>8.4</b> Residuals revisited: R squared</a></li>
<li class="chapter" data-level="8.5" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#inference-with-regression"><i class="fa fa-check"></i><b>8.5</b> Inference with regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#fitting-regression-with-categorical-predictors"><i class="fa fa-check"></i><b>8.6</b> Fitting regression with categorical predictors</a></li>
<li class="chapter" data-level="8.7" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#motivating-multiple-regression"><i class="fa fa-check"></i><b>8.7</b> Motivating multiple regression</a></li>
<li class="chapter" data-level="8.8" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#fitting-and-interpreting-a-multiple-regression-model"><i class="fa fa-check"></i><b>8.8</b> Fitting and interpreting a multiple regression model</a></li>
<li class="chapter" data-level="8.9" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#presenting-your-regression-results."><i class="fa fa-check"></i><b>8.9</b> Presenting your regression results.</a></li>
<li class="chapter" data-level="8.10" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#rescaling-input-variables-to-assist-interpretation"><i class="fa fa-check"></i><b>8.10</b> Rescaling input variables to assist interpretation</a></li>
<li class="chapter" data-level="8.11" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#testing-conditional-hypothesis-interactions"><i class="fa fa-check"></i><b>8.11</b> Testing conditional hypothesis: interactions</a></li>
<li class="chapter" data-level="8.12" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#model-building-and-variable-selection"><i class="fa fa-check"></i><b>8.12</b> Model building and variable selection</a></li>
<li class="chapter" data-level="8.13" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#regression-assumptions"><i class="fa fa-check"></i><b>8.13</b> Regression assumptions</a><ul>
<li class="chapter" data-level="8.13.1" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#homework-4"><i class="fa fa-check"></i><b>8.13.1</b> HOMEWORK</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html"><i class="fa fa-check"></i><b>9</b> Spatial regression models</a><ul>
<li class="chapter" data-level="9.1" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#introduction-3"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#looking-at-the-residuals-and-testing-for-spatial-autocorrelation-in-regression"><i class="fa fa-check"></i><b>9.2</b> Looking at the residuals and testing for spatial autocorrelation in regression</a></li>
<li class="chapter" data-level="9.3" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#what-to-do-now"><i class="fa fa-check"></i><b>9.3</b> What to do now?</a></li>
<li class="chapter" data-level="9.4" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#spatial-regimes"><i class="fa fa-check"></i><b>9.4</b> Spatial Regimes</a><ul>
<li class="chapter" data-level="9.4.1" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#homework-1-3"><i class="fa fa-check"></i><b>9.4.1</b> HOMEWORK 1</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#lagrange-multipliers"><i class="fa fa-check"></i><b>9.5</b> Lagrange multipliers</a><ul>
<li class="chapter" data-level="9.5.1" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#homework-2-4"><i class="fa fa-check"></i><b>9.5.1</b> HOMEWORK 2</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#fitting-and-interpreting-a-spatially-lagged-model"><i class="fa fa-check"></i><b>9.6</b> Fitting and interpreting a spatially lagged model</a></li>
<li class="chapter" data-level="9.7" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#fitting-an-interpreting-a-spatial-error-model"><i class="fa fa-check"></i><b>9.7</b> Fitting an interpreting a spatial error model</a><ul>
<li class="chapter" data-level="9.7.1" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#homework-3-1"><i class="fa fa-check"></i><b>9.7.1</b> HOMEWORK 3</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="spatial-regression-models.html"><a href="spatial-regression-models.html#interpreting-spatial-lag-coefficiences"><i class="fa fa-check"></i><b>9.8</b> Interpreting Spatial Lag Coefficiences</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="time-matters.html"><a href="time-matters.html"><i class="fa fa-check"></i><b>10</b> Time matters</a><ul>
<li class="chapter" data-level="10.1" data-path="time-matters.html"><a href="time-matters.html#crime-and-incident-trend-identification"><i class="fa fa-check"></i><b>10.1</b> Crime and incident trend identification</a><ul>
<li class="chapter" data-level="10.1.1" data-path="time-matters.html"><a href="time-matters.html#lubridate-your-guardian-angel-when-it-comes-to-working-with-temporal-data"><i class="fa fa-check"></i><b>10.1.1</b> Lubridate: your guardian angel when it comes to working with temporal data</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="time-matters.html"><a href="time-matters.html#aggregating-to-simple-intervals"><i class="fa fa-check"></i><b>10.2</b> Aggregating to simple intervals</a><ul>
<li class="chapter" data-level="10.2.1" data-path="time-matters.html"><a href="time-matters.html#aggregating-burglary-to-hour"><i class="fa fa-check"></i><b>10.2.1</b> Aggregating burglary to hour</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="time-matters.html"><a href="time-matters.html#visualising-time-on-a-map"><i class="fa fa-check"></i><b>10.3</b> Visualising time on a map</a></li>
<li class="chapter" data-level="10.4" data-path="time-matters.html"><a href="time-matters.html#time-series"><i class="fa fa-check"></i><b>10.4</b> Time series</a><ul>
<li class="chapter" data-level="10.4.1" data-path="time-matters.html"><a href="time-matters.html#moving-averages"><i class="fa fa-check"></i><b>10.4.1</b> Moving averages</a></li>
<li class="chapter" data-level="10.4.2" data-path="time-matters.html"><a href="time-matters.html#moving-average-in-r"><i class="fa fa-check"></i><b>10.4.2</b> Moving average in R</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Crime Mapping in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="more-on-thematic-maps" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> More on thematic maps</h1>
<div id="introduction-1" class="section level2">
<h2><span class="header-section-number">5.1</span> Introduction</h2>
<p>In this session we are going to discuss some additional features around thematic maps we did not cover in week 3. We are going to discuss how to address some of the problems we confront when we are trying to use use choropleth maps, as well as some alternatives to point based maps. We will also introduce the modifieable area unit problem.</p>
<p>Before we do any of this, we need to load the libraries we will use today:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(sf)</code></pre>
<pre><code>## Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tmap)
<span class="kw">library</span>(sp)
<span class="kw">library</span>(spdep)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: spData</code></pre>
<pre><code>## To access larger datasets in this package, install the spDataLarge
## package with: `install.packages(&#39;spDataLarge&#39;,
## repos=&#39;https://nowosad.github.io/drat/&#39;, type=&#39;source&#39;))`</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(DCluster)</code></pre>
<pre><code>## Loading required package: boot</code></pre>
<pre><code>## Loading required package: MASS</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(cartogram)
<span class="kw">library</span>(ggmap)</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:MASS&#39;:
## 
##     select</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<p>There are also some new libraries we will use. If you don’t already have these you will need to install them.</p>
<div id="pro-tip-do-i-need-to-install-this-package" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Pro-tip: do I need to install this package?</h3>
<p>You might have noticed that in your list of available packages you might see more than you remember downloading. The idea of <em>dependencies</em> has come up throughout the semester. Packages have <em>dependencies</em> when their code is <em>dependent</em> on (uses code from) another package. For example, if I write some code that I think will be useful, so I release this in the form of the package “rekaR”, but I use ggplot2 in the code, then ggplot2 will be a dependency of rekaR. As a default, R will install all the dependencies for a package when you install your package. So this way you might end up with some packages there that you didn’t realise you had.</p>
<p>Why am I telling you this? Well you should always check if you have a package, before installing it. And I wanted to share with you some neat code from a Stackoverflow discussion (if you are not yet familiar with Stackoverflow you have not been Google-ing your error messages enough) <a href="https://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them">here</a> to do this. I’ll comment it a bit, so you can follow along what it does <strong>but you don’t have to if you don’t want to</strong>. This is just an optional extra.</p>
<p>So as a first step, you have to assign a list of all the packages you have to check to an object. Let’s say I tell you that today we will be using the following packaes: “sp”, “rgdal”, “classInt”, “RColorBrewer”, “ggplot2”, “hexbin”, “ggmap”, “XML”, and “dplyr”. Then you can add these to an object called <code>libs</code>, using the <code>c()</code> function:</p>
<pre class="sourceCode r"><code class="sourceCode r">libs &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;sf&quot;</span>, <span class="st">&quot;tmap&quot;</span>, <span class="st">&quot;sp&quot;</span>, <span class="st">&quot;spdep&quot;</span>, <span class="st">&quot;DCluster&quot;</span>, <span class="st">&quot;cartogram&quot;</span>)</code></pre>
<p>Now you can run the below bit of code, and you will see in the console an output of what is and isn’t installed, as well as install the packages that are not!</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span> (x <span class="cf">in</span> libs){                                                <span class="co">#cycle through each item in libs object</span>
  <span class="cf">if</span>(x <span class="op">%in%</span><span class="st"> </span><span class="kw">rownames</span>(<span class="kw">installed.packages</span>()) <span class="op">==</span><span class="st"> </span><span class="ot">FALSE</span>) {          <span class="co">#if the package is not installed</span>
    <span class="kw">print</span>(<span class="kw">paste0</span>(<span class="st">&quot;installing &quot;</span>, x, <span class="st">&quot;...&quot;</span>))                      <span class="co">#print a message to tell me</span>
    <span class="kw">install.packages</span>(x)                                         <span class="co">#and then install the packages</span>
  }
  <span class="cf">else</span>{                                                         <span class="co">#otherwise (if it is installed)</span>
    <span class="kw">print</span> (<span class="kw">paste0</span>(x, <span class="st">&quot; is already installed &quot;</span>))                 <span class="co">#print a message to tell me</span>
  }
  <span class="kw">library</span>(x, <span class="dt">character.only =</span> <span class="ot">TRUE</span>)                             <span class="co">#and then load the packages</span>
}</code></pre>
<pre><code>## [1] &quot;sf is already installed &quot;
## [1] &quot;tmap is already installed &quot;
## [1] &quot;sp is already installed &quot;
## [1] &quot;spdep is already installed &quot;
## [1] &quot;DCluster is already installed &quot;
## [1] &quot;cartogram is already installed &quot;</code></pre>
<p>As you can see if you read through the comments there, this bit of code checks each package in the list you pass to tbe <code>libs</code> object when you create it, and if it is not installed it installs for you, and if it is, it just loads it for you. It can be a handy bit of code to keep around.</p>
</div>
<div id="data" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Data</h3>
<p>Then we will bring back data about homicide across US counties. Some of you that have taken previous classes with us may be familiar with this dataset. The dataset was used as the basis for <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1745-9125.2001.tb00933.x">this study</a>. We will be using it also later on in the semester. It contains data on homicide counts and rates for various decades across the US as well as information on structural factors often thought to be associated with violence.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">##R in Windows have some problems with https addresses, that&#39;s why we need to do this first:</span>
urlfile&lt;-<span class="st">&#39;https://s3.amazonaws.com/geoda/data/ncovr.zip&#39;</span>
<span class="kw">download.file</span>(urlfile, <span class="st">&#39;ncovr.zip&#39;</span>)
<span class="co">#Let&#39;s unzip and create a new directory (ncovr) in our working directory to place the files</span>
<span class="kw">unzip</span>(<span class="st">&#39;ncovr.zip&#39;</span>, <span class="dt">exdir =</span> <span class="st">&#39;ncovr&#39;</span>)</code></pre>
<p>Remember that to treat the data as spatial we need to load the shapefile. With that we can create a spatial object:</p>
<pre class="sourceCode r"><code class="sourceCode r">shp_name &lt;-<span class="st"> &quot;ncovr/ncovr/NAT.shp&quot;</span>
ncovr_sf &lt;-<span class="st"> </span><span class="kw">st_read</span>(shp_name)</code></pre>
<pre><code>## Reading layer `NAT&#39; from data source `/Users/reka/Dropbox (The University of Manchester)/crimemapping_textbook_bookdown/ncovr/ncovr/NAT.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 3085 features and 69 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -124.7314 ymin: 24.95597 xmax: -66.96985 ymax: 49.37173
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs</code></pre>
</div>
</div>
<div id="mapping-rates-learning-from-disease-mapping" class="section level2">
<h2><span class="header-section-number">5.2</span> Mapping rates, learning from disease mapping</h2>
<p>In previous sessions we discussed how to map rates. It seems a fairly straightoforward issue, you calculate a rate by dividing your numerator (eg: number of crimes) by your demoninator (eg: daytime population). You get your variable with the relevant rate and you map it using a choropleth map. However, things are not always that simple. Rates are funny animals. Let’s look at the ncvor data.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(ncovr_sf<span class="op">$</span>HR60)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   0.000   2.783   4.504   6.885  92.937</code></pre>
<p>We can see that the county with the highest homicide rate in the 1960s had a rate of 92.937 homicides per 100,000 individuals. That is very high. Just to put it into context in the UK is about 0.92. Where is that place? I can tell you is a place call Borden. Check it out:</p>
<pre class="sourceCode r"><code class="sourceCode r">borden &lt;-<span class="st"> </span><span class="kw">subset</span>(ncovr_sf, NAME <span class="op">==</span><span class="st"> &quot;Borden&quot;</span>)
borden<span class="op">$</span>HR60</code></pre>
<pre><code>## [1] 92.9368</code></pre>
<p><a href="https://en.wikipedia.org/wiki/Borden_County,_Texas">Borden county</a> in Texas. You may be thinking… “Texas Chainsaw Massacre” perhaps? No, not really. Ed Gein, who inspired the film, was based and operated in Wisconsin. Borden claim to fame is that it was named after Gail Borden, the inventor of condensed milk. So, what’s going on here? Why do we have a homicide rate in Borden that makes it look like a war zone or the setting for Midsomer Murders? Is is that it is only one of the six counties where alcohol is banned in Texas (and people are consequently going nuts?).</p>
<p>Check this out too:</p>
<pre class="sourceCode r"><code class="sourceCode r">borden<span class="op">$</span>HC60</code></pre>
<pre><code>## [1] 1</code></pre>
<p>What? A total homicide count of 1. How can a county with just one homicide have a rate that makes it look like the most dangerous place in the US?</p>
<pre class="sourceCode r"><code class="sourceCode r">borden<span class="op">$</span>PO60</code></pre>
<pre><code>## [1] 1076</code></pre>
<p>Well, there were about 1076 people living there.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(ncovr_sf<span class="op">$</span>PO60)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     208    9417   18408   57845   39165 7781984</code></pre>
<p>If you contrast that with the average county in the US, that’s tiny. One homicide in such a small place can end up producing a big rate. Remember that the rate is simply dividing the number of relevant events by the exposure variable (in this case population) and multiplying by a constant (in this case 100,000 since we expressed crime rates in those terms). Most times Borden is a very peaceful place:</p>
<pre class="sourceCode r"><code class="sourceCode r">borden<span class="op">$</span>HR70</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">borden<span class="op">$</span>HR80</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">borden<span class="op">$</span>HR90</code></pre>
<pre><code>## [1] 0</code></pre>
<p>It has a homicide rate of 0 in most decades. But it only takes one homicide and, bang, it goes top of the league. So a standard map of rates is bound to be noisy. There is the instability that is introduced by virtue of having areas that may be sparsely populated and in which one single event, like in this case, will produce a very noticeable change in the rate. In fact, if you look at the counties with the highest homicide rate in the ncovr dataset you will notice all of them are places like Borden, areas that are sparsely populated, not because they are that dangerous, but because of the instability of rates.</p>
<p>This is a problem that was first noted by epidemiologists doing disease mapping. But a number of other disciplines have now noted this and used some of the approaches developed by public health researchers that confronted this problem when producing maps of disease (PRO TIP: techniques and approaches used by spatial epidemiologists are very similar to those used by criminologists -in case you ever think of changing careers or need inspiration for how to solve a crime analysis problem).</p>
<p>One way of dealing with this is by <strong>smoothing</strong> the rates. This basically as the word implies aims for a smoother representation that avoids hard spikes associated with random noise. There are different ways of doing that. Some ways use a non-spatial approach to smoothing, using something called a <strong>empirical bayesian smoother</strong>. How does this work? This approach takes the raw rates and tries to “shrunk” them towards the overall average. What does this mean? Essentially, we compute a weighted average between the raw rate for each area and the global average across all areas, with weights proportional to the underlying population at risk. What this procedure does is to have the rates of smaller areas (those with a small population at risk) to have their rates adjusted considerably (brought closer to the global average), whereas the rates for the larger areas will barely change.</p>
<p>Here we are going to introduce the approach implemented in <code>DCluster</code>, a package developed for epidemiological research and detection of <a href="https://www.r-project.org/conferences/DSC-2003/Proceedings/GomezRubioEtAl.pdf">clusters of disease</a>.</p>
<pre class="sourceCode r"><code class="sourceCode r">res &lt;-<span class="st"> </span><span class="kw">empbaysmooth</span>(ncovr_sf<span class="op">$</span>HC60, ncovr_sf<span class="op">$</span>PO60)</code></pre>
<p>In the new object we generate, which is a list, you have an element which contains the computed rates. We can add those to our dataset:</p>
<pre class="sourceCode r"><code class="sourceCode r">ncovr_sf<span class="op">$</span>HR60EBS &lt;-<span class="st"> </span>res<span class="op">$</span>smthrr <span class="op">*</span><span class="st"> </span><span class="dv">100000</span></code></pre>
<p>Instead of shrinking to the global rate, we can shrink to a rate based on the neighbours of each county. If instead of shrinking to a global rate, we shrink to a local rate, we may be able to take unobserved heterogeneity into account; for this we need the list of neighbours (we will discuss this code in a later session, so for now just trust us we are computing the rate of the areas that surround each country):</p>
<pre class="sourceCode r"><code class="sourceCode r">ncovr_sp &lt;-<span class="st"> </span><span class="kw">as</span>(ncovr_sf, <span class="st">&quot;Spatial&quot;</span>)
w_nb &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(ncovr_sp, <span class="dt">row.names=</span>ncovr_sp<span class="op">$</span>FIPSNO)
eb2 &lt;-<span class="st"> </span><span class="kw">EBlocal</span>(ncovr_sf<span class="op">$</span>HC60, ncovr_sf<span class="op">$</span>PO60, w_nb)
ncovr_sf<span class="op">$</span>HR60EBSL &lt;-<span class="st"> </span>eb2<span class="op">$</span>est <span class="op">*</span><span class="st"> </span><span class="dv">100000</span></code></pre>
<p>We can now plot the maps and compare them:</p>
<pre class="sourceCode r"><code class="sourceCode r">current_style &lt;-<span class="st"> </span><span class="kw">tmap_style</span>(<span class="st">&quot;col_blind&quot;</span>)</code></pre>
<pre><code>## tmap style set to &quot;col_blind&quot;</code></pre>
<pre><code>## other available styles are: &quot;white&quot;, &quot;gray&quot;, &quot;natural&quot;, &quot;cobalt&quot;, &quot;albatross&quot;, &quot;beaver&quot;, &quot;bw&quot;, &quot;classic&quot;, &quot;watercolor&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">map1&lt;-<span class="st"> </span><span class="kw">tm_shape</span>(ncovr_sf) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&quot;HR60&quot;</span>, <span class="dt">style=</span><span class="st">&quot;quantile&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Raw rate&quot;</span>, <span class="dt">palette =</span> <span class="st">&quot;Reds&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="st">&quot;left&quot;</span>, <span class="st">&quot;bottom&quot;</span>), 
            <span class="dt">legend.title.size =</span> <span class="fl">0.8</span>,
            <span class="dt">legend.text.size =</span> <span class="fl">0.5</span>)

map2&lt;-<span class="st"> </span><span class="kw">tm_shape</span>(ncovr_sf) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&quot;HR60EBS&quot;</span>, <span class="dt">style=</span><span class="st">&quot;quantile&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;EB Smooth&quot;</span>, <span class="dt">palette =</span> <span class="st">&quot;Reds&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="st">&quot;left&quot;</span>, <span class="st">&quot;bottom&quot;</span>), 
            <span class="dt">legend.title.size =</span> <span class="fl">0.8</span>,
            <span class="dt">legend.text.size =</span> <span class="fl">0.5</span>)

map3&lt;-<span class="st"> </span><span class="kw">tm_shape</span>(ncovr_sf) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&quot;HR60EBSL&quot;</span>, <span class="dt">style=</span><span class="st">&quot;quantile&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Local Smooth&quot;</span>, <span class="dt">palette =</span> <span class="st">&quot;Reds&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="st">&quot;left&quot;</span>, <span class="st">&quot;bottom&quot;</span>), 
            <span class="dt">legend.title.size =</span> <span class="fl">0.8</span>,
            <span class="dt">legend.text.size =</span> <span class="fl">0.5</span>)

<span class="kw">tmap_arrange</span>(map1, map2, map3) </code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Notice that the quantiles are not the same, so that will make your comparison difficult.</p>
</div>
<div id="binning-points" class="section level2">
<h2><span class="header-section-number">5.3</span> Binning points</h2>
<p>In GIS it is often difficult to present point-based data because in many instances there are several different points and data symbologies that need to be shown. As the number of different data points grows they can become complicated to interpret and manage which can result in convoluted and sometimes inaccurate maps. This becomes an even larger problem in web maps that are able to be depicted at different scales because smaller scale maps need to show more area and more data. This makes the maps convoluted if multiple data points are included.</p>
<p>In many maps there are so many data points included that little can be interpreted from them. In order to reduce congestion on maps many GIS users and cartographers have turned to a process known as binning.</p>
<blockquote>
<p><strong>Binning</strong> is defined as the process of grouping pairs of locations based on their distance from one another. These points can then be grouped as categories to make less complex and more meaningful maps.</p>
</blockquote>
<p>Researchers and practitioners often require a way to systematically divide a region into equal-sized portions. As well as making maps with many points easier to read, binning data into regions can help identify spatial influence of neighbourhoods, and can be an essential step in developing systematic sampling designs.</p>
<p>This approach to binning generates an array of repeating shapes over a user-specified area. These shapes can be hexagons, squares, rectangles, triangles, circles or points, and they can be generated with any directional orientation.</p>
<p><img src="http://www.jennessent.com/images/shape_patterns_manual.jpg" /></p>
<div id="the-binning-process" class="section level3">
<h3><span class="header-section-number">5.3.1</span> The Binning Process</h3>
<p>Binning is a data modification technique that changes the way data is shown at small scales. It is done in the pre-processing stage of data analysis to convert the original data values into a range of small intervals, known as a bin. These bins are then replaced by a value that is representative of the interval to reduce the number of data points.</p>
<p>Spatial binning (also called <em>spatial discretization</em>) discretizes the location values into a small number of groups associated with geographical areas or shapes. The assignment of a location to a group can be done by any of the following methods:
- Using the coordinates of the point to identify which “bin” it belongs to.
- Using a common variable in the attribute table of the bin and the point layers.</p>
</div>
<div id="different-binning-techniques" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Different Binning Techniques</h3>
<p>Binning itself is a general term used to describe the grouping of a dataset’s values into smaller groups <a href="http://indiemaps.com/blog/2011/10/hexbins/">(Johnson, 2011)</a>. The bins can be based on a variety of factors and attributes such as spatial and temporal and can thus be used for many different projects.</p>
<div id="choropleth-maps" class="section level4">
<h4><span class="header-section-number">5.3.2.1</span> Choropleth maps</h4>
<p>You might be thinkging, “grouping points into a larger spatial unit, haven’t we already done this when making choropleth maps?”. In a way you are right. Choropleth maps are another type of map to that uses binning. Proportional symbol and choropleth maps group similar data points together to show a range of data instead of many individual points. We’ve covered this extensively, and is generally the best approch to consider spatial grouping of your point variables, because the polygons (shapes) to which you are aggregating your points are <em>meaningful</em>. You can group into LSOAs because you want to show variation in neighbourhoods. Or you can group into police force areas because you want to look at differences between those units of analysis. But sometimes there is just not a geography present to meet your needs.</p>
<p>Let’s say you are conducting some days of action in Manchester city centre, focusing on antisocial behaviour. You are going to put up some information booths and staff them with officers to engage with the local population about antiscoail behaviour. For these to be most effective, as an analyst you decide that they should go into the areas with the highest <em>count</em> of antisocial beaviour. You want to be very specific about where you put these as well, and so LSOA level would be too broad, you want to zoom in more. One approach can be to split central Manchester into some smaller polygons, and just calculate the number of antisocial behaviour incidents recorded in each. That way you can then decide to put your information booths somewhere inside the top 5 highest count bins.</p>
</div>
<div id="rectangular-binning" class="section level4">
<h4><span class="header-section-number">5.3.2.2</span> Rectangular binning</h4>
<p>The aggregation of incident point data to regularly shaped grids is used for many reasons such as normalizing geography for mapping or to mitigate the issues of using irregularly shaped polygons created arbitrarily (such as county boundaries or block groups that have been created from a political process). Regularly shaped grids can only be comprised of equilateral triangles, squares, or hexagons, as these three polygon shapes are the only three that can tessellate (repeating the same shape over and over again, edge to edge, to cover an area without gaps or overlaps) to create an evenly spaced grid.</p>
<p>Rectangular binning is the simplest binning method and as such it heavily used. However, there are some reasons why rectangular bins are less preferable over hexagonal bins. Before we cover this, let’s have a look at hexagonal bins.</p>
</div>
<div id="hexagonal-binning" class="section level4">
<h4><span class="header-section-number">5.3.2.3</span> Hexagonal binning</h4>
<p>In many applications binning is done using a technique called <strong>hexagonal binning</strong>. This technique uses hexagon shapes to create a grid of points and develops a spatial histogram that shows different data points as a range or group of pairs with common distances and directions. In hexagonal binning the number of points falling within a particular rectangular or hexagon in a gridded surface is what makes the different colors to easily visualize data <a href="https://www.mapbox.com/blog/binning-alternative-point-maps/">(Smith, 2012)</a>. Hexagonnal binning was first developed in 1987 and today “hexbinning” is conducted by laying a hexagonal grid on top of 2-dimensional data <a href="http://indiemaps.com/blog/2011/10/hexbins/">(Johnson, 2011)</a>. Once this is done users can conduct data point counts to determine the number of points for each hexagon <a href="http://indiemaps.com/blog/2011/10/hexbins/">(Johnson, 2011)</a>. The bins are then symbolized differently to show meaningful patterns in the data.</p>
<p>So how can we use hexbinning to solve our antisocial behaviour days of action task? Well let’s say we split Manchester city centre into hexagons, and count the number of antisocial behaviour instances in these. We can then identify the top hexagons, and locate our booths somewhere within these.</p>
<p>First make sure you have the appropriate packages loaded:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(ggmap)
<span class="kw">library</span>(hexbin)</code></pre>
<p>Also let’s get some data. You could go and get this data yourself from police.uk, we’ve been through all the steps for downloading data from there a few times now. But for now, I have a tidied set of data ready for you. This data is one year’s worth of antisocial behaviour from the <a href="data.police.uk">police.uk</a> data, from May 2016 to May 2017, for the borough of Manchester.</p>
<p>We can take our GMP crimes data, and select only the cases from ASB using the crime.type variable. If you want, however, I have already done this, so you can also download from my dropbox using the link here:</p>
<pre class="sourceCode r"><code class="sourceCode r">manchester_asb &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://www.dropbox.com/s/4tk0aps3jfd9nh4/manchester_asb.csv?dl=1&quot;</span>)</code></pre>
<p>This is currently just a text dataframe, so we need to let R know that actually this is a spatial object, who’s geometry can be find in its longitude and latitude coordinates. As we have long/lat we can assure it’s in WGS 84 projection.</p>
<pre class="sourceCode r"><code class="sourceCode r">ma_spatial &lt;-<span class="st"> </span><span class="kw">st_as_sf</span>(manchester_asb, <span class="dt">coords =</span> <span class="kw">c</span>(<span class="st">&quot;Longitude&quot;</span>, <span class="st">&quot;Latitude&quot;</span>), 
                 <span class="dt">crs =</span> <span class="dv">4326</span>, <span class="dt">agr =</span> <span class="st">&quot;constant&quot;</span>)</code></pre>
<p>Now one thing that this does is it consumes our Long and Lat columnsinto a geometry attribute. This is generally OK, but for the binning we will do, we would like to have them as separate coordinates. To do this, we can use a bespoke function, <code>sfc_as_cols()</code> created by <a href="https://github.com/jmlondon">Josh M. London</a> in response to this <a href="https://github.com/r-spatial/sf/issues/231">issue opened on github for the sf package</a>. To create this function here, run the below code:</p>
<pre class="sourceCode r"><code class="sourceCode r">sfc_as_cols &lt;-<span class="st"> </span><span class="cf">function</span>(x, <span class="dt">names =</span> <span class="kw">c</span>(<span class="st">&quot;x&quot;</span>,<span class="st">&quot;y&quot;</span>)) {
  <span class="kw">stopifnot</span>(<span class="kw">inherits</span>(x,<span class="st">&quot;sf&quot;</span>) <span class="op">&amp;&amp;</span><span class="st"> </span><span class="kw">inherits</span>(sf<span class="op">::</span><span class="kw">st_geometry</span>(x),<span class="st">&quot;sfc_POINT&quot;</span>))
  ret &lt;-<span class="st"> </span>sf<span class="op">::</span><span class="kw">st_coordinates</span>(x)
  ret &lt;-<span class="st"> </span>tibble<span class="op">::</span><span class="kw">as_tibble</span>(ret)
  <span class="kw">stopifnot</span>(<span class="kw">length</span>(names) <span class="op">==</span><span class="st"> </span><span class="kw">ncol</span>(ret))
  x &lt;-<span class="st"> </span>x[ , <span class="op">!</span><span class="kw">names</span>(x) <span class="op">%in%</span><span class="st"> </span>names]
  ret &lt;-<span class="st"> </span><span class="kw">setNames</span>(ret,names)
  dplyr<span class="op">::</span><span class="kw">bind_cols</span>(x,ret)
}</code></pre>
<p>As we are not covering making your own function much here, don’t worry too much about the above code, but if you’re curious, raise your hand in the labs and we can come around and talk through it.</p>
<p>Now finally, let’s use this function we just created to extract the coords to some columns. So in this function, we have to pass as parameters the name of the dataframe, ma_spatial in our case, and also what we want the columnd to be called in a concatenated list (created with the <code>c()</code> function). Let’s call these “lng” and “lat”:</p>
<pre class="sourceCode r"><code class="sourceCode r">ma_spatial &lt;-<span class="st"> </span><span class="kw">sfc_as_cols</span>(ma_spatial, <span class="kw">c</span>(<span class="st">&quot;lng&quot;</span>, <span class="st">&quot;lat&quot;</span>))</code></pre>
<p>As a first step, we can plot asb in the borough of Manchester using simple ggplot! Remember the data visualisation session from weeks ago? We discussed how ggplot is such a great tool for building visualisations, because you can apply whatever geometry best suits your data. So for us to just have a look at the hexbinned version of our point data of antisocial behaviour, we can use the <code>stat_binhex()</code> function. We can also recreate the thematic map element, as we can use the frequency of points in each hex to shade each hexbin from white (least number of incidents) to red (most nuber of incidents).</p>
<p>So let’s have a go:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(ma_spatial, <span class="kw">aes</span>(lng, lat)) <span class="op">+</span><span class="st">                        </span><span class="co">#define data and variables for x and y axes</span>
<span class="st">  </span><span class="kw">stat_binhex</span>() <span class="op">+</span><span class="st">                                                         </span><span class="co">#add binhex layer (hexbin)</span>
<span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colours =</span> <span class="kw">c</span>(<span class="st">&quot;white&quot;</span>,<span class="st">&quot;red&quot;</span>), <span class="dt">name =</span> <span class="st">&quot;Frequency&quot;</span>)    <span class="co">#add shading based on number of ASB incidents</span></code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Neat, but doesn’t quite tell us <em>where</em> that really dark hexbon actually is. So it would be much better if we could do this with a basemap as the backrgound, rather than our grey ggplot theme.</p>
<p>Now, we can apply the same code as we used above, for the ggplot, to this ggmap, to add our hexbins on top of this basemap:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggspatial) <span class="co">#load ggspatial package for background map tiles</span>

<span class="kw">ggplot</span>(ma_spatial, <span class="kw">aes</span>(<span class="dt">x =</span> lng, <span class="dt">y =</span> lat)) <span class="op">+</span>
<span class="st">  </span><span class="kw">annotation_map_tile</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_binhex</span>(<span class="dt">alpha=</span><span class="fl">0.7</span>) <span class="op">+</span><span class="st">                                                         </span><span class="co">#add binhex layer (hexbin)</span>
<span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colours =</span> <span class="kw">c</span>(<span class="st">&quot;white&quot;</span>,<span class="st">&quot;red&quot;</span>), <span class="dt">name =</span> <span class="st">&quot;Frequency&quot;</span>)    <span class="co">#add shading based on number of ASB incidents </span></code></pre>
<pre><code>## Zoom: 10</code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Now this should give you some more context! Woo!</p>
<p>So I mentioned we’d go over some reasons why you should consider aggregating into a hexagon grid rather than other shape:</p>
<ul>
<li>Hexagons reduce sampling bias due to <a href="https://link.springer.com/chapter/10.1007/978-0-387-09688-9_5">edge effects</a> of the grid shape. The edge effects of bounded space refers to the problem of truncated data that can skew the results of subsequent analyses (we’ll get to this in the next section). This is related to the low perimeter-to-area ratio of the shape of the hexagon. A circle has the lowest ratio but cannot tessellate to form a continuous grid. Hexagons are the most circular-shaped polygon that can tessellate to form an evenly spaced grid.</li>
<li>This circularity of a hexagon grid allows it to represent curves in the patterns of your data more naturally than square grids.</li>
<li>When comparing polygons with equal areas, the more similar to a circle the polygon is, the closer to the centroid the points near the border are (especially points near the vertices). This means that any point inside a hexagon is closer to the centroid of the hexagon than any given point in an equal-area square or triangle would be (this is due to the more acute angles of the square and triangle versus the hexagon).</li>
<li>Hexagons are preferable when your analysis includes aspects of connectivity or movement paths. Due to the linear nature of rectangles, fishnet grids can draw our eyes to the straight, unbroken, parallel lines which may inhibit the underlying patterns in the data. Hexagons tend to break up the lines and allow any curvature of the patterns in the data to be seen more clearly and easily. This breakup of artificial linear patterns also diminishes any orientation bias that can be perceived in fishnet grids.</li>
<li>If you are working over a large area, a hexagon grid will suffer less distortion due to the curvature of the earth than the shape of a fishnet grid.</li>
<li>Finding neighbors is more straightforward with a hexagon grid. Since the edge or length of contact is the same on each side, the centroid of each neighbor is equidistant. However, with a fishnet grid, the Queen’s Case (above/below/right/left) neighbor’s centroids are N units away, while the centroids of the diagonal (Rook) neighbors are farther away (exactly the square root of 2 times N units away).</li>
<li>Since the distance between centroids is the same in all six directions with hexagons, if you are using a distance band to find neighbors or are using the Optimized Hot Spot Analysis, Optimized Outlier Analysis or Create Space Time Cube By Aggregating Points tools, you will have more neighbors included in the calculations for each feature if you are using hexagonal grid as opposed to a fishnet grid.</li>
</ul>
<p><img src="img/EE17F7E03F82-web.png" /></p>
<p>Now, to again illustrate the differences of different approaches, let’s see what this map would look like with:</p>
<ol style="list-style-type: lower-alpha">
<li>rectangular binning:</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(ma_spatial, <span class="kw">aes</span>(<span class="dt">x =</span> lng, <span class="dt">y =</span> lat)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">annotation_map_tile</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_bin2d</span>(<span class="dt">alpha=</span><span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colours =</span> <span class="kw">c</span>(<span class="st">&quot;white&quot;</span>,<span class="st">&quot;red&quot;</span>), 
                       <span class="dt">name =</span> <span class="st">&quot;Frequency&quot;</span>) </code></pre>
<pre><code>## Zoom: 10</code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>hexagonal binning:</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(ma_spatial, <span class="kw">aes</span>(<span class="dt">x =</span> lng, <span class="dt">y =</span> lat)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">annotation_map_tile</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_binhex</span>(<span class="dt">alpha=</span><span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colours =</span> <span class="kw">c</span>(<span class="st">&quot;white&quot;</span>,<span class="st">&quot;red&quot;</span>), 
                       <span class="dt">name =</span> <span class="st">&quot;Frequency&quot;</span>)</code></pre>
<pre><code>## Zoom: 10</code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>a simple “heatmap” (we will discuss these more thoroughly next week):</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(ma_spatial, <span class="kw">aes</span>(<span class="dt">x =</span> lng, <span class="dt">y =</span> lat)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">annotation_map_tile</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_density2d</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> ..level.., <span class="co"># value corresponding to discretized density estimates </span>
                     <span class="dt">alpha =</span> ..level..), 
                 <span class="dt">geom =</span> <span class="st">&quot;polygon&quot;</span>) <span class="op">+</span><span class="st">  </span><span class="co"># creates the bands of differenc colors</span>
<span class="st">  </span><span class="co">## Configure the colors, transparency and panel</span>
<span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colours =</span> <span class="kw">c</span>(<span class="st">&quot;white&quot;</span>,<span class="st">&quot;red&quot;</span>), 
                       <span class="dt">name =</span> <span class="st">&quot;Frequency&quot;</span>) </code></pre>
<pre><code>## Zoom: 11</code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
</div>
<div id="homework-5.1" class="section level3">
<h3><span class="header-section-number">5.3.3</span> Homework 5.1</h3>
<p><em>Look at the difference between the three maps (hex, rectangle, and density). How would your conclusions change if you were given these maps? Would you make different decisions about where to place your booths for the days of action? Why or why not? Discuss.</em></p>
</div>
<div id="multivariate-binning" class="section level3">
<h3><span class="header-section-number">5.3.4</span> Multivariate binning</h3>
<p>Multivariate binning is another binning method that lets you visualise slightly more complex data. In this method there can be many different variables consisting of different types of data. Like other binning methods the data is typically grouped with the sum or average of the data. Different types of symbology (such as size, shape and color) can also be used to represent this data as well.</p>
<p>We won’t be covering this here but just so you can have a look at some examples <a href="https://mgimond.github.io/Spatial/data-manipulation-in-r.html">here</a>.</p>
</div>
<div id="benefits-of-binning" class="section level3">
<h3><span class="header-section-number">5.3.5</span> Benefits of Binning</h3>
<p>Because of the plethora of data types available and the wide variety of projects being done in GIS, binning is a popular method for mapping complex data and making it meaningful. Binning is a good option for map makers as well as users because it makes data easy to understand and it can be both static and interactive on many different map scales. If every different point were shown on a map it would have to be a very large scale map to ensure that the data points did not overlap and were easily understood by people using the maps.</p>
<p>According to Kenneth Field, an Esri Research Cartographer, <em>“Data binning is a great alternative for mapping large point-based data sets which allows us to tell a better story without interpolation. Binning is a way of converting point-based data into a regular grid of polygons so that each polygon represents the aggregation of points that fall within it.”</em></p>
<p>By using binning to create categories of data maps are easier to understand, more accurate and more visually appealing.</p>
<p>Hexbin plots can be viewed as an alternative to scatter plots. The hexagon-shaped bins were introduced to plot densely packed sunflower plots. They can be used to plot scatter plots with high-density data.</p>
</div>
</div>
<div id="a-note-of-caution-maup" class="section level2">
<h2><span class="header-section-number">5.4</span> A note of caution: MAUP</h2>
<p>Now that we’ve shown you how to do a lot of spatial crime analysis, we wanted to close with some words of caution. Remember that everything you’ve learned here are just tools that you will be applying to data you are working with, but it’s up to you, the researcher, the analyst, the domain expert, to apply and use these with careful consideration and cautions. This discussion is very much part of spatial crime analysis, and an important field of thought.</p>
<p>I borrow here from George Renghert and Brian Lockwood:</p>
<blockquote>
<p>When spatial analysis of crime is conducted, the analyst should not ignore the spatial units that data are aggregated into and the impact of this choice on the interpretation of findings. Just as several independent variables are considered to determine whether they have statistical significance, a consideration of multiple spatial units of analysis should be made as well, in order to determine whether the choice of aggregation level used in a spatial analysis can result in biased findings.</p>
</blockquote>
<p>In particular, they highlight four main issues inherent in most studies of space:
- issues associated with politically bounded units of aggregation,
- edge effects of bounded space
- the modifiable aerial unit problem (MAUP)
- and ways in which the results of statistical analyses can be manipulated by changes in the level of
aggregation.</p>
<p>In this lab we will focus on <strong>MAUP</strong>, but if you are interested in this kind of work, you should definitely read their paper to consider the other issues as well. There are techniques that can be used to alleviate each of the methodological difficulties, and they are described in accessible detail in their paper: <a href="https://link.springer.com/chapter/10.1007/978-0-387-09688-9_5">Rengert, George F., and Brian Lockwood. “Geographical units of analysis and the analysis of crime.” Putting crime in its place. Springer, New York, NY, 2009. 109-122.</a></p>
<div id="what-is-maup" class="section level3">
<h3><span class="header-section-number">5.4.1</span> What is MAUP?</h3>
<p>The Modifiable Areal Unit Problem (MAUP) is an important issue for those who conduct spatial analysis using units of analysis at aggregations higher than incident level. It is one of the better-known problems in geography and spatial analysis. This phenomenon illustrates both the need for considering space in one’s analysis, and the fundamental uncertainties that accompany real-world analysis.</p>
<p>The MAUP is &quot;a problem arising from the imposition of artificial units of spatial reporting on continuous geographical phenomena, leading to artifacts or errors are created when one groups data into units for analysis.</p>
<p>The classic text on MAUP is the 1983 paper <a href="https://www.uio.no/studier/emner/sv/iss/SGO9010/openshaw1983.pdf">Openshaw, Stan. “The modifiable areal unit problem. CATMOG (Concepts and techniques in modern geography) 38.” Geo Abstracts, Norwich. 1984.</a>.</p>
<p>There are two distinct types of MAUP: Scale (i.e. determining the appropriate size of units for aggregation) and zone (i.e. drawing boundaries or grouping).</p>
<div id="scale" class="section level4">
<h4><span class="header-section-number">5.4.1.1</span> Scale</h4>
<p>The scale problem involves results that change based on data that are analyzed at higher or lower levels of aggregation (Changing the number of units). For example, evaluating data at the state level vs. Census tract level.</p>
<p>The scale problem has moved to the forefront of geographical criminology as a result of the recent interest in small-scale geographical units of analysis. It has been suggested that smaller is better since small areas can be directly perceived by individuals and are likely to be more homogenous than larger areas.
- <a href="https://link.springer.com/article/10.1007/s10940-016-9297-6">Gerell, Manne. “Smallest is better? The spatial distribution of arson and the modifiable areal unit problem.” Journal of quantitative criminology 33.2 (2017): 293-318.</a></p>
</div>
<div id="zone" class="section level4">
<h4><span class="header-section-number">5.4.1.2</span> Zone</h4>
<p>The zonal problem involves keeping the same scale of research (say, at the state level) but changing the actual shape and size of those areas.</p>
<p>The basic issue with the MAUP is that aggregate units of analysis are often arbitrarily produced by whom ever is in charge of creating the aggregate units. A classic example of this problem is known as Gerrymandering. Gerrymandering involves shaping and re-shaping voting districts based on the political affiliations of the resident citizenry.</p>
<p>The inherent problem with the MAUP and with situations such as Gerrymandering is that units of analysis are not based on geographic principles, and instead are based on political and social biases. For researchers and practitioners the MAUP has very important implications for research findings because it is possible that as arbitrarily defined units of analysis change shape findings based on these units will change as well.</p>
<p>When spatial data are derived from counting or averaging data within areal units, the form of those areal units affects the data recorded, and any statistical measures derived from the data. Modifying the areal units therefore changes the data. Two effects are involved: a zoning effect arising from the particular choice of areas at a given scale; and an aggregation effect arising from the extent to which data are aggregated over smaller or larger areas. The modifiable areal unit problem arises in part from edge effect.</p>
<p>If you’re interested, in particular about politics and voting, you can read this interesting piece to learn <a href="https://projects.fivethirtyeight.com/redistricting-maps/">more about gerrymandering</a></p>
</div>
</div>
<div id="why-does-maup-matter" class="section level3">
<h3><span class="header-section-number">5.4.2</span> Why does MAUP matter?</h3>
<p>The practical implications of MAUP are immense for almost all decision-making processes involving GIS technology, since with the availability of aggregated maps, policy could easily focus on issues and problems which might look different if the aggregation scheme used were changed .</p>
<p>All studies based on geographical areas are susceptible to MAUP. The implications of the MAUP affect potentially any area level data, whether direct measures or complex model-based estimates. Here are a few examples of situations where the MAUP is expected to make a difference:</p>
<ul>
<li>The special case of the ecological fallacy is always present when Census area data are used to formulate and evaluate policies that address problems at individual level, such as deprivation. Also, it is recognised that a potential source of error in the analysis of Census data is ‘the arrangement of continuous space into defined regions for purposes of data reporting’</li>
<li>The MAUP has an impact on indices derived from areal data, such as measures of segregation, which can change significantly as a result of using different geographical levels of analysis to derive composite measures .</li>
<li>The choice of boundaries for reporting mortality ratios is not without consequences: when the areas are too small, the values estimated are unstable, while when the areas are too large, the values reported may be over-smoothed, i.e. meaningful variation may be lost .</li>
<li><a href="https://link.springer.com/article/10.1007/s10940-016-9297-6">Gerell, Manne. “Smallest is better? The spatial distribution of arson and the modifiable areal unit problem.” Journal of quantitative criminology 33.2 (2017): 293-318.</a></li>
</ul>
</div>
<div id="what-can-we-do" class="section level3">
<h3><span class="header-section-number">5.4.3</span> What can we do?</h3>
<p>Most often you will just have to remain aware of the MAUP and it’s possible effects. There are some techniques, that can help you address these issues, and the chapter pointed out at the beginning of this section is a great place to start to explore these. It is possible to use also an alternative, zone-free approach to mapping these crime patterns, perhaps by using kernel density estimation. Here we model the relative density of the points as a density surface - essentially a function of location (x,y) representing the relative likelihood of occurrence of an event at that point. We have covered KDE elsewhere in this course.</p>
<p>For the purposes of this course, it’s enough that you know of, and understand the MAUP and its implications. Always be smart when choosing your appropriate spatial unit of analysis, and when you use binning of any form, make sure you consider how and if your conclusions might change compared to another possible approach.</p>
</div>
<div id="homework-5.2" class="section level3">
<h3><span class="header-section-number">5.4.4</span> Homework 5.2</h3>
<p><em>Look at the question for homework 5.1 about the three maps of binning and the hotspot map. Answer this question again, but now in light of what you have learned about MAUP. </em></p>
</div>
</div>
<div id="replacing-polygons-with-grid-or-hex-shapes" class="section level2">
<h2><span class="header-section-number">5.5</span> Replacing polygons with grid or hex shapes</h2>
<p>When you have meaningful spatial units of analysis in your polygons, for example you are interested specifically in Local Autorities, it might make sense to stick with what we did last week, and aggregate the points into these polygons to cheare thematic maps. However, while thematic maps are an accessible and visually appealing method for displaying spatial information, they can also be highly misleading. Irregularly shaped polygons and large differences in the size of areas being mapped can introduce misrepresentation. The message researchers want to get across might be lost, or even worse, misdirect the viewers to erroneous conclusions. <a href="https://www.tandfonline.com/eprint/q9w7iUhFJwzvBR84GkT9/full">This article</a> provides a helpful discussion of the problem illustrating the case with UK election maps. It is worth reading.</p>
<p>Fortunately, there are many methods in R to enhance the legibility of geographic information and the interpretability of what it is trying to be communicated.</p>
<p>Broadly, the options are:</p>
<ul>
<li>cartogram</li>
<li>hexmap</li>
<li>grid</li>
</ul>
<p>Selecting the appropriate method might depend on the research question being posed (e.g. clustering) and the data itself. Even once a method has been selected, there are different ways of operationalising them. We focus on methods for transforming our maps to hex and gridap. We make grid and hex maps where instead of creating a grid, we reshape the existing polygons into grid or hex shapes. We will also speak about <strong>cartograms</strong>, but I’ll leave that to the next section.</p>
<p>Let’s explore this using the example of the results of the 2016 EU referendum at Local Authority level, where remain areas clustered in London. A simple thematic map does not necessarily communicate this well because Local Authorities are both small and densely populated in London.</p>
<p>You can download the full set of EU referendum result data as a csv from <a href="https://www.electoralcommission.org.uk/find-information-by-subject/elections-and-referendums/past-elections-and-referendums/eu-referendum/eu-referendum-result-visualisations">the Electoral Commission webside</a>. Let’s read it straight into R:</p>
<pre class="sourceCode r"><code class="sourceCode r">eu_ref &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://www.electoralcommission.org.uk/__data/assets/file/0014/212135/EU-referendum-result-data.csv&quot;</span>)</code></pre>
<p>OKAY, now we need a shapefile to join it to. Remember when we got the Manchester lsoa shapefile with the <a href="https://borders.ukdataservice.ac.uk/bds.html">boundary selector</a>? Let’s go back, and this time get <em>Local Authority Districts</em> for <em>England</em>.</p>
<p>In this case that means select “English Districts, UAs and London Boroughs, 2011”:</p>
<p><img src="img/la_shp_dl.png" /></p>
<p>Once you have the file, download, extract (unzip) and put the folder in your working directory. Mine is in a subfolder in my working directory called data, so I point R inside that folder to find my shape file.</p>
<pre class="sourceCode r"><code class="sourceCode r">las &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="st">&quot;data/England_lad_2011_gen/england_lad_2011_gen.shp&quot;</span>)</code></pre>
<pre><code>## Reading layer `england_lad_2011_gen&#39; from data source `/Users/reka/Dropbox (The University of Manchester)/crimemapping_textbook_bookdown/data/England_lad_2011_gen/england_lad_2011_gen.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 326 features and 4 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 82644.8 ymin: 5349.399 xmax: 655976.9 ymax: 657599.5
## epsg (SRID):    NA
## proj4string:    +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +datum=OSGB36 +units=m +no_defs</code></pre>
<p>We can now join the EU referendum data, as we have learned in the past weeks:</p>
<pre class="sourceCode r"><code class="sourceCode r">eu_sf &lt;-<span class="st"> </span><span class="kw">left_join</span>(las, eu_ref, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;name&quot;</span> =<span class="st"> &quot;Area&quot;</span>))</code></pre>
<pre><code>## Warning: Column `name`/`Area` joining factors with different levels,
## coercing to character vector</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#make sure we are in British National Grid Projection</span>
eu_sf &lt;-<span class="st"> </span><span class="kw">st_transform</span>(eu_sf, <span class="dv">27700</span>)</code></pre>
<p>Now we can have a look at these data:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> eu_sf, <span class="kw">aes</span>(<span class="dt">fill =</span> Pct_Leave)) </code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>We can see that in smaller LAs we don’t even really see the result, as the boundary lines pretty much cover everything. Hmm. Now what we can do is transform the shapes into squares of hexagons. Let’s have a go at squares.</p>
<p>We can use the functions in the geogrid package.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(geogrid)</code></pre>
<p>Now we can use the <code>calculate_grid()</code> function. This function, given an input multipolgyon spatial data frame this function calculates a hexagonal or regular grid, that strives to preserve the original geography. Once this is done, we assign each polygon in the original file to a new location in the gridded geometry. <strong>NOTE THIS WILL TAKE A WHILE</strong> again this is something that is quite computationally intensive, so you set it running, and go for a short break. You need short breaks in coding.</p>
<p>However this particular bit of code will actually take about 10 minutes. So if you’re about to leave, wait until you are home to run it.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#first make our sf object into an sp object</span>
eu_sp &lt;-<span class="st"> </span><span class="kw">as</span>(eu_sf, <span class="st">&#39;Spatial&#39;</span>)

<span class="co">#then use the calculate_grid function. Note how we specify grid type to be &quot;regular&quot;.</span>
eu_reg &lt;-<span class="st"> </span><span class="kw">calculate_grid</span>(<span class="dt">shape =</span> eu_sp, <span class="dt">grid_type =</span> <span class="st">&quot;regular&quot;</span>, <span class="dt">seed =</span> <span class="dv">1</span>)
<span class="co">#assign the polygons</span>
eu_reg &lt;-<span class="st"> </span><span class="kw">assign_polygons</span>(eu_sp, eu_reg)

<span class="co">#now turn it back into sf object for easy ggplot plotting</span>
eu_reg &lt;-<span class="st"> </span><span class="kw">st_as_sf</span>(eu_reg)</code></pre>
<p>While you’re waiting for that, you can have a read about how the polygons are assigned. The help file will tell you they use “the Hungarian algorithm”. This is from a paper called <a href="https://pdfs.semanticscholar.org/b6a0/f30260302a2001da9999096cfdd89bc1f7fb.pdf">The Hungarian Method for the Assignment Problem</a> by Harold W. Kuhn. Apparently, this method was so promising, that when Kuhn came across it referenced in a paper, even though the original paper is in Hungarian, Kuhn describes he “took out a Hungarian grammar and a large Hungarian-English dictionary and taught myself enough Hungarian to translate Egervary’s paper.” I can assure you, Hungarian is not an easy language to learn, so this must have been a most excellent theory to prompt such an act.</p>
<p>Now that your code has run, and you have your eu_reg shapefile, we can plot this!</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> eu_reg, <span class="kw">aes</span>(<span class="dt">fill =</span> Pct_Leave)) </code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Cool, eh?</p>
<div id="homework-5.3" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Homework 5.3</h3>
<p><em>Reproduce the above grid map using hexagons instead of squares.</em></p>
</div>
</div>
<div id="cartograms" class="section level2">
<h2><span class="header-section-number">5.6</span> Cartograms</h2>
<p>The last thing we will do today is make some cartograms! Cartogram types of maps distort reality to convey information. They resize and exaggerate any variable on an attribute value.</p>
<p>There are different types of cartograms.</p>
<p>Density-equalizing (contiguous) cartograms are your traditional cartograms. In density-equalizing cartograms, map features bulge out a specific variable. Even though it distorts each feature, it remains connected during its creation. On the other hand, you can have Non-Contiguous Cartograms, where features in non-contiguous cartograms don’t have to stay connected. Finally, Dorling Cartogram (named after professor <a href="https://www.geog.ox.ac.uk/staff/ddorling.html">Danny Dorling</a>) uses shapes like circles and rectangles to depict area. These types of cartograms make it easy to recognize patterns. For example, here is a Darling Cartogram I made of <a href="www.fixmystreet.org">FixMyStreet</a> reports in London:</p>
<p><img src="img/notNaAll3CartogramNewFrame.png" /></p>
<p>Now we can make our own as well, using the cartogram package.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(cartogram)</code></pre>
<p>Within that there is the <code>cartogram()</code> function, which takes 2 arguments, 1 - the shape file (it can be a SpatialPolygonDataFrame or an sf object), and 2 - the variable which it should use to distort the polygon by.</p>
<p>In our data set we have a variable “electorate” which refers to the total number of registered electors</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># construct a cartogram using the percentage voting leave</span>
eu_cartogram &lt;-<span class="st"> </span><span class="kw">cartogram</span>(eu_sf, <span class="st">&quot;Electorate&quot;</span>)</code></pre>
<p>Again this is some labour intensive work, much like the grid making, you have some time to chill now. Maybe read up on the maths behind this tranformation as well, in the paper <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/j.0033-0124.1985.00075.x">Dougenik, J. A., Chrisman, N. R., &amp; Niemeyer, D. R. (1985). An Algorithm To Construct Continuous Area Cartograms. In The Professional Geographer, 37(1), 75-81.</a>.</p>
<p>I do have a tip for you if you want to make sure the process does not take too long. You can set a parameter in the cartogram function which is the “itermax” parameter. This specifies the maximum number of iterations we are happy with. If you don’t specify it’s set to 15. Let’s set to 5 for the sake of speed:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># construct a cartogram using the percentage voting leave</span>
eu_cartogram &lt;-<span class="st"> </span><span class="kw">cartogram_cont</span>(eu_sf, <span class="st">&quot;Electorate&quot;</span>, <span class="dt">itermax =</span> <span class="dv">5</span>)</code></pre>
<pre><code>## Mean size error for iteration 1: 4.11884641548982</code></pre>
<pre><code>## Mean size error for iteration 2: 21.1096264523744</code></pre>
<pre><code>## Mean size error for iteration 3: 3.05848955161026</code></pre>
<pre><code>## Mean size error for iteration 4: 2.51480274961733</code></pre>
<pre><code>## Mean size error for iteration 5: 2.92812677999131</code></pre>
<p>And if your cartogram has been created, you can now plot again the referendum results, but using the electorate to change the size of the locad authority:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> eu_cartogram, <span class="kw">aes</span>(<span class="dt">fill =</span> Pct_Leave)) </code></pre>
<p><img src="05-week5_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>We can now see London much better, and see that darker coloured cluster where much smaller percentage of people voted leave.</p>
<p>Okay that’s probably enough for the day. Nice work crime mappers!</p>
</div>
<div id="references-and-further-reading" class="section level2">
<h2><span class="header-section-number">5.7</span> References and further reading</h2>
<div id="binning" class="section level3">
<h3><span class="header-section-number">5.7.1</span> Binning</h3>
<ul>
<li><a href="http://indiemaps.com/blog/2011/10/hexbins/">Johnson, Zachary Forest. (18 October 2011). “Hexbins!” Retrieved from: http://indiemaps.com/blog/2011/10/hexbins/ (8 August 2014).</a></li>
<li><a href="https://www.mapbox.com/blog/binning-alternative-point-maps/">Smith, Nate. (25 May 2012). “Binning: An Alternative to Point Maps.” Mapbox. Retrieved from: https://www.mapbox.com/blog/binning-alternative-point-maps/ (8 August 2014).</a></li>
<li><a href="http://www.rpubs.com/cengel248/97543">Claudia A Engel’s fantastic R-pub on <em>Making Maps in R</em></a>.</li>
<li><a href="https://www.r-graph-gallery.com/329-hexbin-map-for-distribution/">Hexbin Graph Gallery</a></li>
<li><a href="https://www.r-bloggers.com/u-s-drought-monitoring-with-hexbin-state-maps-in-r/">US Drought Hexmap</a></li>
<li><a href="http://santiago.begueria.es/2016/04/mapping-with-ggplot2-hexbin-maps/">Hexbin with ggplot2</a></li>
</ul>
</div>
<div id="maup" class="section level3">
<h3><span class="header-section-number">5.7.2</span> MAUP</h3>
<ul>
<li><a href="https://link.springer.com/article/10.1007/s10940-016-9297-6">Gerell, Manne. “Smallest is better? The spatial distribution of arson and the modifiable areal unit problem.” Journal of quantitative criminology 33.2 (2017): 293-318.</a></li>
<li><a href="https://www.uio.no/studier/emner/sv/iss/SGO9010/openshaw1983.pdf">Openshaw, Stan. “The modifiable areal unit problem. CATMOG (Concepts and techniques in modern geography) 38.” Geo Abstracts, Norwich. 1984.</a>.</li>
<li><a href="https://link.springer.com/chapter/10.1007/978-0-387-09688-9_5">Rengert, George F., and Brian Lockwood. “Geographical units of analysis and the analysis of crime.” Putting crime in its place. Springer, New York, NY, 2009. 109-122.</a></li>
</ul>
</div>
<div id="transforming-polygons" class="section level3">
<h3><span class="header-section-number">5.7.3</span> Transforming polygons</h3>
<ul>
<li><a href="https://www.tandfonline.com/doi/full/10.1111/j.1467-8306.2004.09401004.x">Waldo Tobler (2004) Thirty Five Years of Computer Cartograms, Annals of the Association of American Geographers, 94:1, 58-73, DOI: 10.1111/j.1467-8306.2004.09401004.x</a></li>
<li><a href="https://rpubs.com/langton_/visual_geography_study">Langton, S.H. &amp; Solymosi, R. (2018) ‘Visualising geographic information: examining methods of improving the thematic map.’ RPubs. Available: https://rpubs.com/langton_/visual_geography_study</a></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="performing-spatial-operations-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="studying-spatial-point-patterns.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/05-week5.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["CrimeMapping.pdf", "CrimeMapping.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
