<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 8 Regression analysis (a refresher) | Crime Mapping in R</title>
  <meta name="description" content="Worksheets for labs of Crime Mapping course">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 8 Regression analysis (a refresher) | Crime Mapping in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Worksheets for labs of Crime Mapping course" />
  <meta name="github-repo" content="maczokni/crimemapping_textbook_bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Regression analysis (a refresher) | Crime Mapping in R" />
  
  <meta name="twitter:description" content="Worksheets for labs of Crime Mapping course" />
  

<meta name="author" content="Juanjo Medina and Reka Solymosi">


<meta name="date" content="2019-02-25">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="global-and-local-spatial-autocorrelation.html">
<link rel="next" href="time-matters.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Crime mapping in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prelude</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i><b>0.1</b> Introduction</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>0.2</b> Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A first lesson about R</a><ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#open-up-and-explore-rstudio"><i class="fa fa-check"></i><b>1.2</b> Open up and explore RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>1.3</b> Customising the RStudio look</a></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>1.4</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="1.5" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#talk-to-your-computer"><i class="fa fa-check"></i><b>1.5</b> Talk to your computer</a></li>
<li class="chapter" data-level="1.6" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-packages"><i class="fa fa-check"></i><b>1.6</b> More on packages</a></li>
<li class="chapter" data-level="1.7" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#using-objects"><i class="fa fa-check"></i><b>1.7</b> Using objects</a></li>
<li class="chapter" data-level="1.8" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-objects"><i class="fa fa-check"></i><b>1.8</b> More on objects</a></li>
<li class="chapter" data-level="1.9" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#vectors"><i class="fa fa-check"></i><b>1.9</b> Vectors</a></li>
<li class="chapter" data-level="1.10" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#on-comments"><i class="fa fa-check"></i><b>1.10</b> On comments</a></li>
<li class="chapter" data-level="1.11" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#factors"><i class="fa fa-check"></i><b>1.11</b> Factors</a></li>
<li class="chapter" data-level="1.12" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#naming-conventions-for-objects-in-r"><i class="fa fa-check"></i><b>1.12</b> Naming conventions for objects in R</a></li>
<li class="chapter" data-level="1.13" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#dataframes"><i class="fa fa-check"></i><b>1.13</b> Dataframes</a></li>
<li class="chapter" data-level="1.14" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#exploring-data"><i class="fa fa-check"></i><b>1.14</b> Exploring data</a></li>
<li class="chapter" data-level="1.15" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#quitting-rstudio"><i class="fa fa-check"></i><b>1.15</b> Quitting RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html"><i class="fa fa-check"></i><b>2</b> Making your first maps in R</a><ul>
<li class="chapter" data-level="2.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#a-quick-introduction-of-terms"><i class="fa fa-check"></i><b>2.1</b> A quick introduction of terms</a><ul>
<li class="chapter" data-level="2.1.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#geospatial-perspective---the-basics"><i class="fa fa-check"></i><b>2.1.1</b> Geospatial Perspective - The Basics</a></li>
<li class="chapter" data-level="2.1.2" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#summary"><i class="fa fa-check"></i><b>2.1.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#getting-some-spatial-data-to-put-on-a-map"><i class="fa fa-check"></i><b>2.2</b> Getting some spatial data to put on a map</a><ul>
<li class="chapter" data-level="2.2.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#a-first-look-at-basemaps"><i class="fa fa-check"></i><b>2.2.1</b> A first look at basemaps</a></li>
<li class="chapter" data-level="2.2.2" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#find-some-relevant-data-to-show-obtaining-data-on-crime"><i class="fa fa-check"></i><b>2.2.2</b> Find some relevant data to show: obtaining data on crime</a></li>
<li class="chapter" data-level="2.2.3" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#add-a-point-layer-to-your-basemap"><i class="fa fa-check"></i><b>2.2.3</b> Add a point layer to your basemap</a></li>
<li class="chapter" data-level="2.2.4" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#homework-1"><i class="fa fa-check"></i><b>2.2.4</b> HOMEWORK 1</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#from-dataframes-to-spatial-objects-finding-shapefiles"><i class="fa fa-check"></i><b>2.3</b> From dataframes to spatial objects: finding shapefiles</a></li>
<li class="chapter" data-level="2.4" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#reading-shapefiles-into-r-the-wonderful-world-of-sf-objects"><i class="fa fa-check"></i><b>2.4</b> Reading shapefiles into R: the wonderful world of sf objects</a><ul>
<li class="chapter" data-level="2.4.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#homework-2"><i class="fa fa-check"></i><b>2.4.1</b> <strong>HOMEWORK 2</strong></a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#add-some-data"><i class="fa fa-check"></i><b>2.5</b> Add some data</a><ul>
<li class="chapter" data-level="2.5.1" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>2.5.1</b> Data wrangling with dplyr</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#join-data-to-spatial-object"><i class="fa fa-check"></i><b>2.6</b> Join data to spatial object</a></li>
<li class="chapter" data-level="2.7" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#so-left_join-eh"><i class="fa fa-check"></i><b>2.7</b> So left_join(), eh?</a></li>
<li class="chapter" data-level="2.8" data-path="making-your-first-maps-in-r.html"><a href="making-your-first-maps-in-r.html#lets-make-this-prettier-a-quick-glance-at-tmap"><i class="fa fa-check"></i><b>2.8</b> Let’s make this prettier: a quick glance at tmap</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html"><i class="fa fa-check"></i><b>3</b> Thematic maps in R</a><ul>
<li class="chapter" data-level="3.1" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#intro-and-recap"><i class="fa fa-check"></i><b>3.1</b> Intro and recap</a></li>
<li class="chapter" data-level="3.2" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#creating-choropleth-maps"><i class="fa fa-check"></i><b>3.2</b> Creating choropleth maps</a></li>
<li class="chapter" data-level="3.3" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#producing-small-multiples-to-compare-the-effect-of-different-classification-systems"><i class="fa fa-check"></i><b>3.3</b> Producing small multiples to compare the effect of different classification systems</a><ul>
<li class="chapter" data-level="3.3.1" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#homework-3.1"><i class="fa fa-check"></i><b>3.3.1</b> Homework 3.1</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#using-graduated-symbols"><i class="fa fa-check"></i><b>3.4</b> Using graduated symbols</a></li>
<li class="chapter" data-level="3.5" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#bringing-additional-census-data-in"><i class="fa fa-check"></i><b>3.5</b> Bringing additional census data in</a></li>
<li class="chapter" data-level="3.6" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#computing-and-mapping-crime-rates"><i class="fa fa-check"></i><b>3.6</b> Computing and mapping crime rates</a><ul>
<li class="chapter" data-level="3.6.1" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#homework-2-1"><i class="fa fa-check"></i><b>3.6.1</b> Homework 2</a></li>
<li class="chapter" data-level="3.6.2" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#homework-3"><i class="fa fa-check"></i><b>3.6.2</b> Homework 3</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#more-on-small-multiples-and-point-pattern-maps"><i class="fa fa-check"></i><b>3.7</b> More on small multiples and point pattern maps</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html"><i class="fa fa-check"></i><b>4</b> Performing spatial operations in R</a><ul>
<li class="chapter" data-level="4.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#getting-some-more-data"><i class="fa fa-check"></i><b>4.1</b> Getting some (more) data</a><ul>
<li class="chapter" data-level="4.1.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#reading-data-in-from-the-web"><i class="fa fa-check"></i><b>4.1.1</b> Reading data in from the web</a></li>
<li class="chapter" data-level="4.1.2" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#subsetting-using-pattern-matching"><i class="fa fa-check"></i><b>4.1.2</b> Subsetting using pattern matching</a></li>
<li class="chapter" data-level="4.1.3" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#geocoding-from-an-address"><i class="fa fa-check"></i><b>4.1.3</b> Geocoding from an address</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#making-interactive-maps-with-leaflet"><i class="fa fa-check"></i><b>4.2</b> Making interactive maps with leaflet</a><ul>
<li class="chapter" data-level="4.2.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#making-a-map"><i class="fa fa-check"></i><b>4.2.1</b> Making a map</a></li>
<li class="chapter" data-level="4.2.2" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#adding-some-content"><i class="fa fa-check"></i><b>4.2.2</b> Adding some content:</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#adding-points-manually"><i class="fa fa-check"></i><b>4.3</b> Adding points manually:</a><ul>
<li class="chapter" data-level="4.3.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#adding-data-from-elsewhere"><i class="fa fa-check"></i><b>4.3.1</b> Adding data from elsewhere</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#spatial-operations"><i class="fa fa-check"></i><b>4.4</b> Spatial operations</a><ul>
<li class="chapter" data-level="4.4.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#coordinate-reference-systems-revisited"><i class="fa fa-check"></i><b>4.4.1</b> Coordinate reference systems revisited</a></li>
<li class="chapter" data-level="4.4.2" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#meet-a-new-format-of-shapefile-geojson"><i class="fa fa-check"></i><b>4.4.2</b> Meet a new format of shapefile: geojson</a></li>
<li class="chapter" data-level="4.4.3" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#subset-points-to-those-within-a-polygon"><i class="fa fa-check"></i><b>4.4.3</b> Subset points to those within a polygon</a></li>
<li class="chapter" data-level="4.4.4" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#spatial-operations-two-building-buffers"><i class="fa fa-check"></i><b>4.4.4</b> Spatial operations two: building buffers</a></li>
<li class="chapter" data-level="4.4.5" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#points-in-polygon"><i class="fa fa-check"></i><b>4.4.5</b> Points in Polygon</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#recap"><i class="fa fa-check"></i><b>4.5</b> Recap</a></li>
<li class="chapter" data-level="4.6" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#homework"><i class="fa fa-check"></i><b>4.6</b> Homework</a><ul>
<li class="chapter" data-level="4.6.1" data-path="performing-spatial-operations-in-r.html"><a href="performing-spatial-operations-in-r.html#geocode-the-addresses"><i class="fa fa-check"></i><b>4.6.1</b> <strong>Geocode the addresses:</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html"><i class="fa fa-check"></i><b>5</b> More on thematic maps</a><ul>
<li class="chapter" data-level="5.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#introduction-1"><i class="fa fa-check"></i><b>5.1</b> Introduction</a><ul>
<li class="chapter" data-level="5.1.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#pro-tip-do-i-need-to-install-this-package"><i class="fa fa-check"></i><b>5.1.1</b> Pro-tip: do I need to install this package?</a></li>
<li class="chapter" data-level="5.1.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#data"><i class="fa fa-check"></i><b>5.1.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#mapping-rates-learning-from-disease-mapping"><i class="fa fa-check"></i><b>5.2</b> Mapping rates, learning from disease mapping</a></li>
<li class="chapter" data-level="5.3" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#binning-points"><i class="fa fa-check"></i><b>5.3</b> Binning points</a><ul>
<li class="chapter" data-level="5.3.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#the-binning-process"><i class="fa fa-check"></i><b>5.3.1</b> The Binning Process</a></li>
<li class="chapter" data-level="5.3.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#different-binning-techniques"><i class="fa fa-check"></i><b>5.3.2</b> Different Binning Techniques</a></li>
<li class="chapter" data-level="5.3.3" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#homework-5.1"><i class="fa fa-check"></i><b>5.3.3</b> Homework 5.1</a></li>
<li class="chapter" data-level="5.3.4" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#multivariate-binning"><i class="fa fa-check"></i><b>5.3.4</b> Multivariate binning</a></li>
<li class="chapter" data-level="5.3.5" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#benefits-of-binning"><i class="fa fa-check"></i><b>5.3.5</b> Benefits of Binning</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#a-note-of-caution-maup"><i class="fa fa-check"></i><b>5.4</b> A note of caution: MAUP</a><ul>
<li class="chapter" data-level="5.4.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#what-is-maup"><i class="fa fa-check"></i><b>5.4.1</b> What is MAUP?</a></li>
<li class="chapter" data-level="5.4.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#why-does-maup-matter"><i class="fa fa-check"></i><b>5.4.2</b> Why does MAUP matter?</a></li>
<li class="chapter" data-level="5.4.3" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#what-can-we-do"><i class="fa fa-check"></i><b>5.4.3</b> What can we do?</a></li>
<li class="chapter" data-level="5.4.4" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#homework-5.2"><i class="fa fa-check"></i><b>5.4.4</b> Homework 5.2</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#replacing-polygons-with-grid-or-hex-shapes"><i class="fa fa-check"></i><b>5.5</b> Replacing polygons with grid or hex shapes</a><ul>
<li class="chapter" data-level="5.5.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#homework-5.3"><i class="fa fa-check"></i><b>5.5.1</b> Homework 5.3</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#cartograms"><i class="fa fa-check"></i><b>5.6</b> Cartograms</a></li>
<li class="chapter" data-level="5.7" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#references-and-further-reading"><i class="fa fa-check"></i><b>5.7</b> References and further reading</a><ul>
<li class="chapter" data-level="5.7.1" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#binning"><i class="fa fa-check"></i><b>5.7.1</b> Binning</a></li>
<li class="chapter" data-level="5.7.2" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#maup"><i class="fa fa-check"></i><b>5.7.2</b> MAUP</a></li>
<li class="chapter" data-level="5.7.3" data-path="more-on-thematic-maps.html"><a href="more-on-thematic-maps.html#transforming-polygons"><i class="fa fa-check"></i><b>5.7.3</b> Transforming polygons</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html"><i class="fa fa-check"></i><b>6</b> Studying spatial point patterns</a><ul>
<li class="chapter" data-level="6.1" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#what-well-do-today"><i class="fa fa-check"></i><b>6.1</b> What we’ll do today</a></li>
<li class="chapter" data-level="6.2" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#getting-the-data"><i class="fa fa-check"></i><b>6.2</b> Getting the data</a></li>
<li class="chapter" data-level="6.3" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#getting-the-data-into-spatstat-the-problem-with-duplicates"><i class="fa fa-check"></i><b>6.3</b> Getting the data into spatstat: the problem with duplicates</a></li>
<li class="chapter" data-level="6.4" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#inspecting-our-data-with-spatstat"><i class="fa fa-check"></i><b>6.4</b> Inspecting our data with spatstat</a></li>
<li class="chapter" data-level="6.5" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#density-estimates"><i class="fa fa-check"></i><b>6.5</b> Density estimates</a></li>
<li class="chapter" data-level="6.6" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#adding-some-context"><i class="fa fa-check"></i><b>6.6</b> Adding some context</a><ul>
<li class="chapter" data-level="6.6.1" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#homework-1-1"><i class="fa fa-check"></i><b>6.6.1</b> Homework 1</a></li>
<li class="chapter" data-level="6.6.2" data-path="studying-spatial-point-patterns.html"><a href="studying-spatial-point-patterns.html#homework-2-2"><i class="fa fa-check"></i><b>6.6.2</b> Homework 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html"><i class="fa fa-check"></i><b>7</b> Global and local spatial autocorrelation</a><ul>
<li class="chapter" data-level="7.1" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#get-data"><i class="fa fa-check"></i><b>7.1</b> Get data</a></li>
<li class="chapter" data-level="7.2" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#what-is-a-neighbour"><i class="fa fa-check"></i><b>7.2</b> What is a neighbour?</a><ul>
<li class="chapter" data-level="7.2.1" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#homework-1-2"><i class="fa fa-check"></i><b>7.2.1</b> Homework 1</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#creating-a-list-of-neighbours"><i class="fa fa-check"></i><b>7.3</b> Creating a list of neighbours</a></li>
<li class="chapter" data-level="7.4" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#generating-the-weight-matrix"><i class="fa fa-check"></i><b>7.4</b> Generating the weight matrix</a><ul>
<li class="chapter" data-level="7.4.1" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#homework-2-3"><i class="fa fa-check"></i><b>7.4.1</b> Homework 2</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#compute-morans-i"><i class="fa fa-check"></i><b>7.5</b> Compute Moran’s I</a><ul>
<li class="chapter" data-level="7.5.1" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#homework-3-optional-practice"><i class="fa fa-check"></i><b>7.5.1</b> Homework 3 (Optional Practice)</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#week-7-local-spatial-autocorrelation"><i class="fa fa-check"></i><b>7.6</b> Week 7 : Local spatial autocorrelation</a></li>
<li class="chapter" data-level="7.7" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#prelude-1"><i class="fa fa-check"></i><b>7.7</b> Prelude</a></li>
<li class="chapter" data-level="7.8" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#get-data-and-built-the-weight-matrix"><i class="fa fa-check"></i><b>7.8</b> Get data and built the weight matrix</a></li>
<li class="chapter" data-level="7.9" data-path="global-and-local-spatial-autocorrelation.html"><a href="global-and-local-spatial-autocorrelation.html#generating-and-visualising-the-lisa-measures"><i class="fa fa-check"></i><b>7.9</b> Generating and visualising the LISA measures</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html"><i class="fa fa-check"></i><b>8</b> Regression analysis (a refresher)</a><ul>
<li class="chapter" data-level="8.1" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#introduction-2"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#motivating-regression"><i class="fa fa-check"></i><b>8.2</b> Motivating regression</a></li>
<li class="chapter" data-level="8.3" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#fitting-a-simple-regression-model"><i class="fa fa-check"></i><b>8.3</b> Fitting a simple regression model</a></li>
<li class="chapter" data-level="8.4" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#residuals-revisited-r-squared"><i class="fa fa-check"></i><b>8.4</b> Residuals revisited: R squared</a></li>
<li class="chapter" data-level="8.5" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#inference-with-regression"><i class="fa fa-check"></i><b>8.5</b> Inference with regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#fitting-regression-with-categorical-predictors"><i class="fa fa-check"></i><b>8.6</b> Fitting regression with categorical predictors</a></li>
<li class="chapter" data-level="8.7" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#motivating-multiple-regression"><i class="fa fa-check"></i><b>8.7</b> Motivating multiple regression</a></li>
<li class="chapter" data-level="8.8" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#fitting-and-interpreting-a-multiple-regression-model"><i class="fa fa-check"></i><b>8.8</b> Fitting and interpreting a multiple regression model</a></li>
<li class="chapter" data-level="8.9" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#presenting-your-regression-results."><i class="fa fa-check"></i><b>8.9</b> Presenting your regression results.</a></li>
<li class="chapter" data-level="8.10" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#rescaling-input-variables-to-assist-interpretation"><i class="fa fa-check"></i><b>8.10</b> Rescaling input variables to assist interpretation</a></li>
<li class="chapter" data-level="8.11" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#testing-conditional-hypothesis-interactions"><i class="fa fa-check"></i><b>8.11</b> Testing conditional hypothesis: interactions</a></li>
<li class="chapter" data-level="8.12" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#model-building-and-variable-selection"><i class="fa fa-check"></i><b>8.12</b> Model building and variable selection</a></li>
<li class="chapter" data-level="8.13" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#regression-assumptions"><i class="fa fa-check"></i><b>8.13</b> Regression assumptions</a><ul>
<li class="chapter" data-level="8.13.1" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#homework-4"><i class="fa fa-check"></i><b>8.13.1</b> HOMEWORK</a></li>
</ul></li>
<li class="chapter" data-level="8.14" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#introduction-3"><i class="fa fa-check"></i><b>8.14</b> Introduction</a></li>
<li class="chapter" data-level="8.15" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#looking-at-the-residuals-and-testing-for-spatial-autocorrelation-in-regression"><i class="fa fa-check"></i><b>8.15</b> Looking at the residuals and testing for spatial autocorrelation in regression</a></li>
<li class="chapter" data-level="8.16" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#what-to-do-now"><i class="fa fa-check"></i><b>8.16</b> What to do now?</a></li>
<li class="chapter" data-level="8.17" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#spatial-regimes"><i class="fa fa-check"></i><b>8.17</b> Spatial Regimes</a><ul>
<li class="chapter" data-level="8.17.1" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#homework-1-3"><i class="fa fa-check"></i><b>8.17.1</b> HOMEWORK 1</a></li>
</ul></li>
<li class="chapter" data-level="8.18" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#lagrange-multipliers"><i class="fa fa-check"></i><b>8.18</b> Lagrange multipliers</a><ul>
<li class="chapter" data-level="8.18.1" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#homework-2-4"><i class="fa fa-check"></i><b>8.18.1</b> HOMEWORK 2</a></li>
</ul></li>
<li class="chapter" data-level="8.19" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#fitting-and-interpreting-a-spatially-lagged-model"><i class="fa fa-check"></i><b>8.19</b> Fitting and interpreting a spatially lagged model</a></li>
<li class="chapter" data-level="8.20" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#fitting-an-interpreting-a-spatial-error-model"><i class="fa fa-check"></i><b>8.20</b> Fitting an interpreting a spatial error model</a><ul>
<li class="chapter" data-level="8.20.1" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#homework-3-1"><i class="fa fa-check"></i><b>8.20.1</b> HOMEWORK 3</a></li>
</ul></li>
<li class="chapter" data-level="8.21" data-path="regression-analysis-a-refresher.html"><a href="regression-analysis-a-refresher.html#interpreting-spatial-lag-coefficiences"><i class="fa fa-check"></i><b>8.21</b> Interpreting Spatial Lag Coefficiences</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="time-matters.html"><a href="time-matters.html"><i class="fa fa-check"></i><b>9</b> Time matters</a><ul>
<li class="chapter" data-level="9.1" data-path="time-matters.html"><a href="time-matters.html#crime-and-incident-trend-identification"><i class="fa fa-check"></i><b>9.1</b> Crime and incident trend identification</a><ul>
<li class="chapter" data-level="9.1.1" data-path="time-matters.html"><a href="time-matters.html#lubridate-your-guardian-angel-when-it-comes-to-working-with-temporal-data"><i class="fa fa-check"></i><b>9.1.1</b> Lubridate: your guardian angel when it comes to working with temporal data</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="time-matters.html"><a href="time-matters.html#aggregating-to-simple-intervals"><i class="fa fa-check"></i><b>9.2</b> Aggregating to simple intervals</a><ul>
<li class="chapter" data-level="9.2.1" data-path="time-matters.html"><a href="time-matters.html#aggregating-burglary-to-hour"><i class="fa fa-check"></i><b>9.2.1</b> Aggregating burglary to hour</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="time-matters.html"><a href="time-matters.html#visualising-time-on-a-map"><i class="fa fa-check"></i><b>9.3</b> Visualising time on a map</a></li>
<li class="chapter" data-level="9.4" data-path="time-matters.html"><a href="time-matters.html#time-series"><i class="fa fa-check"></i><b>9.4</b> Time series</a><ul>
<li class="chapter" data-level="9.4.1" data-path="time-matters.html"><a href="time-matters.html#moving-averages"><i class="fa fa-check"></i><b>9.4.1</b> Moving averages</a></li>
<li class="chapter" data-level="9.4.2" data-path="time-matters.html"><a href="time-matters.html#moving-average-in-r"><i class="fa fa-check"></i><b>9.4.2</b> Moving average in R</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Crime Mapping in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-analysis-a-refresher" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> Regression analysis (a refresher)</h1>
<div id="introduction-2" class="section level2">
<h2><span class="header-section-number">8.1</span> Introduction</h2>
<p>In this session we are going to cover regression analysis or, rather, we are beginning to talk about regression modelling. This form of analysis has been one the main technique of data analysis in the social sciences for many years and it belongs to a family of techniques called generalised linear models. Regression is a flexible model that allows you to “explain” or “predict” a given outcome (Y), variously called your outcome, response or dependent variable, as a function of a number of what is variously called inputs, features or independent, explanatory, or predictive variables (X1, X2, X3, etc.). Following Gelman and Hill (2007), I will try to stick for the most part to the terms outputs and inputs.</p>
<p>Today we will cover something that is called linear regression or ordinary least squares regression (OLS), which is a technique that you use when you are interested in explaining variation in an interval level variable. First we will see how you can use regression analysis when you only have one input and then we will move to situations when we have several explanatory variables or inputs. For those of you already familiar with regression analysis this session can be a it of a refresher, for those that aren’t a bit of an introduction. Today we will cover regression models more generally and in the next lab we will discuss adaptations to the regression model that are necessary when you have spatial autocorrelation.</p>
<p>We will use a dataset that includes information about homicide in the US, as well as information in a number of sociodemographic variables that are often thought of as associated with the geographical distribution of homicides.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">##R in Windows have some problems with https addresses, that&#39;s why we need to do this first:</span>
urlfile&lt;-<span class="st">&#39;https://s3.amazonaws.com/geoda/data/ncovr.zip&#39;</span>
<span class="kw">download.file</span>(urlfile, <span class="st">&#39;ncovr.zip&#39;</span>)
<span class="co">#Let&#39;s unzip and create a new directory (ncovr) in our working directory to place the files</span>
<span class="kw">unzip</span>(<span class="st">&#39;ncovr.zip&#39;</span>, <span class="dt">exdir =</span> <span class="st">&#39;ncovr&#39;</span>)</code></pre>
<p>There is quite a few files and folders here. We don’t need all of it. If you look inside the newly created folder you will find two subdirecoties MACOSX and ncovr. Look in the latter. You will see a pdf file called codebook.pdf. Read this file. It provides information on the variables and data that is included here. We are now going to read the main data file into R. This is the NAT.csv file.</p>
<pre class="sourceCode r"><code class="sourceCode r">ncovr &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;ncovr/ncovr/NAT.csv&#39;</span>)</code></pre>
<p>The dataset contains information about 3085 counties in the US and if you view it you will see it has information about several decades, the 60s, 70s, 80s, and 90s. The number at the end of the variable names denotes the relevant decade and you will see that for each decade we have the same variables.</p>
<p>The purpose of this and next session is to help you choose a model to represent the relationship between homicide and various predictors. You can think of a model as a map. A map aims to represent a given reality, but as you may have already discovered there are many ways of presenting the same information through a map. As an analyst you decide what the most appropriate representation for your needs is. Each representation you choose will involve an element of distortion. Maps (and models) are not exact representations of the real word, they are simply good approximations that may serve well a particular functional need. Look at the map of the metro in London that we reproduce below:</p>
<div class="figure">
<img src="img/tube-map.gif" alt="Figure 1" />
<p class="caption"><strong>Figure 1</strong></p>
</div>
<p>London doesn’t quite look like this. Yet, if you want to use the Metro system, this map will be extremely helpful to you. It serves a need in a good way. Same happens with models. They may not be terribly good reflections of the world, but may give us approximations that allows us to develop useful insights.</p>
<p>Choosing a good model is like choosing a good way for displaying quantitative information in a map. Decisions, decisions, decisions. There are many parameters and options one can choose from. This can be overwhelming, particularly as you are learning how to model and map phenomena. How to make good decisions is something that you learn on earnest by practice, practice, practice. Nobody expects you to get the maps you are doing as you are learning, and the models you are developing as you are learning spot on. So please do not stress out about this. All we can do here is to learn some basic principles and start getting some practice, which you will be able to further develop in aprofessional context or in further training.</p>
<p>The first step in any analysis is to develop some familiarity with the data you are going to be working with. We have been here before. Read the codebook. Run summary statistics for your quantitative variables, frequency distributions for your categorical variables, and visualise your variables. This will help you to detect any anomalies and give you a sense for what you have. If, for example, you run a histogram for the homicide rate for 1990 (HR90), you will get a sense of the distribution form –which of course is skewed.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">qplot</span>(<span class="dt">x =</span> HR90, <span class="dt">data =</span> ncovr)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Once one has gone through the process of exploring the data in this way for all the variables you want to work, you can start exploring bivariate associations with your dependent, response or outcome variable. So, as an illustration, you could explore the association with resource deprivation (RD90), a measure of the level of concentrated disadvantge or social exclusion in an area, via a scatterplot:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(ncovr, <span class="kw">aes</span>(<span class="dt">x =</span> RD90, <span class="dt">y =</span> HR90)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha=</span>.<span class="dv">2</span>) </code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>What do you think when looking at this scatterplot? Is there a relationship between the variables? Does it look as if individuals that have a high score on the X axis also have a high score on the Y axis? Or viceversa?</p>
</div>
<div id="motivating-regression" class="section level2">
<h2><span class="header-section-number">8.2</span> Motivating regression</h2>
<p>Now, imagine that we play a game. Imagine I have all the respondents waiting in a room, and I randomly call one of them to the stage. You’re sitting in the audience, and you have to guess the level of fear (’tcviolent’) for that respondent. Imagine that I pay £150 to the student that gets the closest to the right value. What would you guess if you only have one guess and you knew (as we do) how fear of violent crime is distributed?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(ncovr, <span class="kw">aes</span>(<span class="dt">x =</span> HR90)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_density</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">4.377</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>, <span class="dt">color=</span><span class="st">&quot;red&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">6.183</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>, <span class="dt">color=</span><span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Density estimate, mean and median of homicide rate 1990&quot;</span>)</code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(ncovr<span class="op">$</span>HR90)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   1.334   4.377   6.183   8.938  71.378</code></pre>
<p>If I only had one shot, you could go for the median, in red, (given the skew) but the mean, in blue, perhaps would be your second best. Most of the areas here have values clustered around those values, which is another way of saying they are bound to be not too far from them.</p>
<p>Imagine, however, that now when someone is called to the stage, you are told the level of resource deprivation in the county - so the value of the <code>RD90</code> variable for the individual that has been selected (for example 4). Imagine as well that you have the scatterplot that we produced earlier in front of you. Would you still go for the value of “4.377” as your best guess for the value of the selected county?</p>
<p>I certainly would not go with the overall mean or median as my prediction anymore. If somebody said to me, the value ‘RD90’ for the selected respondent is 4, I would be more inclined to guess the mean value for the level of homicide with that level of resource deprivation (the conditional mean), rather than the overall mean across all the counties. Wouldn’t you?</p>
<p>If we plot the conditional means we can see that the mean of homicide rate for counties that report a value of 4 in <code>RD90</code> is around 22. So you may be better off guessing that.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(grid)
<span class="kw">ggplot</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data=</span>ncovr, <span class="kw">aes</span>(<span class="dt">x =</span> RD90, <span class="dt">y =</span> HR90), <span class="dt">alpha=</span>.<span class="dv">2</span>) <span class="op">+</span>
<span class="kw">geom_line</span>(<span class="dt">data=</span>ncovr, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">round</span>(RD90<span class="op">/</span><span class="fl">0.12</span>)<span class="op">*</span><span class="fl">0.12</span>, <span class="dt">y =</span> HR90), 
          <span class="dt">stat=</span><span class="st">&#39;summary&#39;</span>,
          <span class="dt">fun.y=</span>mean,
          <span class="dt">color=</span><span class="st">&quot;red&quot;</span>,
          <span class="dt">size=</span><span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;segment&quot;</span>, <span class="dt">x=</span><span class="dv">3</span>, <span class="dt">xend =</span> <span class="dv">4</span>, <span class="dt">y =</span> <span class="dv">25</span>, <span class="dt">yend=</span> <span class="dv">22</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">arrow =</span> <span class="kw">arrow</span>()) <span class="op">+</span>
<span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="dv">3</span>, <span class="dt">y =</span> <span class="dv">29</span>, <span class="dt">label =</span> <span class="st">&quot;Pick this one!&quot;</span>, <span class="dt">size =</span><span class="dv">7</span>, <span class="dt">colour =</span> <span class="st">&quot;blue&quot;</span>)</code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Linear regression tackles this problem using a slightly different approach. Rather than focusing on the conditional mean (smoothed or not), it draws a straight line that tries to capture the trend in the data. If we focus in the region of the scatterplot that are less sparse we see that this is an upward trend, suggesting that as resource deprivation increases so does the homicide rate.</p>
<p>Simple linear regression draws a single straight line of predicted values as the model for the data. This line would be a <strong>model</strong>, a <em>simplification</em> of the real world like any other model (e.g., a toy pistol, an architectural drawing, a subway map), that assumes that there is approximately a linear relationship between X and Y. Let’s draw the regression line:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> ncovr, <span class="kw">aes</span>(<span class="dt">x =</span> RD90, <span class="dt">y =</span> HR90)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">.2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="co">#This ask for a geom with the regression line, method=lm asks for the linear regression line, se=FALSE ask for just the line to be printed, the other arguments specify the color and thickness of the line</span></code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>What that line is doing is giving you guesses (predictions) for the values of homicide based in the information that we have about the level of resource deprivation. It gives you one possible guess for the value of homicide for every possible value of resource deprivation and links them all together in a straight line.</p>
<p>Another way of thinking about this line is as the best possible summary of the cloud of points that are represented in the scatterplot (if we can assume that a straight line would do a good job doing this). If I were to tell you to draw a straight line that best represents this pattern of points the regression line would be the one that best does it (if certain assumptions are met).</p>
<p>The linear model then is a model that takes the form of the equation of a straight line through the data. The line does not go through all the points. In fact, you can see is a slightly less accurate representation than the (smoothed) conditional means:</p>
<p><img src="08-week8_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Our regression line underpredicts at low levels of resource deprivation and does not seem to capture well the variability at higher levels of resource deprivation. But imperfect as a model as it might be it simplifies well the overall growing trend for homicide as resource deprivation increases.</p>
<p>As De Veaux et al (2012: 179) highlight: “like all models of the real world, the line will be wrong, wrong in the sense that it can’t match reality exactly. But it can help us understand how the variables are associated”. A map is never a perfect representation of the world, the same happens with statistical models. Yet, as with maps, models can be helpful.</p>
</div>
<div id="fitting-a-simple-regression-model" class="section level2">
<h2><span class="header-section-number">8.3</span> Fitting a simple regression model</h2>
<p>In order to draw a regression line we need to know two things:
(1) We need to know where the line begins, what is the value of Y (our dependent variable) when X (our independent variable) is 0, so that we have a point from which to start drawing the line. The technical name for this point is the <strong>intercept</strong>.
(2) And we need to know what is the <strong>slope</strong> of that line, that is, how inclined the line is, the angle of the line.</p>
<p>If you recall from elementary algebra (and you may not), the equation for any straight line is:
y = mx + b
In statistics we use a slightly different notation, although the equation remains the same:
y = b0 + b1x</p>
<p>We need the origin of the line (b0) and the slope of the line (b1). How does R get the intercept and the slope for the green line? How does R know where to draw this line? We need to estimate these <strong>parameters</strong> (or <strong>coefficients</strong>) from the data. How? We don’t have the time to get into these more mathematical details now. You should study the <a href="http://link.springer.com/chapter/10.1007/978-1-4614-7138-7_3">required reading</a> to understand this (<em>required means it is required, it is not optional</em>)<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. For now, suffice to say that for linear regression modes like the one we cover here, when drawing the line, R tries to minimise the distance from every point in the scatterplot to the regression line using a method called <strong>least squares estimation</strong>.</p>
<p>In order to fit the model we use the <code>lm()</code> function using the formula specification <code>(Y ~ X)</code>. Typically you want to store your regression model in a “variable”, let’s call it <code>fit_1</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r">fit_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR90 <span class="op">~</span><span class="st"> </span>RD90, <span class="dt">data =</span> ncovr)</code></pre>
<p>You will see in your R Studio global environment space that there is a new object called <code>fit_1</code> with 12 elements on it. We can get a sense for what this object is and includes using the functions we introduced in previous weeks:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(fit_<span class="dv">1</span>)</code></pre>
<pre><code>## [1] &quot;lm&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attributes</span>(fit_<span class="dv">1</span>)</code></pre>
<pre><code>## $names
##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;        
## 
## $class
## [1] &quot;lm&quot;</code></pre>
<p>R is telling us that this is an object of class <code>lm</code> and that it includes a number of attributes. One of the beauties of R is that you are producing all the results from running the model, putting them in an object, and then giving you the opportunity for using them later on. If you want to simply see the basic results from running the model you can use the <code>summary()</code> function.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(fit_<span class="dv">1</span>)</code></pre>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ RD90, data = ncovr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.796  -3.415  -0.719   2.540  67.103 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  6.18286    0.09844   62.81   &lt;2e-16 ***
## RD90         3.77121    0.09846   38.30   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.468 on 3083 degrees of freedom
## Multiple R-squared:  0.3224, Adjusted R-squared:  0.3222 
## F-statistic:  1467 on 1 and 3083 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Or if you prefer more parsimonious presentation you could use the <code>display()</code> function of the <code>arm</code> package:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(arm)</code></pre>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: lme4</code></pre>
<pre><code>## 
## arm (Version 1.10-1, built: 2018-4-12)</code></pre>
<pre><code>## Working directory is /Users/reka/Dropbox (The University of Manchester)/crimemapping_textbook_bookdown</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">display</span>(fit_<span class="dv">1</span>)</code></pre>
<pre><code>## lm(formula = HR90 ~ RD90, data = ncovr)
##             coef.est coef.se
## (Intercept) 6.18     0.10   
## RD90        3.77     0.10   
## ---
## n = 3085, k = 2
## residual sd = 5.47, R-Squared = 0.32</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(package<span class="op">:</span>arm) <span class="co">#This will unload the package</span></code></pre>
<p>For now I just want you to focus on the numbers in the “Estimate” (or coef.est) column. The value of 6.18 estimated for the <strong>intercept</strong> is the “predicted” value for Y when X equals zero. This is the predicted value of the fear of crime score <em>when resource deprivation has a value of zero</em>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(ncovr<span class="op">$</span>RD90)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -2.4103 -0.6667 -0.2016  0.0000  0.4393  5.5831</code></pre>
<p>RD90 is a variable that has been centered in ). It has been created by the researchers in such a way that is has a mean value of 0. Since we only have one explanatory variable in the model this corresponds to the mean of the homicide rate, 6.18. In many other contexts the intercept has less of a meaning.</p>
<p>We then need the b1 regression coefficient for for our independent variable, the value that will shape the <strong>slope</strong> in this scenario. This value is 3.77. This estimated regression coefficient for our independent variable has a convenient interpretation. When the value is positive, it tells us that <em>for every one unit increase in X there is a b1 increase on Y</em>. If the coefficient is negative then it represents a decrease on Y. Here, we can read it as “for every one unit increase in the resource deprivation score, there is a 3.77 unit increase in the homicide rate.”</p>
<p>Knowing these two parameters not only allows us to draw the line, we can also solve for any given value of X. Let’s go back to our guess-the-homicide-rate game. Imagine I tell you the level of resource deprivation is 1. What would be your best bet now? We can simply go back to our regression line equation and insert the estimated parameters:</p>
<p>y = b0 + b1x<br />
y = 6.18 + 3.77 (1)<br />
y = 9.95</p>
<p>Or if you don’t want to do the calculation yourself, you can use the <code>predict</code> function (differences are due to rounding error):</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(fit_<span class="dv">1</span>, <span class="kw">data.frame</span>(<span class="dt">RD90 =</span> <span class="kw">c</span>(<span class="dv">1</span>))) <span class="co">#First you name your stored model and then you identify the new data (which has to be in a data frame format and with a variable name matching the one in the original data set)</span></code></pre>
<pre><code>##        1 
## 9.954065</code></pre>
<p>This is the expected value of Y, homicide rate, when X, resource deprivation is 1 <strong>according to our model</strong> (according to our simplification of the real world, our simplification of the whole cloud of points into just one straight line). Look back at the scatterplot we produced earlier with the red line. Does it look as if the green line when X is 1 corresponds to a value of Y of 9.95?</p>
</div>
<div id="residuals-revisited-r-squared" class="section level2">
<h2><span class="header-section-number">8.4</span> Residuals revisited: R squared</h2>
<p>In the output above we saw there was something called the residuals. The residuals are the differences between the observed values of Y for each case minus the predicted or expected value of Y, in other words the distances between each point in the dataset and the regression line (see the visual example below).</p>
<div class="figure">
<img src="img/mYzliZjY4ZDc0NjI3YWQ3YWVlM2MzZmUzN2MwOWY.jpg" alt="drawing" />
<p class="caption">drawing</p>
</div>
<p>You see that we have our line, which is our predicted values, and then we have the black dots which are our actually observed values. The distance between them is essentially the amount by which we were wrong, and all these distances between observed and predicted values are our residuals. Least square estimation essentially aims to reduce the squared average of all these distances: that’s how it draws the line.</p>
<p>Why do we have residuals? Well, think about it. The fact that the line is not a perfect representation of the cloud of points makes sense, doesn’t it? You cannot predict perfectly what the value of Y is for every observation just by looking ONLY at their level of resource deprivation! This line only uses information regarding resource deprivation. This means that there’s bound to be some difference between our predicted level of homicide given our knowledge of deprivation (the regression line) and the actual level of homicide (the actual location of the points in the scatterplot). There are other things that matter not being taken into account by our model to predict the values of Y. There are other things that surely matter in terms of understanding homicide. And then, of course, we have measurement error and other forms of noise.</p>
<p>We can re-write our equation like this if we want to represent each value of Y (rather than the predicted value of Y) then:
y = b0 + b1x + residuals</p>
<p>The residuals capture how much variation is unexplained, how much we still have to learn if we want to understand variation in Y. A good model tries to maximise explained variation and reduce the magnitude of the residuals.</p>
<p>We can use information from the residuals to produce a measure of effect size, of how good our model is in predicting variation in our dependent variables. Remember our game where we try to guess homicide (Y)? If we did not have any information about X our best bet for Y would be the mean of Y. The regression line aims to improve that prediction. By knowing the values of X we can build a regression line that aims to get us closer to the actual values of Y (look at the Figure below).</p>
<div class="figure">
<img src="img/weight2.png" alt="r squared" />
<p class="caption">r squared</p>
</div>
<p>The distance between the mean (our best guess without any other piece of information) and the observed value of Y is what we call the <strong>total variation</strong>. The residual is the difference between our predicted value of Y and the observed value of Y. This is what we cannot explain (i.e, variation in Y that is <em>unexplained</em>). The difference between the mean value of Y and the expected value of Y (the value given by our regression line) is how much better we are doing with our prediction by using information about X (i.e., in our previous example it would be variation in Y that can be <em>explained</em> by knowing about resource deprivation). How much closer the regression line gets us to the observed values. We can then contrast these two different sources of variation (explained and unexplained) to produce a single measure of how good our model is. The formula is as follows:</p>
<div class="figure">
<img src="img/r_squared_constant.gif" alt="formula" />
<p class="caption">formula</p>
</div>
<p>All this formula is doing is taking a ratio of the explained variation (the squared differences between the regression line and the mean of Y for each observation) by the total variation (the squared differences of the observed values of Y for each observation from the mean of Y). This gives us a measure of the <strong>percentage of variation in Y that is “explained” by X</strong>. If this sounds familiar is because it is a measure similar to eta squared in ANOVA.</p>
<p>As then we can take this value as a measure of the strength of our model. If you look at the R output you will see that the R2 for our model was .32 (look at the multiple R square value in the output) . We can say that our model explains 32% of the variance in the fear of homicide. when doing regression, you will often find that regression models with aggregate data such as county level data will give you better results than when dealing with individuals. It is much harder understanding individual variation than county level variation.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#As an aside, and to continue emphasising your appreciation of the object oriented nature of R, when we run the summary() function we are simply generating a list object of the class summary.lm.</span>
<span class="kw">attributes</span>(<span class="kw">summary</span>(fit_<span class="dv">1</span>))</code></pre>
<pre><code>## $names
##  [1] &quot;call&quot;          &quot;terms&quot;         &quot;residuals&quot;     &quot;coefficients&quot; 
##  [5] &quot;aliased&quot;       &quot;sigma&quot;         &quot;df&quot;            &quot;r.squared&quot;    
##  [9] &quot;adj.r.squared&quot; &quot;fstatistic&quot;    &quot;cov.unscaled&quot; 
## 
## $class
## [1] &quot;summary.lm&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#This means that we can access its elements if so we wish. So, for example, to obtain just the R Squared, we could ask for:</span>
<span class="kw">summary</span>(fit_<span class="dv">1</span>)<span class="op">$</span>r.squared</code></pre>
<pre><code>## [1] 0.3224335</code></pre>
<p>Knowing how to interpret this is important. R^2 ranges from 0 to 1. The greater it is the more powerful our model is, the more explaining we are doing, the better we are able to account for variation in our outcome Y with our input. In other words, the stronger the relationship is between Y and X. As with all the other measures of effect size interpretation is a matter of judgement. You are advised to see what other researchers report in relation to the particular outcome that you may be exploring.</p>
<p>Weisburd and Britt (2009: 437) suggest that in criminal justice you rarely see values for R^2 greater than .40. Thus, if your R^2 is larger than .40, you can assume you have a powerful model. When, on the other hand, R^2 is lower than .15 or .2 the model is likely to be viewed as relatively weak. Our observed r squared here is rather poor. There is considerably room for improvement if we want to develop a better model to explain fear of violent crime<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>. In any case, many people would argue that R^2 is a bit overrated. You need to be aware of what it measures and the context in which you are using it. Read <a href="http://blog.minitab.com/blog/adventures-in-statistics/how-high-should-r-squared-be-in-regression-analysis">here</a> for some additional detail.</p>
</div>
<div id="inference-with-regression" class="section level2">
<h2><span class="header-section-number">8.5</span> Inference with regression</h2>
<p>In real applications, we have access to a set of observations from which we can compute the least squares line, but the population regression line is unobserved. So our regression line is one of many that could be estimated. A different sample would produce a different regression line. The same sort of ideas that we introduced when discussing the estimation of sample means or proportions also apply here. if we estimate b0 and b1 from a particular sample, then our estimates won’t be exactly equal to b0 and b1 in the population. But if we could average the estimates obtained over a very large number of data sets, the average of these estimates would equal the coefficients of the regression line in the population.</p>
<p>We can compute standard errors for the regression coefficients to quantify our uncertainty about these estimates. These standard errors can in turn be used to produce confidence intervals. This would require us to assume that the residuals are normally distributed. As seen in the image, and for a simple regression model, you are assuming that the values of Y are approximately normally distributed for each level of X:</p>
<div class="figure">
<img src="img/Doe4.3.png" alt="normalityresiduals" />
<p class="caption">normalityresiduals</p>
</div>
<p>In those circumstances we can trust the confidence intervals that we can draw around the regression line as in the image below:</p>
<div class="figure">
<img src="img/SimpleLinearRegressionJags-ICON-FREQ-EST.png" title="Image taken from John Krushcke blog http://doingbayesiandataanalysis.blogspot.co.uk/" alt="estimated" />
<p class="caption">estimated</p>
</div>
<p>The dark-blue line marks the best fit. The two dark-pink lines mark the limits of the confidence interval. The light-pink lines show the sampling distributions around each of the confidence-interval limits (the many regression lines that would result from repeated sampling); notice that the best-fit line falls at the extreme of each sampling distribution.</p>
<p>You can also then perform standard hypothesis test on the coefficients. As we saw before when summarising the model, R will compute the standard errors and a t test for each of the coefficients.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(fit_<span class="dv">1</span>)<span class="op">$</span>coefficients</code></pre>
<pre><code>##             Estimate Std. Error  t value      Pr(&gt;|t|)
## (Intercept) 6.182860 0.09844166 62.80735  0.000000e+00
## RD90        3.771206 0.09845761 38.30283 6.535551e-263</code></pre>
<p>In our example, we can see that the coefficient for our predictor here is statistically significant<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</p>
<p>We can also obtain confidence intervals for the estimated coefficients using the <code>confint()</code> function:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(fit_<span class="dv">1</span>)</code></pre>
<pre><code>##                2.5 %   97.5 %
## (Intercept) 5.989842 6.375877
## RD90        3.578156 3.964255</code></pre>
</div>
<div id="fitting-regression-with-categorical-predictors" class="section level2">
<h2><span class="header-section-number">8.6</span> Fitting regression with categorical predictors</h2>
<p>So far we have explained regression using a numeric input. It turns out we can also use regression with categorical explanatory variables. It is quite straightforward to run it.</p>
<p>There is only one categorical explanatory variable in this dataset, a binary indicator that indicates whether the county is in a Southern State or not. We can also explore this relationship using regression and a regression line. This is how you would express the model:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#We use the as.factor function to tell R that SOUTH is a categorical variable</span>
fit_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR90 <span class="op">~</span><span class="st"> </span><span class="kw">as.factor</span>(SOUTH), <span class="dt">data=</span>ncovr)</code></pre>
<p>Notice that there is nothing different in how we ask for the model. And see below the regression line:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data=</span>ncovr, <span class="kw">aes</span>(<span class="dt">x=</span><span class="kw">as.factor</span>(SOUTH), <span class="dt">y=</span>HR90)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha=</span>.<span class="dv">2</span>, <span class="dt">position=</span><span class="st">&quot;jitter&quot;</span>, <span class="dt">color=</span><span class="st">&quot;orange&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> fit_<span class="dv">2</span><span class="op">$</span>coefficients[<span class="dv">1</span>],
    <span class="dt">slope =</span> fit_<span class="dv">2</span><span class="op">$</span>coefficients[<span class="dv">2</span>], <span class="dt">color=</span><span class="st">&quot;red&quot;</span>, <span class="dt">size=</span><span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Let’s have a look at the results:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(fit_<span class="dv">2</span>)</code></pre>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ as.factor(SOUTH), data = ncovr)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.549 -3.342 -1.172  1.931 68.036 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         3.3416     0.1437   23.25   &lt;2e-16 ***
## as.factor(SOUTH)1   6.2077     0.2124   29.22   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.878 on 3083 degrees of freedom
## Multiple R-squared:  0.2169, Adjusted R-squared:  0.2167 
## F-statistic:   854 on 1 and 3083 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As you will see the output does not look too different. But notice that in the print out you see how the row with the coefficient and other values for our input variable <code>SOUTH</code> we see that R is printing <code>1</code>. What does this mean?</p>
<p>It turns out that a linear regression model with just one dichotomous categorical predictor is just the equivalent of a t test. When you only have one predictor the value of the intercept is the mean value of the <strong>reference category</strong> and the coefficient for the slope tells you how much higher (if it is positive) or how much lower (if it is negative) is the mean value for the other category in your factor.</p>
<p>The reference category is the one for which R does not print the <em>level</em> next to the name of the variable for which it gives you the regression coefficient. Here we see that the named level is “1”. That’s telling you that the reference category here is “0”. If you look at the codebook you will see that 1 means the county is in a Southern state. Therefore the Y intercept in this case is the mean value of fear of violent crime for the northern counties, whereas the coefficient for the slope is telling you how much higher (since it is a positive value) the mean value is for the southern counties. Don’t believe me?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(ncovr<span class="op">$</span>HR90[ncovr<span class="op">$</span>SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">0</span>], <span class="dt">na.rm=</span><span class="ot">TRUE</span>)</code></pre>
<pre><code>## [1] 3.341614</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(ncovr<span class="op">$</span>HR90[ncovr<span class="op">$</span>SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">1</span>], <span class="dt">na.rm=</span><span class="ot">TRUE</span>) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(ncovr<span class="op">$</span>HR90[ncovr<span class="op">$</span>SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">0</span>], <span class="dt">na.rm=</span><span class="ot">TRUE</span>)</code></pre>
<pre><code>## [1] 6.207679</code></pre>
<p>So, to reiterate, for a binary predictor, the coefficient is nothing else than the difference between the mean of the two levels in your factor variable, between the averages in your two groups.</p>
<p>With categorical variables encoded as <strong>factors</strong> you always have a situation like this: a reference category and then as many additional coefficients as there are additional levels in your categorical variable. Each of these additional categories is included into the model as <strong>“dummy” variables</strong>. Here our categorical variable has two levels, thus we have only one dummy variable. There will always be one fewer dummy variable than the number of levels. The level with no dummy variable, northern counties in this example, is known as the <strong>reference category</strong> or the <strong>baseline</strong>.</p>
<p>It turns out then that the regression table is printing out for us a t test of statistical significance for every input in the model. If we look at the table above this t value is 29.22 and the p value associated with it is near 0. This is indeed considerably lower than the conventional significance level of 0.05. So we could conclude that the probability of obtaining this value if the null hypothesis is true is very low. The r squared is not too bad either, although lower than we saw when using resource deprivation.</p>
</div>
<div id="motivating-multiple-regression" class="section level2">
<h2><span class="header-section-number">8.7</span> Motivating multiple regression</h2>
<p>So we have seen that we can fit models with just one predictor. We can build better models by expanding the number of predictors (although keep in mind you should also aim to build models as parsimonious as possible).</p>
<p>Another reason why it is important to think about additional variables in your model is to control for spurious correlations (although here you may also want to use your common sense when selecting your variables!). You must have heard before that correlation does not equal causation. Just because two things are associated we cannot assume that one is the cause for the other. Typically we see how the pilots switch the secure the belt button when there is turbulence. These two things are associated, they tend to come together. But the pilots are not causing the turbulences by pressing a switch! The world is full of <strong>spurious correlations</strong>, associations between two variables that should not be taking too seriously. You can explore a few <a href="http://tylervigen.com/">here</a>. It’s funny.</p>
<p>Looking only at covariation between pair of variables can be misleading. It may lead you to conclude that a relationship is more important than it really is. This is no trivial matter, but one of the most important ones we confront in research and policy<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>.</p>
<p>It’s not an exaggeration to say that most quantitative explanatory research is about trying to control for the presence of <strong>confounders</strong>, variables that may explain explain away observed associations. Think about any criminology question: Does marriage reduces crime? Or is it that people that get married are different from those that don’t (and are those pre-existing differences that are associated with less crime)? Do gangs lead to more crime? Or is it that young people that join gangs are more likely to be offenders to start with? Are the police being racist when they stop and search more members of ethnic minorities? Or is it that there are other factors (i.e., offending, area of residence, time spent in the street) that, once controlled, would mean there is no ethnic dis-proportionality in stop and searches? Does a particular program reduces crime? Or is the observed change due to something else?</p>
<p>These things also matter for policy. Wilson and Kelling, for example, argued that signs of incivility (or antisocial behaviour) in a community lead to more serious forms of crime later on as people withdraw to the safety of their homes when they see those signs of incivilities and this leads to a reduction in informal mechanisms of social control. All the policies to tackle antisocial behaviour in this country are very much informed by this model and were heavily influenced by broken windows theory.</p>
<p>But is the model right? Sampson and Raudenbush argue it is not entirely correct. They argue, and tried to show, that there are other confounding (poverty, collective efficacy) factors that explain the association of signs of incivility and more serious crime. In other words, the reason why you see antisocial behaviour in the same communities that you see crime is because other structural factors explain both of those outcomes. They also argue that perceptions of antisocial behaviour are not just produced by observed antisocial behaviour but also by stereotypes about social class and race. If you believe them, then the policy implications are that only tackling antisocial behaviour won’t help you to reduce crime (as Wilson and Kelling have argued) . So as you can see this stuff matters for policy not just for theory.</p>
<p>Multiple regression is one way of checking the relevance of competing explanations. You could set up a model where you try to predict crime levels with an indicator of broken windows and an indicator of structural disadvantage. If after controlling for structural disadvantage you see that the regression coefficient for broken windows is still significant you may be into something, particularly if the estimated effect is still large. If, on the other hand, the t test for the regression coefficient of your broken windows variable is no longer significant, then you may be tempted to think that perhaps Sampson and Raudenbush were into something.</p>
</div>
<div id="fitting-and-interpreting-a-multiple-regression-model" class="section level2">
<h2><span class="header-section-number">8.8</span> Fitting and interpreting a multiple regression model</h2>
<p>It could not be any easier to fit a multiple regression model. You simply modify the formula in the <code>lm()</code> function by adding terms for the additional inputs.</p>
<pre class="sourceCode r"><code class="sourceCode r">ncovr<span class="op">$</span>SOUTH_f &lt;-<span class="st"> </span><span class="kw">as.factor</span>(ncovr<span class="op">$</span>SOUTH)
fit_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR90 <span class="op">~</span><span class="st"> </span>RD90 <span class="op">+</span><span class="st"> </span>SOUTH_f, <span class="dt">data=</span>ncovr)
<span class="kw">summary</span>(fit_<span class="dv">3</span>)</code></pre>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ RD90 + SOUTH_f, data = ncovr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -16.480  -2.996  -0.576   2.216  68.151 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   4.7270     0.1394   33.90   &lt;2e-16 ***
## RD90          2.9649     0.1108   26.77   &lt;2e-16 ***
## SOUTH_f1      3.1809     0.2223   14.31   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.295 on 3082 degrees of freedom
## Multiple R-squared:  0.3647, Adjusted R-squared:  0.3642 
## F-statistic: 884.4 on 2 and 3082 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>With more than one input, you need to ask yourself whether all of the regression coefficients are zero. This hypothesis is tested with a F test. Again we are assuming the residuals are normally distributed, though with large samples the F statistics approximates the F distribution.</p>
<p>You see the F test printed at the bottom of the summary output and the associated p value, which in this case is way below the conventional .05 that we use to declare statistical significance and reject the null hypothesis. At least one of our inputs must be related to our response variable.</p>
<p>Notice that the table printed also reports a t test for each of the predictors. These are testing whether each of these predictors is associated with the response variable when adjusting for the other variables in the model. They report the “partial effect of adding that variable to the model” (James et al. 2014: 77). In this case we can see that both variables seem to be significantly associated with the response variable.</p>
<p>If we look at the r squared we can now see that it is higher than before. r squared will always increase as a consequence of adding new variables, even if the new variables added are weakly related to the response variable.</p>
<p>We see that the coefficients for the predictors change somehow, it goes down a bit for <code>RD90</code> and it halvesfor <code>SOUTH</code>. <strong>But their interpretation now changes</strong>. A common interpretation is that now the regression for each variable tells you about changes in Y related to that variable <strong>when the other variables in the model are held constant</strong>. So, for example, you could say the coefficient for <code>RD90</code> represents the increase in hommicide for every one-unit increase in the measure of resource deprivation <em>when holding all other variables in the model constant</em> (in this case that refers to holding constant <code>SOUTH</code>). But this terminology can be a bit misleading.</p>
<p>Other interpretations are also possible and are more generalizable. Gelman and Hill (2007: p. 34) emphasise what they call the <em>predictive interpretation</em> that considers how “the outcome variable differs, on average, when comparing two groups of units that differ by 1 in the relevant predictor while being identical in all the other predictors”. So <a href="http://andrewgelman.com/2013/01/05/understanding-regression-models-and-regression-coefficients/">if you’re regressing y on u and v, the coefficient of u is the average difference in y per difference in u, comparing pairs of items that differ in u but are identical in v</a>.</p>
<p>So, for example, in this case we could say that comparing counties that have the same level of resource deprivation but that differed in whether they are South or North, the model predicts a expected difference of 3.18 in their homicide rate. And that respondents that do not vary in whether they are South or North, but that differ by one point in the level of resource deprivation, we would expect to see a difference of 2.96 in their homicide rate. So we are interpreting the regression slopes <strong>as comparisons of cases that differ in one predictor while being at the same levels of the other predictors</strong>.</p>
<p>As you can see, interpreting regression coefficients can be kind of tricky<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>. The relationship between the response y and any one explanatory variable can change greatly depending on what other explanatory variables are present in the model.</p>
<p>For example, if you contrast this model with the one we run with only <code>SOUTH</code> as a predictor you will notice the intercept has changed. You cannot longer read the intercept as the mean value of homicide rate for Northern counties. <em>Adding predictors to the model changes their meaning</em>. Now the intercept index the value of homicide for southern counties that score 0 in <code>RD90</code>. In this case you have cases that meet this condition (equal zero in all your predictors), but often you may not have any case that does meet the definition of the intercept. More often than not, then, there is not much value in bothering to interpret the intercept.</p>
<p>Something you need to be particularly careful about is to interpret the coefficients in a causal manner. At least your data come from an experiment this is unlikely to be helpful. With observational data regression coefficients should not be read as indexing causal relations. This sort of textbook warning is, however, often neglectfully ignored by professional researchers. Often authors carefully draw sharp distinctions between causal and correlational claims when discussing their data analysis, but then interpret the correlational patterns in a totally causal way in their conclusion section. This is what is called the <a href="http://junkcharts.typepad.com/numbersruleyourworld/2012/07/the-causation-creep.html">causation</a> or <a href="http://www.carlislerainey.com/2012/12/05/another-example-of-causal-creep/">causal</a> creep. Beware. Don’t do this tempting as it may be.</p>
<p>Comparing the simple models with this more complex model we could say that adjusting for <code>SOUTH</code> does not change much the impact of <code>RD90</code> in homicide, but that adjusting for resource deprivation halves the impact of the regional effect on homicide.</p>
</div>
<div id="presenting-your-regression-results." class="section level2">
<h2><span class="header-section-number">8.9</span> Presenting your regression results.</h2>
<p>Communicating your results in a clear manner is incredibly important. We have seen the tabular results produced by R. If you want to use them in a paper you may need to do some tidying up of those results. There are a number of packages (<code>textreg</code>, <code>stargazer</code>) that automatise that process. They take your <code>lm</code> objects and produce tables that you can put straight away in your reports or papers. One popular trend in presenting results is the <strong>coefficient plot</strong> as an alternative to the table of regression coefficients. There are various ways of producing coefficient plots with R for a variety of models. See <a href="http://www.carlislerainey.com/2012/06/30/coefficient-plots-in-r/">here</a> and <a href="http://www.carlislerainey.com/2012/07/03/an-improvement-to-coefficient-plots/">here</a>, for example.</p>
<p>We are going to use instead the <code>plot_model()</code> function of the <code>sjPlot</code> package, that makes it easier to produce this sort of plots. You can find a more detailed tutorial about this function <a href="https://strengejacke.wordpress.com/2017/10/23/one-function-to-rule-them-all-visualization-of-regression-models-in-rstats-w-sjplot/">here</a>. See below for an example:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(sjPlot)</code></pre>
<pre><code>## Warning in checkMatrixPackageVersion(): Package version inconsistency detected.
## TMB was built with Matrix version 1.2.15
## Current Matrix version is 1.2.14
## Please re-install &#39;TMB&#39; from source using install.packages(&#39;TMB&#39;, type = &#39;source&#39;) or ask CRAN for a binary version of &#39;TMB&#39; matching CRAN&#39;s &#39;Matrix&#39; package</code></pre>
<p>Let’s try with a more complex example:</p>
<pre class="sourceCode r"><code class="sourceCode r">fit_<span class="dv">4</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR90 <span class="op">~</span><span class="st"> </span>RD90 <span class="op">+</span><span class="st"> </span>SOUTH_f <span class="op">+</span><span class="st"> </span>DV90 <span class="op">+</span><span class="st"> </span>MA90 <span class="op">+</span><span class="st"> </span>PS90, <span class="dt">data=</span>ncovr)
<span class="kw">plot_model</span>(fit_<span class="dv">4</span>, <span class="dt">breakLabelsAt =</span> <span class="dv">30</span>)</code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Visual display of the effects of the variables in the model are particularly helpful. The <code>effects</code> package allows us to produce plots to visualise these relationships (when adjusting for the other variables in the model). Here’s an example going back to our model fit_3 which contained SOUTH and RD90 predictor variables:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(effects)</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## lattice theme set by effectsTheme()
## See ?effectsTheme for details.</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">allEffects</span>(fit_<span class="dv">3</span>), <span class="dt">ask=</span><span class="ot">FALSE</span>)</code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Notice that the line has a confidence interval drawn around it and that the predicted means for southern and northern counties (when controlling for <code>RD90</code>) also have a confidence interval.</p>
</div>
<div id="rescaling-input-variables-to-assist-interpretation" class="section level2">
<h2><span class="header-section-number">8.10</span> Rescaling input variables to assist interpretation</h2>
<p>The interpretation or regression coefficients is sensitive to the scale of measurement of the predictors. This means one cannot compare the magnitude of the coefficients to compare the relevance of variables to predict the response variable. Let’s look at the more recent model, how can we tell what predictors have a stronger effect?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(fit_<span class="dv">4</span>)</code></pre>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ RD90 + SOUTH_f + DV90 + MA90 + PS90, data = ncovr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.740  -2.588  -0.678   1.708  69.180 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.20350    0.98475   4.269 2.03e-05 ***
## RD90         3.19923    0.11167  28.648  &lt; 2e-16 ***
## SOUTH_f1     2.59975    0.21557  12.060  &lt; 2e-16 ***
## DV90         0.47594    0.05308   8.967  &lt; 2e-16 ***
## MA90        -0.07609    0.02743  -2.774  0.00557 ** 
## PS90         1.26451    0.10047  12.587  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.035 on 3079 degrees of freedom
## Multiple R-squared:  0.4262, Adjusted R-squared:  0.4252 
## F-statistic: 457.3 on 5 and 3079 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We just cannot. One way of dealing with this is by rescaling the input variables. A common method involves subtracting the mean and dividing by the standard deviation of each numerical input. The coefficients in these models is the expected difference in the response variable, comparing units that differ by one standard deviation in the predictor while adjusting for other predictors in the model.</p>
<p>Instead, <a href="http://www.stat.columbia.edu/~gelman/research/published/standardizing7.pdf">Gelman (2008)</a> has proposed dividing each numeric variables <em>by two times its standard deviation</em>, so that the generic comparison is with inputs equal to plus/minus one standard deviation. As Gelman explains the resulting coefficients are then comparable to untransformed binary predictors. The implementation of this approach in the <code>arm</code> package subtract the mean of each binary input while it subtract the mean and divide by two standard deviations for every numeric input.</p>
<p>The way we would obtain these rescaled inputs uses the <code>standardize()</code> function of the <code>arm</code> package, that takes as an argument the name of the stored fit model.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(arm)</code></pre>
<pre><code>## 
## arm (Version 1.10-1, built: 2018-4-12)</code></pre>
<pre><code>## Working directory is /Users/reka/Dropbox (The University of Manchester)/crimemapping_textbook_bookdown</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">standardize</span>(fit_<span class="dv">4</span>)</code></pre>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ z.RD90 + c.SOUTH_f + z.DV90 + z.MA90 + z.PS90, 
##     data = ncovr)
## 
## Coefficients:
## (Intercept)       z.RD90    c.SOUTH_f       z.DV90       z.MA90  
##      6.1829       6.3985       2.5998       1.6497      -0.5478  
##      z.PS90  
##      2.5290</code></pre>
<p>Notice the main change affects the numerical predictors. The unstandardised coefficients are influenced by the degree of variability in your predictors, which means that typically they will be larger for your binary inputs. With unstandardised coefficients you are comparing complete change in one variable (whether one is a Southern county or not) with one-unit changes in your numerical variable, which may not amount to much change. So, by putting in a comparable scale, you avoid this problem.</p>
<p>Standardising in the way described here will help you to make fairer comparisons. This standardised coefficients are comparable in a way that the unstandardised coefficients are not. We can now see what inputs have a comparatively stronger effect. It is very important to realise, though, that one <strong>should not</strong> compare standardised coefficients <em>across different models</em>.</p>
</div>
<div id="testing-conditional-hypothesis-interactions" class="section level2">
<h2><span class="header-section-number">8.11</span> Testing conditional hypothesis: interactions</h2>
<p>In the social sciences there is a great interest in what are called conditional hypothesis or interactions. Many of our theories do not assume simply <strong>additive effects</strong> but <strong>multiplicative effects</strong>.For example, <a href="http://euc.sagepub.com/content/8/5/401.short">Wikstrom and his colleagues (2011)</a> suggest that the threat of punishment only affects the probability of involvement on crime for those that have a propensity to offend but are largely irrelevant for people who do not have this propensity. Or you may think that a particular crime prevention programme may work in some environments but not in others. The interest in this kind of conditional hypothesis is growing.</p>
<p>One of the assumptions of the regression model is that the relationship between the response variable and your predictors is additive. That is, if you have two predictors <code>x1</code> and <code>x2</code>. Regression assumes that the effect of <code>x1</code> on <code>y</code> is the same at all levels of <code>x2</code>. If that is not the case, you are then violating one of the assumptions of regression. This is in fact one of the most important assumptions of regression, even if researchers often overlook it.</p>
<p>One way of extending our model to accommodate for interaction effects is to add additional terms to our model, a third predictor <code>x3</code>, where <code>x3</code> is simply the product of multiplying <code>x1</code> by <code>x2</code>. Notice we keep a term for each of the <strong>main effects</strong> (the original predictors) as well as a new term for the interaction effect. “Analysts should include all constitutive terms when specifying multiplicative interaction models except in very rare circumstances” (Brambor et al., 2006: 66).</p>
<p>How do we do this in R? One way is to use the following notation in the formula argument. Notice how we have added a third term <code>RD90:SOUTH_f</code>, which is asking R to test the conditional hypothesis that resource deprivation may have a different impact on homicide for soutern and northern counties.</p>
<pre class="sourceCode r"><code class="sourceCode r">fit_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR90 <span class="op">~</span><span class="st"> </span>RD90 <span class="op">+</span><span class="st"> </span>SOUTH_f <span class="op">+</span><span class="st"> </span>RD90<span class="op">:</span>SOUTH_f , <span class="dt">data=</span>ncovr)
<span class="co"># which is equivalent to: </span>
<span class="co"># fit_5 &lt;- lm(HR90 ~ RD90 * SOUTH_f , data=ncovr)</span>
<span class="kw">summary</span>(fit_<span class="dv">5</span>)</code></pre>
<pre><code>## 
## Call:
## lm(formula = HR90 ~ RD90 + SOUTH_f + RD90:SOUTH_f, data = ncovr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.055  -2.998  -0.566   2.227  68.136 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     4.5477     0.1586  28.675   &lt;2e-16 ***
## RD90            2.5814     0.1963  13.148   &lt;2e-16 ***
## SOUTH_f1        3.2612     0.2247  14.515   &lt;2e-16 ***
## RD90:SOUTH_f1   0.5622     0.2377   2.365   0.0181 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.292 on 3081 degrees of freedom
## Multiple R-squared:  0.3658, Adjusted R-squared:  0.3652 
## F-statistic: 592.4 on 3 and 3081 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>You see here that essentially you have only two inputs (resource deprivation and south) but several regression coefficients. Gelman and Hill (2007) suggest reserving the term input for the variables encoding the information and to use the term predictor to refer to each of the terms in the model. So here we have two inputs and three predictors (one for SOUTH, another for resource deprivation, and a final one for the interaction effect).</p>
<p>In this case the test for the interaction effect is significant, which suggests there is such an interaction. Let’s visualise the results with the <code>effects</code> package:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">allEffects</span>(fit_<span class="dv">5</span>), <span class="dt">ask=</span><span class="ot">FALSE</span>)</code></pre>
<p><img src="08-week8_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>Notice that essentially what we are doing is running two regression lines and testing whether the slope is different for the two groups. The intercept is different, we know that Southern counties are more violent, but what we are testing here is whether the level of homicide goes up in a steeper fashion (and in the same direction) for one or the other group as the level of resource deprivation goes up. We see that’s the case here. The estimated lines are almost parallel, but the slopw is a bit more steep in the Southern counties. In southern counties resource deprivation seems to have more of an impact on homicide than in northern counties.</p>
<p>A word of warning, the moment you introduce an interaction effect the meaning of the coefficients for the other predictors changes (what it is often referred as to the “main effects” as opposed to the interaction effect). You cannot retain the interpretation we introduced earlier. Now, for example, the coefficient for the <code>SOUTH</code> variable relates the marginal effect of this variable when <code>RD90</code> equals zero. The typical table of results helps you to understand whether the effects are significant but offers little of interest that will help you to meaningfully interpret what the effects are. For this is better you use some of the graphical displays we have covered.</p>
<p>Essentially what happens is that the regression coefficients that get printed are interpretable only for certain groups. So now:</p>
<ul>
<li><p>The intercept still represents the predicted score of homicide for southern counties and have a score of 0 in resurce deprivation (as before).</p></li>
<li><p>The coefficient of <code>SOUTH_f1</code> now can be thought of as the difference between the predicted score of homicide rate for northern counties <em>that have a score of 0 in resource deprivation</em> and northern counties <em>that have a score of 0 in resource deprivation</em>.</p></li>
<li><p>The coefficient of <code>RD90</code> now becomes the comparison of mean homicide rate <em>for southern</em> counties who differ by one point in resource deprivation.</p></li>
<li><p>The coefficient for the interaction term represents the difference in the slope for <code>RD90</code> comparing southern and northern counties, the difference in the slope of the two lines that we visualised above.</p></li>
</ul>
<p>Models with interaction terms are too often misinterpreted. I strongly recommend you read this piece by <a href="https://files.nyu.edu/mrg217/public/pa_final.pdf">Brambor et al (2005)</a> to understand some of the issues involved. When discussing logistic regression we will return to this and will consider tricks to ease the interpretation.</p>
<p>Equally, <a href="http://www.jstatsoft.org/v08/i15/paper">John Fox (2003)</a> piece on the <code>effects</code> package goes to much more detail that we can here to explain the logic and some of the options that are available when producing plots to show interactions with this package.</p>
</div>
<div id="model-building-and-variable-selection" class="section level2">
<h2><span class="header-section-number">8.12</span> Model building and variable selection</h2>
<p>How do you construct a good model? This partly depends on your goal, although there are commonalities. You do want to start with theory as a way to select your predictors and when specifying the nature of the relationship to your response variable (e.g., additive, multiplicative). Gelman and Hill (2007) provide a series of general principles<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a>. I would like to emphasise at this stage two of them:</p>
<ul>
<li><p>Include all input variables that, for substantive reasons, might be expected to be important in predicting the outcome.</p></li>
<li><p>For inputs with large effects, consider including their interactions as well.</p></li>
</ul>
<p>It is often the case that for any model, the response variable is only related to a subset of the predictors. There are some scenarios where you may be interested in understanding what is the best subset of predictors. Imagine that you want to develop a risk assessment tool to be used by police officers that respond to a domestic violence incident, so that you could use this tool for forecasting the future risk of violence. There is a cost to adding too many predictors. A police officer time should not be wasted gathering information on predictors that are not associated with future risk. So you may want to identify the predictors that will help in this process.</p>
<p>Ideally, we would like to perform variable selection by trying out a lot of different models, each containing a different subset of the predictors. There are various statistics that help in making comparisons across models. Unfortunately, as the number of potentially relevant predictors increases the number of potential models to compare increases exponentially. So you need methods that help you in this process. There are a number of tools that you can use for <strong>variable selection</strong> but this goes beyond the aims of this introduction. If you are interested you may want to read <a href="http://link.springer.com/chapter/10.1007/978-1-4614-7138-7_6">this</a>.</p>
</div>
<div id="regression-assumptions" class="section level2">
<h2><span class="header-section-number">8.13</span> Regression assumptions</h2>
<p>Although so far we have discussed the practicalities of fitting and interpreting regression models, in practical applications you want to first check your model and proceed from there. Not much point spending time interpreting your model until you know that the model reasonably fits your data.</p>
<p>In previous data analysis modules we surely covered assumptions made by various statistical tests. The regression model also makes assumptions of its own. In fact, there are so many that we could spend an entire class discussing them. Gelman and Hill (2007) point out that the most important regression assumptions by decreasing order of importance are:</p>
<ul>
<li><strong>Validity</strong>. The data should be appropriate for the question that you are trying to answer:</li>
</ul>
<blockquote>
<p>“Optimally, this means that the outcome measure should accurately reflect the phenomenon of interes, the model should include all relevant predictors, and the model should generalize to all cases to which it will be applied… Data used in empirical research rarely meet all (if any) of these criteria precisely. However, keeping these goals in mind can help you be precise about the types of questions you can and cannot answer reliably”</p>
</blockquote>
<ul>
<li><p><strong>Additiviy and linearity</strong>. These are the most important mathematical assumptions of the model. We already talked about additivity in previous sessions and discussed how you can include interaction effects in your models if the additivity assumption is violated. We will discuss problems with non-linearities today as well as ways to diagnose and solve this problem. If the relationship is non linear (e.g, it is curvilinear) predicted values will be wrong in a biased manner, meaning that predicted values will systematically miss the true pattern of the mean of y (as related to the x-variables).</p></li>
<li><p><strong>Independence of errors</strong>. Regression assumes that the errors from the prediciton line (or hyperplane) are independent. If there is dependency between the observations (you are assessing change across the same units, working with spatial units, or with units that are somehowed grouped such as students from the same class), you may have to use models that are more appropriate (e.g., multilevel models, spatial regression, etc.).</p></li>
<li><p><strong>Equal variances of errors</strong>. When the variance of the residuals is unequal, you may need different estimation methods. This is, nonetheless, considered a minor issue. There is a small effect on the validity of t-test and F-test results, but generally regression inferences are robust with regard to the variance issue.</p></li>
<li><p><strong>Normality of errors</strong>. The residuals should be normally distributed. Gelman and Hill (2007: 46) discuss this as the least important of the assumptions and in fact “do <em>not</em> recommend diagnostics of the normality of the regression residuals”. If the errors do not have a normal distribution, it usually is not particularly serious. Regression inferences tend to be robust with respect to normality (or nonnormality of the errors). In practice, the residuals may appear to be nonnormal when the wrong regression equation has been used. So, I will show you how to inspect normality of the residuals not because this is a problem on itself, but because it may be give you further evidence that there is some other problem with the model you are applying to your data.</p></li>
</ul>
<p>Apart from this, it is convenient to diagnose multicollinearity (this affects interpretation) and influential observations.</p>
<p>So these are the assumptions of linear regression, and today we will go through how to test for them, and also what are some options that you can consider if you find that your model violates them. While finding that some of the assumptions are violated do not necessarily mean that you have to scrap your model, it is important to use these diagnostics to illustrate that you have considered what the possible issues with your model is, and if you find any serious issues that you address them.</p>
<p>You may have noticed the second of this assumption is independence of errors. This is an issue with spatial data. If you have spatial autocorrelation basically you are syaing that your observations are not independent. What happens in area X is likely to be similar to what happens in its surrounding neighbors (if you have positive spatial autocorrelation). What do you do? Well, that’s what we will cover next week. We will learn how to fit regression models where you have spatial dependency.</p>
<div id="homework-4" class="section level3">
<h3><span class="header-section-number">8.13.1</span> HOMEWORK</h3>
<p>Fit a regression model with a few relevant explanatory variables for the homicide rate in 1970. Make sure you interpret your results.</p>

<p>#Spatial regression models</p>
</div>
</div>
<div id="introduction-3" class="section level2">
<h2><span class="header-section-number">8.14</span> Introduction</h2>
<p>Last week we provided you with an introduction to regression analysis with R. the data we used had a spatial component. We were modelling the geographical distribution of homicide across US counties. However, we did not incorporated this spatial component into our models. As we have explained througout the semester criminal events often cluster geographically in space. So if we want to develop a regression model for crime we may have to recognise this spatial component. Remember as well, from last week, that regression models assume independence between the observations. That is, a regression model is formally assuming that what happens in area Xi is not in any way related (it is independent) of what happens in area Xii. But if those two areas are adjacent in geographical space we know that there is a good chance that this assumption may be violated. In previous weeks we covered formal tests for spatial autocorrelation, which allow us to test whether this assumption is met or not. So before we fit a regression model with spatial data we need to explore the issue of autocorrelation. We already know how to do this. In this session, we will examine the data from last week, explore whether autocorrelation is an issue, and then introduce models that allow us to take into account spatial autocorrelation. We will see that there are two basic ways of adjusting for spatial autocorrelation: through a spatial lag model or through a spatial error model.</p>
<p>Before we do any of this, we need to load the libraries we will use today:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(sf)</code></pre>
<pre><code>## Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tmap)
<span class="kw">library</span>(sp)
<span class="kw">library</span>(spdep)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: spData</code></pre>
<pre><code>## To access larger datasets in this package, install the spDataLarge
## package with: `install.packages(&#39;spDataLarge&#39;,
## repos=&#39;https://nowosad.github.io/drat/&#39;, type=&#39;source&#39;))`</code></pre>
<p>Then we will bring back the data from last week:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">##R in Windows have some problems with https addresses, that&#39;s why we need to do this first:</span>
urlfile&lt;-<span class="st">&#39;https://s3.amazonaws.com/geoda/data/ncovr.zip&#39;</span>
<span class="kw">download.file</span>(urlfile, <span class="st">&#39;ncovr.zip&#39;</span>)
<span class="co">#Let&#39;s unzip and create a new directory (ncovr) in our working directory to place the files</span>
<span class="kw">unzip</span>(<span class="st">&#39;ncovr.zip&#39;</span>, <span class="dt">exdir =</span> <span class="st">&#39;ncovr&#39;</span>)</code></pre>
<p>Last week we did not treated the data as spatial and, consequently, relied on the csv file. But notice that in the unzip ncovr file there is also a shapefile that we can load as a spatial object into R:</p>
<pre class="sourceCode r"><code class="sourceCode r">shp_name &lt;-<span class="st"> &quot;ncovr/ncovr/NAT.shp&quot;</span>
ncovr_sf &lt;-<span class="st"> </span><span class="kw">st_read</span>(shp_name)</code></pre>
<pre><code>## Reading layer `NAT&#39; from data source `/Users/reka/Dropbox (The University of Manchester)/crimemapping_textbook_bookdown/ncovr/ncovr/NAT.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 3085 features and 69 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -124.7314 ymin: 24.95597 xmax: -66.96985 ymax: 49.37173
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs</code></pre>
<p>We can indeed represent our variable of interest using a choropleth map.</p>
<pre class="sourceCode r"><code class="sourceCode r">current_style &lt;-<span class="st"> </span><span class="kw">tmap_style</span>(<span class="st">&quot;col_blind&quot;</span>)</code></pre>
<pre><code>## tmap style set to &quot;col_blind&quot;</code></pre>
<pre><code>## other available styles are: &quot;white&quot;, &quot;gray&quot;, &quot;natural&quot;, &quot;cobalt&quot;, &quot;albatross&quot;, &quot;beaver&quot;, &quot;bw&quot;, &quot;classic&quot;, &quot;watercolor&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tm_shape</span>(ncovr_sf) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&quot;HR90&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Homicide Rate (Quantiles)&quot;</span>, <span class="dt">style=</span><span class="st">&quot;quantile&quot;</span>, <span class="dt">palette =</span> <span class="st">&quot;Reds&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_borders</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">main.title =</span> <span class="st">&quot;Homicide Rate across US Counties, 1990&quot;</span>, <span class="dt">main.title.size =</span> <span class="fl">0.7</span> ,
            <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;bottom&quot;</span>), <span class="dt">legend.title.size =</span> <span class="fl">0.8</span>)</code></pre>
<p><img src="09-week9_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Do you think there is spatial patterning to homicide?</p>
</div>
<div id="looking-at-the-residuals-and-testing-for-spatial-autocorrelation-in-regression" class="section level2">
<h2><span class="header-section-number">8.15</span> Looking at the residuals and testing for spatial autocorrelation in regression</h2>
<p>Residuals, as we have explained, give you an idea of the distance between our observed Y values and the predicted Y values. So in essence they are deviations of reality from your model. Your regression line or hyperplane is optimised to be the one that best represent your data if those assumptions are met. Residuals are very helpful to diagnose, then, whether your model is a good representation of reality or not. Most diagnostics of the assumptions for OLS regression, which is if you remember from last year the technique we are using, rely on exploring the residuals.</p>
<p>In order to explore the residuals we need to fit our model first. Let’s look at one of the models from last week.</p>
<pre class="sourceCode r"><code class="sourceCode r">fit_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR90 <span class="op">~</span><span class="st"> </span>RD90 <span class="op">+</span><span class="st"> </span>SOUTH <span class="op">+</span><span class="st"> </span>DV90 <span class="op">+</span><span class="st"> </span>MA90 <span class="op">+</span><span class="st"> </span>PS90 <span class="op">+</span>UE90, <span class="dt">data=</span>ncovr_sf)</code></pre>
<p>Now that we have fitted the model we can extract the residuals. If you look at the fit_1 object in your RStudio environment or if you run the str() function to look inside this object you will see that this object is a list with differet elements, one of which is the residuals. An element of this object then includes the residual for each of your observations (the difference between the observed value and the value predicted by your model). We can extract the residuals using the residuals() function and add them to our spatial data set.</p>
<pre class="sourceCode r"><code class="sourceCode r">ncovr_sf<span class="op">$</span>res_fit1 &lt;-<span class="st"> </span><span class="kw">residuals</span>(fit_<span class="dv">1</span>)</code></pre>
<p>If you now look at the dataset you will see that there is a new variable with the residuals. In those cases where the residual is negative this is telling us that the observed value is lower than the predicted (that is, our model is overpredicting the level of homicide for that observation) when the residual is positive the observed value is higher than the predicted (that is, our model is underpredicting the level of homicide for that observation).</p>
<p>We could also extract the predicted values if we wanted. We would use the fitted() function.</p>
<pre class="sourceCode r"><code class="sourceCode r">ncovr_sf<span class="op">$</span>fitted_fit1 &lt;-<span class="st"> </span><span class="kw">fitted</span>(fit_<span class="dv">1</span>)</code></pre>
<p>Now look at the second county in the dataset. It has a homice rate in 1990 of 15.88. This is the observed value. If we look at the new column we have created (fitted_fit1), our model predicts a homicide rate of 2.41. That is, knowing the level unemployment, whether the county is North or South, the level of resource deprivation, etc., we are predicting a homicide rate of 2.41. Now, this is lower than the observed value, so our model is underpredicting the level of homicide in this case. If you observed the residual you will see that it has a value of 13.46, which is simply the difference between the observed and the predicted value.</p>
<p>With spatial data one useful thing to do is to look at any spatial patterning in the distribution of the residuals. Notice that the residuals are the difference between the observed values for homicide and the predicted values for homicide, so you want your residual to NOT display any spatial patterning. If, on the other hand, your model display a patterning in the areas of the study region where it performs predicts badly, then you may have a problem. This is telling your model is not a good representation of the social phenomena you are studying across the full study area: there is systematically more distortion in some areas than in others.</p>
<p>We are going to produce a choropleth map for the residuals, but we will use a common classification method we haven’t covered yet: standard deviations. Standard deviation is a statistical technique type of map based on how much the data differs from the mean. You measure the mean and standard deviation for your data. Then, each standard deviation becomes a class in your choropleth maps.</p>
<p>In order to do that we will compute the mean and the standard deviation for the variable we want to plot and break the variable according to these values. The following code creates a new variable in which we will express the residuals in terms of standard deviations away from the mean. So, for each observation, we substract the mean and divide by the standard deviation.</p>
<pre class="sourceCode r"><code class="sourceCode r">ncovr_sf<span class="op">$</span>sd_breaks &lt;-<span class="st"> </span>(ncovr_sf<span class="op">$</span>res_fit1 <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(ncovr_sf<span class="op">$</span>res_fit1))<span class="op">/</span><span class="kw">sd</span>(ncovr_sf<span class="op">$</span>res_fit1)
<span class="kw">summary</span>(ncovr_sf<span class="op">$</span>sd_breaks)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -3.5370 -0.5238 -0.1404  0.0000  0.3314 13.7407</code></pre>
<p>Next we use a new style, fixed, within the tm_fill function. When we break the variable into classes using the fixed argument we need to specify the boundaries of the classes. We do this using the breaks argument. In this case we are going to ask R to create 7 classes based on standard deviations away from the mean.</p>
<pre class="sourceCode r"><code class="sourceCode r">my_breaks &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">14</span>,<span class="op">-</span><span class="dv">3</span>,<span class="op">-</span><span class="dv">2</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">14</span>)

<span class="kw">tm_shape</span>(ncovr_sf) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&quot;sd_breaks&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Residuals&quot;</span>, <span class="dt">style =</span> <span class="st">&quot;fixed&quot;</span>, <span class="dt">breaks =</span> my_breaks, <span class="dt">palette =</span> <span class="st">&quot;-RdBu&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_borders</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">main.title =</span> <span class="st">&quot;Residuals&quot;</span>, <span class="dt">main.title.size =</span> <span class="fl">0.7</span> ,
            <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;bottom&quot;</span>), <span class="dt">legend.title.size =</span> <span class="fl">0.8</span>)</code></pre>
<pre><code>## Variable &quot;sd_breaks&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="09-week9_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Notice the spatial patterning of areas of over-prediction (negative residuals, or blue tones) and under-prediction (positive residuals, or brown tones). This visual inspection of the residuals is telling you that spatial autocorrelation may be present here. This, however, would require a more formal test.</p>
<p>Remember from week 6 that in order to do this first we need to turn our sf object into a sp class object and then create the spatial weight matrix. If the code below and what it does is not clear to you, revise the notes from week 6 -when we first introduced it.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#We coerce the sf object into a new sp object</span>
ncovr_sp &lt;-<span class="st"> </span><span class="kw">as</span>(ncovr_sf, <span class="st">&quot;Spatial&quot;</span>)
<span class="co">#Then we create a list of neighbours using the Queen criteria</span>
w &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(ncovr_sp, <span class="dt">row.names=</span>ncovr_sp<span class="op">$</span>FIPSNO)
<span class="kw">summary</span>(w)</code></pre>
<pre><code>## Neighbour list object:
## Number of regions: 3085 
## Number of nonzero links: 18168 
## Percentage nonzero weights: 0.190896 
## Average number of links: 5.889141 
## Link number distribution:
## 
##    1    2    3    4    5    6    7    8    9   10   11   13   14 
##   24   36   91  281  620 1037  704  227   50   11    2    1    1 
## 24 least connected regions:
## 53009 53029 25001 44005 36103 51840 51660 6041 51790 51820 51540 51560 6075 51580 51530 51131 51115 51770 51720 51690 51590 27031 26083 55029 with 1 link
## 1 most connected region:
## 49037 with 14 links</code></pre>
<p>This should give you an idea of the distribution of connectedness across the data, with counties having on average nearly 6 neighbours. Now we can generate the row standardise spatial weight matrix and the Moran Scatterplot.</p>
<pre class="sourceCode r"><code class="sourceCode r">wm &lt;-<span class="st"> </span><span class="kw">nb2mat</span>(w, <span class="dt">style=</span><span class="st">&#39;B&#39;</span>)
rwm &lt;-<span class="st"> </span><span class="kw">mat2listw</span>(wm, <span class="dt">style=</span><span class="st">&#39;W&#39;</span>)</code></pre>
<p>We obtain the Moran’s test for regression residuals using the function lm.morantest() as below. It is important to realize that the Moran’s I test statistic for residual spatial autocorrelation takes into account the fact that the variable under consideration is a residual, computed from a regression. The usual Moran’s I test statistic does not. It is therefore incorrect to simply apply a Moran’s I test to the residuals from the regression without correcting for the fact that these are residuals.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm.morantest</span>(fit_<span class="dv">1</span>, rwm, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = HR90 ~ RD90 + SOUTH + DV90 + MA90 + PS90 +
## UE90, data = ncovr_sf)
## weights: rwm
## 
## Moran I statistic standard deviate = 10.321, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## sample estimates:
## Observed Moran I      Expectation         Variance 
##     0.1093062514    -0.0014498532     0.0001151682</code></pre>
<p>You will notice we obtain a statistically significant value for Moran’s I. The value of the Moran’s I test is not too high, but we still need to keep it in mind. If we diagnose that spatial autocorrelation is an issue, that is, that the errors (the residuals) are related systematically among themselves, then we have a problem and need to use a more appropriate approach: a spatial regression model.</p>
</div>
<div id="what-to-do-now" class="section level2">
<h2><span class="header-section-number">8.16</span> What to do now?</h2>
<p>If the test is significant (as in this case), then we possibly need
to think of a more suitable model to represent our data: a spatial regression model. Remember spatial dependence means that there will be areas of spatial clustering for the residuals in our regression model. So our predicted line (or hyperplane) will systematically under-predict or over-predict in areas that are close to each other. That’s not good. We want a better model that does not
display any spatial clustering in the residuals.</p>
<p>There are two general ways of incorporating spatial dependence in a regression model, through what we called a <strong>spatial error model</strong> or by means of a <strong>spatially lagged model</strong>. There are <em>spdep</em> functions that provides us with some tools to help us make a decision as to which of these two is most appropriate: the <strong>Lagrange Multiplier tests</strong>.</p>
<p>The difference between these two models is both technical and conceptual. The <strong>spatial error model</strong> treats the spatial autocorrelation as a nuisance that needs to be dealt with. A spatial error model basically implies that the:</p>
<p><em>spatial dependence observed in our data does not reflect a truly spatial process, but merely the geographical clustering of the sources of the behaviour of interest. For example, citizens in adjoining neighbohoods may favour the same (political) candidate not because they talk to their neighbors, but because citizens with similar incomes tend to cluster geographically, and income also predicts vote choice. Such spatial dependence can be termed attributional dependence&quot;</em> (Darmofal, 2015: 4)</p>
<p>The <strong>spatially lagged model</strong>, on the other hand, incorporates spatial dependence explicitly by adding a “spatially lagged” variable <em>y</em> on the right hand side of our regression equation. Its distinctive
characteristic is that it includes a spatially lagged “dependent” variable among the explanatory factors. It’s basically explicitly saying that the values of y in the neighbouring areas of observation <em>n~i</em> is an important predictor of y on each individual area <em>n~i</em> . This is one way of saying that the spatial dependence may be produced by a spatial process such as the diffusion of behaviour between neighboring units:</p>
<p><em>“If so the behaviour is likely to be highly social in nature, and understanding the interactions between interdependent units is critical to understanding the behaviour in question. For example, citizens may discuss politics across adjoining neighbours such that an increase in support for a candidate in one neighbourhood directly leads to an increase in support for the candidate in adjoining neighbourhoods”</em> (Darmofal, 2015: 4)</p>
</div>
<div id="spatial-regimes" class="section level2">
<h2><span class="header-section-number">8.17</span> Spatial Regimes</h2>
<p>Before we proceed to a more detailed description of these two models it is important that we examine another aspect of our model that also links to geography. Remember that when we brought up our data into R, we decided to test for the presence of an interaction. We looked at whether the role of unemployment was different in Southern and Northern states. We found that this interaction was indeed significant. Unemployment had a more significant effect in Southern than in Northern states. This was particularly obvious during the 1970s, when unemployment did not affected homicide rates in the Northern states, but it did led to a decrease in homicide in the Southern states.</p>
<p>We could have attempted to test other interaction effects between some of our other predictors and their geographical location in the South or the North. But we did not.</p>
<p>If you have read the Ballen et al. (2001) paper that we are replicating in last week and this week lab, you will have noticed that they decided that they needed to run separate models for the South and the North. This kind of situation, where sub-regions, seem to display different patterns often is alluded with the name of spatial regimes. In the context of regression analysis, spatial regimes relates to the possibility that we may need to split our data into two (or more sub-regions) in order to run our models, because we presume that the relationship of the predictors to the outcome may play out differently in these sub-regions (spatial regimes).</p>
<p>So how can we assess whether this is an issue in our data? As with many other diagnostics of regression, you may want to start by looking at your residuals. Look at the residual map we produced earlier. Do you think that the residuals look different in the South and in the North? If the pattern is not clear to you, you may want to run other forms of visualisation.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

<span class="kw">ggplot</span>(ncovr_sf, <span class="kw">aes</span>(<span class="dt">x =</span> res_fit1, <span class="dt">colour =</span> <span class="kw">as.factor</span>(SOUTH))) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_density</span>() </code></pre>
<p><img src="09-week9_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div id="homework-1-3" class="section level3">
<h3><span class="header-section-number">8.17.1</span> HOMEWORK 1</h3>
<p><em>What do you see in this plot? And, critically, what does it mean? What is this telling you about the predicted values that result from our model? (Remember what a residual is: the difference between the observed values and the predicted values).</em></p>
<p>There are formal tests that one can use to further explore these issues. The paper by Bollen et al. (2001) mentions them (Chow tests). But those are beyond the scope of this course. Sufficient to say that, as Bollen et al. (2001), we are going to split our analysis and run them separately for the Southern and the Northern states. We have covered the filter() function from dplyr to split datasets based on values of a variable. But to split sf objects it is better to rely on the more generic subset function, since filter() doesn’t accommodate well the column with the geographic information that sf provides.</p>
<pre class="sourceCode r"><code class="sourceCode r">ncovr_s_sf &lt;-<span class="st"> </span><span class="kw">subset</span>(ncovr_sf, SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)
ncovr_n_sf &lt;-<span class="st"> </span><span class="kw">subset</span>(ncovr_sf, SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)</code></pre>
</div>
</div>
<div id="lagrange-multipliers" class="section level2">
<h2><span class="header-section-number">8.18</span> Lagrange multipliers</h2>
<p>The Moran’s I test statistic has high power against a range of spatial alternatives. However, it does not provide much help in terms of which alternative model would be most appropriate. The Lagrange Multiplier test statistics do allow a distinction between spatial error models and spatial lag models.</p>
<p>In order to practice their computation and interpretation, let’s run two separate OLS regression models (one for the South and one for the North), using the same predictors as we used last week and, first, focusing on homicide in the northern counties in the earliest year for which we have data (1960). We have split the data in two, so that means that before we do this we need to create new files for the spatial weight matrix: in particular we will create one using first order queen criteria.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#We coerce the sf object into a new sp object</span>
ncovr_n_sp &lt;-<span class="st"> </span><span class="kw">as</span>(ncovr_n_sf, <span class="st">&quot;Spatial&quot;</span>)
<span class="co">#Then we create a list of neighbours using the Queen criteria</span>
w_n &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(ncovr_n_sp, <span class="dt">row.names=</span>ncovr_n_sp<span class="op">$</span>FIPSNO)
wm_n &lt;-<span class="st"> </span><span class="kw">nb2mat</span>(w_n, <span class="dt">style=</span><span class="st">&#39;B&#39;</span>)
rwm_n &lt;-<span class="st"> </span><span class="kw">mat2listw</span>(wm_n, <span class="dt">style=</span><span class="st">&#39;W&#39;</span>)

fit_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR60 <span class="op">~</span><span class="st"> </span>RD60 <span class="op">+</span><span class="st"> </span>DV60 <span class="op">+</span><span class="st"> </span>MA60 <span class="op">+</span><span class="st"> </span>PS60 <span class="op">+</span>UE60, <span class="dt">data=</span>ncovr_n_sf)</code></pre>
<p>First look at the Moran’s I.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm.morantest</span>(fit_<span class="dv">2</span>, rwm_n, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## Moran I statistic standard deviate = 2.84, p-value = 0.004511
## alternative hypothesis: two.sided
## sample estimates:
## Observed Moran I      Expectation         Variance 
##     0.0394654814    -0.0022539192     0.0002157889</code></pre>
<p>The p (probability) value associated with this Moran’s I is below our standard threshold. So we will say that we have an issue with spatial autocorrelation that we need to deal with. OLS regression won’t do. In order to decide whether to fit a spatial error or a spatially lagged model we need to run the Lagrange Multipliers.</p>
<p>Both Lagrange multiplier tests (for the error and the lagged models, LMerr and LMlag respectively), as well as their robust forms (RLMerr and RLMLag, also respectively) are included in the lm.LMtests function. Again, a regression object and a spatial listw object must be passed as arguments. In addition, the tests must be specified as a character vector (the default is only LMerror), using the c( ) operator (concatenate), as illustrated below.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm.LMtests</span>(fit_<span class="dv">2</span>, rwm_n, <span class="dt">test =</span> <span class="kw">c</span>(<span class="st">&quot;LMerr&quot;</span>,<span class="st">&quot;LMlag&quot;</span>,<span class="st">&quot;RLMerr&quot;</span>,<span class="st">&quot;RLMlag&quot;</span>,<span class="st">&quot;SARMA&quot;</span>))</code></pre>
<pre><code>## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## LMerr = 7.1326, df = 1, p-value = 0.007569
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## LMlag = 16.595, df = 1, p-value = 4.627e-05
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## RLMerr = 8.2906, df = 1, p-value = 0.003985
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## RLMlag = 17.753, df = 1, p-value = 2.515e-05
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## SARMA = 24.886, df = 2, p-value = 3.946e-06</code></pre>
<p>How do we interpret the Lagrange Multipliers? First we look at the standard ones (LMerr and LMlag). <strong>If both</strong> are below the .05 level this means we need to have a look at the robust version of these tests (Robust LM). If the non-robust version is not significant, the mathematical properties of the robust tests may not hold, so we don’t look at them in those scenarios. It is fairly common to find that both the lag (LMlag) and the error (LMerr) non-robust LM are significant. If only one of them were, problem solved we would choose a spatial lag or a spatial error model according to this (i.e., if the lag M was significant and the error LM was not we would run a spatial lag model or viceversa). Here we see that both are significant, thus, we need to inspect their robust versions.</p>
<p>Yet we look at the robust Lagrange multipliers (RLMlag and RLMerr) and encounter that both are significant again. What do we do? Luc Anselin (2008: 199-200) proposes the following criteria:</p>
<p><em>“When both LM test statistics reject the null hypothesis, proceed to the bottom part of the graph and consider the Robust forms of the test statistics. Typically, only one of them will be significant, or one will be orders of magnitude more significant than the other (e.g., p &lt; 0.00000 compared to p &lt; 0.03). In that case the decision is simple: estimate the spatial regression model matching the (most) significant” robust “statistic. In the rare instance that both would be highly significant, go with the model with the largest value for the test statistic. However, in this situation, some caution is needed, since there may be other sources of misspecification. One obvious action to take is to consider the results for different spatial weight and/or change the basic (i.e., not the spatial part) specification of the model. there are also rare instances where neither of the Robust LM test statistics are significant. In those cases, more serious specification problems are likely present and those should be addressed first”.</em></p>
<p>By other specification errors Prof. Anselin refers to problems with some of the other assumptions of regression that we covered last week.</p>
<p>Ok, so let’s go back to our results and keep this criteria in mind. Both Robust LM are significant, but we can see that the test for the lag model is several orders more significant than for the error model (p &lt; 0.0000251 vs p &lt; 0.004). Notice as well that the test value is higher for the lag model (18 versus 8). In this case we would say that the Lagrange Multiplier tests suggest we estimate a spatial lag model rather than a spatial error model.</p>
<div id="homework-2-4" class="section level3">
<h3><span class="header-section-number">8.18.1</span> HOMEWORK 2</h3>
<p><em>???Run a OLS regression model for homicide rate in 1980 for the Southern states using the covariates we have been using so far and make sure that you ask for the spatial dependence tests and the Lagrange Multipliers (attach the results). What model do you think need to be estimated in this case? The spatial lag or the spatial error model?</em></p>
</div>
</div>
<div id="fitting-and-interpreting-a-spatially-lagged-model" class="section level2">
<h2><span class="header-section-number">8.19</span> Fitting and interpreting a spatially lagged model</h2>
<p>Maximum Likelihood (ML) estimation of the spatial lag model is carried out with the lagsarlm() function. The required arguments are a regression “formula”, a data set and a listw spatial weights object. The default method uses Ord’s eigenvalue decomposition of the spatial weights matrix.</p>
<pre class="sourceCode r"><code class="sourceCode r">fit_<span class="dv">2</span>_lag &lt;-<span class="st"> </span><span class="kw">lagsarlm</span>(HR60 <span class="op">~</span><span class="st"> </span>RD60 <span class="op">+</span><span class="st"> </span>DV60 <span class="op">+</span><span class="st"> </span>MA60 <span class="op">+</span><span class="st"> </span>PS60 <span class="op">+</span>UE60, <span class="dt">data=</span>ncovr_n_sf, rwm_n)
<span class="kw">summary</span>(fit_<span class="dv">2</span>_lag)</code></pre>
<pre><code>## 
## Call:
## lagsarlm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data = ncovr_n_sf, 
##     listw = rwm_n)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -11.86076  -1.54308  -0.55531   0.76832  28.30435 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept)  5.802071   0.677236  8.5673 &lt; 2.2e-16
## RD60         1.734746   0.157771 10.9954 &lt; 2.2e-16
## DV60         1.002757   0.077951 12.8640 &lt; 2.2e-16
## MA60        -0.179328   0.020024 -8.9557 &lt; 2.2e-16
## PS60         0.382956   0.077193  4.9610 7.014e-07
## UE60         0.087963   0.030109  2.9215  0.003483
## 
## Rho: 0.13749, LR test value: 15.139, p-value: 9.9874e-05
## Asymptotic standard error: 0.035631
##     z-value: 3.8587, p-value: 0.000114
## Wald statistic: 14.89, p-value: 0.000114
## 
## Log likelihood: -4273.43 for lag model
## ML residual variance (sigma squared): 9.6542, (sigma: 3.1071)
## Number of observations: 1673 
## Number of parameters estimated: 8 
## AIC: 8562.9, (AIC for lm: 8576)
## LM test for residual autocorrelation
## test value: 10.659, p-value: 0.0010954</code></pre>
<p>As expected, the spatial autoregressive parameter (Rho) is highly significant, as indicated by the p-value of 0.000114 on an asymptotic t-test (based on the asymptotic variance matrix). The Likelihood Ratio test (LR) on this parameter is also highly significant (p value 9.9874e-05).</p>
<p>Just to reiterate, we run the spatial lag model not only because the Lagrange Multiplier suggests this may be appropriate, but also because in this case we believe that the values of y in one county, i, are directly influenced by the values of y that exist in the “neighbors” of i. This is an influence that goes beyond other explanatory variables that are specific to i. Remember what we said earlier in the spatial lag model we are simply adding as an additional explanatory variable the values of y in the surrounding area. What we mean by “surrounding” will be defined by our spatial weight matrix. It’s important to emphasise that one has to think very carefully and explore appropriate definitions of “surrounding” (as we discussed, though just superficially, in the section on spatial clustering a few weeks ago). We are using here the first order queen criteria, but in real practice you would need to explore whether this is the best definition and one that makes theoretical sense.</p>
<p>How do you interpret these results? First you need to look at the general measures of fit of the model. I know what you are thinking. Look at the R Square and compare them, right? Well, don’t. This R Square is not a real R Square, but a pseudo-R Square and therefore is not comparable to the one we obtain from the OLS regression model. Instead we can look at the Akaike Information Criterion. We see that the lag model has a AIC of 8562.9 whereas the linear model with no lags has a AIC of 8576, so this is telling us there is a better fit when we include the spatial lag.</p>
<p>In our spatial lag model you will notice that there is a new term Rho. What is this? This is our spatial lag. It is a variable that measures the homicide rate in the counties that are defined as surrounding each county in our spatial weight matrix. We are simply using this variable as an additional explanatory variable to our model, so that we can appropriately take into account the spatial clustering detected by our Moran’s I test. You will notice that the estimated coefficient for this termis both positive and statistically significant. In other words, when the homicide rate in surrounding areas increases, so does the homicide rate in each country, even when we adjust for the other explanatory variables in our model. The fact the lag is significant adds further evidence that this is a better model than the OLS regression specification.</p>
<p>You also see at the bottom further tests for spatial dependence, a likelihood ratio test. This is not a test for residual spatial autocorrelation after we introduce our spatial lag. What you want is for this test to be significant because in essence is further evidence that the spatial lag model is a good fit.</p>
<p>How about the coefficients? It may be tempting to look at the regression coefficients for the other explanatory variables for the original OLS model and compare them to those in the spatial lag model. But you should be careful when doing this. Their meaning now has changed:</p>
<p>“Interpreting the substantive effects of each predictor in a spatial lag model is much more complex than in a nonspatial model (or in a spatial error model) because of the presence of the spatial multiplier that links the independent variables to the dependent. In the nonspatial model, it does not matter which unit is experiencing the change on the independent variable. The effect” in the dependent variable “of a change” in the value of an independent variable “is constant across all observations” (Darmofal, 2015: 107). Remember we say, when interpreting a regression coefficient for variable X~i, that they indicate how much Y goes up or down for every one unit increase in X~i when holding all other variables in the model constant. In our example, for the nonspatial model this effect is the same for every county in our dataset. But in the spatial lag model things are not the same. We cannot interpret the regression coefficients for the substantive predictors in the same way because the “substantive effects of the independent variables vary by observation as a result of the different neighbors for each unit in the data” (Darmofal, 2015: 107).</p>
<p>In the OLS regression model, the coefficients for any of the explanatory variables measure the absolute impact of these variables. It is a simpler scenario. We look at the effect of X in Y within each county. So X in county A affects Y in count A. In the spatial lag model there are two components to how X affect Y. X affects Y within each county directly but remember we are also including the spatial, the measure of Y in the surrounding counties (call them B, C, and D). So our model includes not only the effect of X in county A in the level of Y in county A. By virtues of including the spatial lag (a measure of Y in county B, C and D) we are indirectly incorporating as well the effects that X has on Y in counties B, C, and D. So the effect of a covariate (independent variable) is the sum of two particular effects: a direct, local effect of the covariate in that unit, and an indirect, spillover effect due to the spatial lag.</p>
<p>In, other words, in the spatial lag model, the coefficients only focus on the “short-run impact” of x~i on y~i , rather than the net effect. As Ward and Gleditsch (2008) explain “Since the value of y~i will influence the level of” homicide “in other” counties y~j and these y~j , in turn, feedback on to y~i , we need to take into account the additional effects that the short impact of x~i exerts on y~i through its impact on the level of&quot; homicide “in other” counties. You can still read the coefficients in the same way but need to keep in mind that they are not measuring the net effect. Part of their effect will be captured by the spatial lag. Yet, you may still want to have a look at whether things change dramatically, particularly in terms of their significance (which is not the case in this example).</p>
</div>
<div id="fitting-an-interpreting-a-spatial-error-model" class="section level2">
<h2><span class="header-section-number">8.20</span> Fitting an interpreting a spatial error model</h2>
<p>We saw (well you should have seen!) that for the case of homicide in the 80s for Southern states the spatial error model was more appropriate when using the 1 st order contiguity queen criteria. In this case then, we need to run a spatial error model.</p>
<p>Maximum likelihood estimation of the spatial error model is similar to the lag procedure and implemented in the errorsarlm() function. Again, the formula, data set and a listw spatial weights object must be specified, as illustrated below.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#We coerce the sf object into a new sp object</span>
ncovr_s_sp &lt;-<span class="st"> </span><span class="kw">as</span>(ncovr_s_sf, <span class="st">&quot;Spatial&quot;</span>)
<span class="co">#Then we create a list of neighbours using the Queen criteria</span>
w_s &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(ncovr_s_sp, <span class="dt">row.names=</span>ncovr_s_sp<span class="op">$</span>FIPSNO)
wm_s &lt;-<span class="st"> </span><span class="kw">nb2mat</span>(w_s, <span class="dt">style=</span><span class="st">&#39;B&#39;</span>)
rwm_s &lt;-<span class="st"> </span><span class="kw">mat2listw</span>(wm_s, <span class="dt">style=</span><span class="st">&#39;W&#39;</span>)

fit_<span class="dv">3</span>_err &lt;-<span class="st"> </span><span class="kw">errorsarlm</span>(HR80 <span class="op">~</span><span class="st"> </span>RD80 <span class="op">+</span><span class="st"> </span>DV80 <span class="op">+</span><span class="st"> </span>MA80 <span class="op">+</span><span class="st"> </span>PS80 <span class="op">+</span>UE80, <span class="dt">data=</span>ncovr_s_sf, rwm_s)
<span class="kw">summary</span>(fit_<span class="dv">3</span>_err)</code></pre>
<pre><code>## 
## Call:errorsarlm(formula = HR80 ~ RD80 + DV80 + MA80 + PS80 + UE80, 
##     data = ncovr_s_sf, listw = rwm_s)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -17.70984  -3.46135  -0.56817   2.55031  24.84717 
## 
## Type: error 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) 11.395096   1.525679  7.4689 8.082e-14
## RD80         3.286154   0.189085 17.3793 &lt; 2.2e-16
## DV80         0.732640   0.133462  5.4895 4.030e-08
## MA80        -0.177938   0.044032 -4.0411 5.319e-05
## PS80         1.540084   0.214637  7.1753 7.216e-13
## UE80        -0.174869   0.066194 -2.6418  0.008248
## 
## Lambda: 0.3026, LR test value: 61.006, p-value: 5.6621e-15
## Asymptotic standard error: 0.037726
##     z-value: 8.0209, p-value: 1.1102e-15
## Wald statistic: 64.335, p-value: 9.992e-16
## 
## Log likelihood: -4384.823 for error model
## ML residual variance (sigma squared): 28.654, (sigma: 5.353)
## Number of observations: 1412 
## Number of parameters estimated: 8 
## AIC: 8785.6, (AIC for lm: 8844.7)</code></pre>
<p>The spatial lag model is probably the most common specification and maybe the most generally useful way to think about spatial dependence. But we can also enter the spatial dependence as, we mentioned trough the error term in our regression equation. Whereas the spatial lag model sees the spatial dependence as substantively meaningful (in that y, say homicide, in county i is influenced by homicide in its neighbours), the spatial error model simply treats the spatial dependence as a nuisance. This model focuses on estimating the regression parameters for the explanatory variables of interest and disregards the possibility that the spatial clustering, the spatial autocorrelation, may reflect something meaningful (other than attributional dependence as explained earlier). So instead of assuming that a spatial lag influences the dependent variable we estimate a model that relaxes the standard regression model assumption about the need for the errors to be independent. It’s beyond the scope of this introductory course to cover the mathematical details of this procedure, though you can use the suggested reading (particularly the highly accessible Ward and Gleditsch,2008, book or the more recent Darmofal, 2015) or some of the video lectures in the matter that are available in the GeoDa website.</p>
<p>As before the AIC is better for the spatial model (8786) than for the non spatial model (8845). In this case, you can compare the regression coefficients with those from the OLS model, since we don’t have a spatial lag capturing some of their effect. Notice how one of the most notable differences is the fact that unemployment nearly halves its impact in the new model. You will see the table includes a new parameter (lambda) but you don’t need to worry about this for the purpose of the course. It is something you would understand if you get into the mathematical estimation details.</p>
<div id="homework-3-1" class="section level3">
<h3><span class="header-section-number">8.20.1</span> HOMEWORK 3</h3>
<p><em>Estimate an appropriate regression model for the homicide rate for the 1970s for the Northern States. Justify and interpret the model that you have selected.</em></p>
</div>
</div>
<div id="interpreting-spatial-lag-coefficiences" class="section level2">
<h2><span class="header-section-number">8.21</span> Interpreting Spatial Lag Coefficiences</h2>
<p>Today we are mostly going to go back to some issues about geographical representation (mapping rates, bins) and other more general issues that are quite revelant when we talk about spatial analysis, and are integral part of a spatial analysis course (e.g., the modifiable area unit problem). But before we do any of that we need to go back to something we mentioned last week about the spatial lag models.</p>
<p>Remember that last week we fitted the following spatial lag model after creating a spatial weight matrix based on Queen first order neighbours:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Split the data into Southern and Northern counties</span>
ncovr_s_sf &lt;-<span class="st"> </span><span class="kw">subset</span>(ncovr_sf, SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)
ncovr_n_sf &lt;-<span class="st"> </span><span class="kw">subset</span>(ncovr_sf, SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)
<span class="co">#We coerce the sf object into a new sp object</span>
ncovr_n_sp &lt;-<span class="st"> </span><span class="kw">as</span>(ncovr_n_sf, <span class="st">&quot;Spatial&quot;</span>)
<span class="co">#Then we create a list of neighbours using the Queen criteria</span>
w_n &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(ncovr_n_sp, <span class="dt">row.names=</span>ncovr_n_sp<span class="op">$</span>FIPSNO)
wm_n &lt;-<span class="st"> </span><span class="kw">nb2mat</span>(w_n, <span class="dt">style=</span><span class="st">&#39;B&#39;</span>)
rwm_n &lt;-<span class="st"> </span><span class="kw">mat2listw</span>(wm_n, <span class="dt">style=</span><span class="st">&#39;W&#39;</span>)
<span class="co">#Fit model</span>
fit_<span class="dv">1</span>_lag &lt;-<span class="st"> </span><span class="kw">lagsarlm</span>(HR60 <span class="op">~</span><span class="st"> </span>RD60 <span class="op">+</span><span class="st"> </span>DV60 <span class="op">+</span><span class="st"> </span>MA60 <span class="op">+</span><span class="st"> </span>PS60 <span class="op">+</span>UE60, <span class="dt">data=</span>ncovr_n_sf, rwm_n)
<span class="kw">summary</span>(fit_<span class="dv">1</span>_lag)</code></pre>
<pre><code>## 
## Call:
## lagsarlm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data = ncovr_n_sf, 
##     listw = rwm_n)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -11.86076  -1.54308  -0.55531   0.76832  28.30435 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept)  5.802071   0.677236  8.5673 &lt; 2.2e-16
## RD60         1.734746   0.157771 10.9954 &lt; 2.2e-16
## DV60         1.002757   0.077951 12.8640 &lt; 2.2e-16
## MA60        -0.179328   0.020024 -8.9557 &lt; 2.2e-16
## PS60         0.382956   0.077193  4.9610 7.014e-07
## UE60         0.087963   0.030109  2.9215  0.003483
## 
## Rho: 0.13749, LR test value: 15.139, p-value: 9.9874e-05
## Asymptotic standard error: 0.035631
##     z-value: 3.8587, p-value: 0.000114
## Wald statistic: 14.89, p-value: 0.000114
## 
## Log likelihood: -4273.43 for lag model
## ML residual variance (sigma squared): 9.6542, (sigma: 3.1071)
## Number of observations: 1673 
## Number of parameters estimated: 8 
## AIC: 8562.9, (AIC for lm: 8576)
## LM test for residual autocorrelation
## test value: 10.659, p-value: 0.0010954</code></pre>
<p>Remember what we said last week:</p>
<p>“Interpreting the substantive effects of each predictor in a spatial lag model is much more complex than in a nonspatial model (or in a spatial error model) because of the presence of the spatial multiplier that links the independent variables to the dependent. In the nonspatial model, it does not matter which unit is experiencing the change on the independent variable. The effect” in the dependent variable “of a change” in the value of an independent variable “is constant across all observations” (Darmofal, 2015: 107). Remember we say, when interpreting a regression coefficient for variable X~i, that they indicate how much Y goes up or down for every one unit increase in X~i when holding all other variables in the model constant. In our example, for the nonspatial model this effect is the same for every county in our dataset. But in the spatial lag model things are not the same. We cannot interpret the regression coefficients for the substantive predictors in the same way because the “substantive effects of the independent variables vary by observation as a result of the different neighbors for each unit in the data” (Darmofal, 2015: 107).</p>
<p>In the OLS regression model, the coefficients for any of the explanatory variables measure the absolute impact of these variables. It is a simpler scenario. We look at the effect of X in Y within each county. So X in county A affects Y in count A. In the spatial lag model there are two components to how X affect Y. X affects Y within each county directly but remember we are also including the spatial, the measure of Y in the surrounding counties (call them B, C, and D). So our model includes not only the effect of X in county A in the level of Y in county A. By virtues of including the spatial lag (a measure of Y in county B, C and D) we are indirectly incorporating as well the effects that X has on Y in counties B, C, and D. So the effect of a covariate (independent variable) is the sum of two particular effects: a direct, local effect of the covariate in that unit, and an indirect, spillover effect due to the spatial lag.</p>
<p>This implies that a change in the ith region’s predictor can affect the jth region’s outcome. We have 2 situations: (a) the direct impact of an observation’s predictor on its own outcome, and (b) the indirect impact of an observation’s neighbor’s predictor on its outcome.This leads to three quantities that we want to know:</p>
<p>-Average Direct Impact, which is similar to a traditional interpretation
-Average Total impact, which would be the total of direct and indirect impacts of a predictor on one’s outcome
-Average Indirect impact, which would be the average impact of one’s neighbors on one’s outcome</p>
<p>These quantities can be found using the impacts() function in the spdep library. We follow the example that converts the spatial weight matrix into a “sparse” matrix, and power it up using the trW() function. This follows the approximation methods described in Lesage and Pace, 2009. Here, we use Monte Carlo simulation to obtain simulated distributions of the various impacts.</p>
<pre class="sourceCode r"><code class="sourceCode r">W &lt;-<span class="st"> </span><span class="kw">as</span>(rwm_n, <span class="st">&quot;CsparseMatrix&quot;</span>)
trMC &lt;-<span class="st"> </span><span class="kw">trW</span>(W, <span class="dt">type=</span><span class="st">&quot;MC&quot;</span>)
im&lt;-<span class="kw">impacts</span>(fit_<span class="dv">1</span>_lag, <span class="dt">tr=</span>trMC, <span class="dt">R=</span><span class="dv">100</span>)
sums&lt;-<span class="kw">summary</span>(im,  <span class="dt">zstats=</span>T)
<span class="co">#To print the coefficients</span>
<span class="kw">data.frame</span>(sums<span class="op">$</span>res)</code></pre>
<pre><code>##        direct    indirect      total
## 1  1.74079931  0.27047142  2.0112707
## 2  1.00625581  0.15634395  1.1625998
## 3 -0.17995336 -0.02795971 -0.2079131
## 4  0.38429189  0.05970819  0.4440001
## 5  0.08827032  0.01371473  0.1019851</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#To print the p values</span>
<span class="kw">data.frame</span>(sums<span class="op">$</span>pzmat)</code></pre>
<pre><code>##            Direct     Indirect        Total
## RD60 0.000000e+00 0.0005297197 0.000000e+00
## DV60 0.000000e+00 0.0004665117 0.000000e+00
## MA60 0.000000e+00 0.0012529767 4.440892e-16
## PS60 3.767540e-08 0.0042974481 8.089557e-08
## UE60 2.969916e-03 0.0332419432 3.174851e-03</code></pre>
<p>We see that all the variables have signficant direct, indirect and total effects. You may want to have a look at how things differ when you just run a non spatial model.</p>
<pre class="sourceCode r"><code class="sourceCode r">fit_<span class="dv">1</span>_OLS &lt;-<span class="st"> </span><span class="kw">lm</span>(HR60 <span class="op">~</span><span class="st"> </span>RD60 <span class="op">+</span><span class="st"> </span>DV60 <span class="op">+</span><span class="st"> </span>MA60 <span class="op">+</span><span class="st"> </span>PS60 <span class="op">+</span>UE60, <span class="dt">data=</span>ncovr_n_sf)
<span class="kw">summary</span>(fit_<span class="dv">1</span>_OLS)</code></pre>
<pre><code>## 
## Call:
## lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data = ncovr_n_sf)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.1581  -1.5986  -0.5770   0.7949  28.4121 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  6.39963    0.66312   9.651  &lt; 2e-16 ***
## RD60         1.85730    0.15692  11.836  &lt; 2e-16 ***
## DV60         1.11883    0.07604  14.713  &lt; 2e-16 ***
## MA60        -0.19537    0.01976  -9.889  &lt; 2e-16 ***
## PS60         0.37748    0.07782   4.851 1.34e-06 ***
## UE60         0.09277    0.03021   3.071  0.00217 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.132 on 1667 degrees of freedom
## Multiple R-squared:  0.1833, Adjusted R-squared:  0.1809 
## F-statistic: 74.83 on 5 and 1667 DF,  p-value: &lt; 2.2e-16</code></pre>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p><a href="http://link.springer.com/chapter/10.1007/978-1-4614-9170-5_15">This</a> is a fine chapter too if you struggle with the explanations in the required reading. Many universities, like the University of Manchester, have full access to Springer ebooks. You can also have a look at <a href="http://people.stern.nyu.edu/wgreene/Statistics/MultipleRegressionBasicsCollection.pdf">these notes</a>.<a href="regression-analysis-a-refresher.html#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p><a href="http://blog.minitab.com/blog/adventures-in-statistics/regression-analysis-how-do-i-interpret-r-squared-and-assess-the-goodness-of-fit">This</a> is a reasonable explanation of how to interpret R-Squared.<a href="regression-analysis-a-refresher.html#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p><a href="http://www.sumsar.net/blog/2013/12/an-animation-of-the-construction-of-a-confidence-interval/">This blog post</a> provides a nice animation of the confidence interval and hypothesis testing.<a href="regression-analysis-a-refresher.html#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p><a href="http://vudlab.com/simpsons/">This</a> is a nice illustration of the Simpon’s Paradox, a well known example of ommitted variable bias.<a href="regression-analysis-a-refresher.html#fnref4" class="footnote-back">↩</a></p></li>
<li id="fn5"><p>I recommend reading chapter 13 “Woes of regression coefficients” of an old book Mostseller and Tukey (1977) Data Analysis and Regression. Reading: Addison-Wesley Publishing.<a href="regression-analysis-a-refresher.html#fnref5" class="footnote-back">↩</a></p></li>
<li id="fn6"><p>Look at <a href="http://www.r-bloggers.com/stop-using-bivariate-correlations-for-variable-selection/">this</a> too.<a href="regression-analysis-a-refresher.html#fnref6" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="global-and-local-spatial-autocorrelation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="time-matters.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/08-week8.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["CrimeMapping.pdf", "CrimeMapping.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
