<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Crime Mapping in R</title>
  <meta name="description" content="Worksheets for labs of Crime Mapping course">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Crime Mapping in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Worksheets for labs of Crime Mapping course" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Crime Mapping in R" />
  
  <meta name="twitter:description" content="Worksheets for labs of Crime Mapping course" />
  

<meta name="author" content="Juanjo Medina and Reka Solymosi">


<meta name="date" content="2019-02-05">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="week-8-regression-analysis-a-refresher.html">
<link rel="next" href="week-10.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Crime mapping in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prelude</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i><b>0.1</b> Introduction</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>0.2</b> Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html"><i class="fa fa-check"></i><b>1</b> A first lesson about R (Week 1)</a><ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#install-r-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#open-up-and-explore-rstudio"><i class="fa fa-check"></i><b>1.2</b> Open up and explore RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>1.3</b> Customising the RStudio look</a></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>1.4</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="1.5" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#talk-to-your-computer"><i class="fa fa-check"></i><b>1.5</b> Talk to your computer</a></li>
<li class="chapter" data-level="1.6" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#more-on-packages"><i class="fa fa-check"></i><b>1.6</b> More on packages</a></li>
<li class="chapter" data-level="1.7" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#using-objects"><i class="fa fa-check"></i><b>1.7</b> Using objects</a></li>
<li class="chapter" data-level="1.8" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#more-on-objects"><i class="fa fa-check"></i><b>1.8</b> More on objects</a></li>
<li class="chapter" data-level="1.9" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#vectors"><i class="fa fa-check"></i><b>1.9</b> Vectors</a></li>
<li class="chapter" data-level="1.10" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#on-comments"><i class="fa fa-check"></i><b>1.10</b> On comments</a></li>
<li class="chapter" data-level="1.11" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#factors"><i class="fa fa-check"></i><b>1.11</b> Factors</a></li>
<li class="chapter" data-level="1.12" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#naming-conventions-for-objects-in-r"><i class="fa fa-check"></i><b>1.12</b> Naming conventions for objects in R</a></li>
<li class="chapter" data-level="1.13" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#dataframes"><i class="fa fa-check"></i><b>1.13</b> Dataframes</a></li>
<li class="chapter" data-level="1.14" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#exploring-data"><i class="fa fa-check"></i><b>1.14</b> Exploring data</a></li>
<li class="chapter" data-level="1.15" data-path="a-first-lesson-about-r-week-1.html"><a href="a-first-lesson-about-r-week-1.html#quitting-rstudio"><i class="fa fa-check"></i><b>1.15</b> Quitting RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html"><i class="fa fa-check"></i><b>2</b> Week 2: Making your first maps in R</a><ul>
<li class="chapter" data-level="2.1" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#a-quick-introduction-of-terms"><i class="fa fa-check"></i><b>2.1</b> A quick introduction of terms</a><ul>
<li class="chapter" data-level="2.1.1" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#geospatial-perspective---the-basics"><i class="fa fa-check"></i><b>2.1.1</b> Geospatial Perspective - The Basics</a></li>
<li class="chapter" data-level="2.1.2" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#summary"><i class="fa fa-check"></i><b>2.1.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#getting-some-spatial-data-to-put-on-a-map"><i class="fa fa-check"></i><b>2.2</b> Getting some spatial data to put on a map</a><ul>
<li class="chapter" data-level="2.2.1" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#a-first-look-at-basemaps"><i class="fa fa-check"></i><b>2.2.1</b> A first look at basemaps</a></li>
<li class="chapter" data-level="2.2.2" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#find-some-relevant-data-to-show-obtaining-data-on-crime"><i class="fa fa-check"></i><b>2.2.2</b> Find some relevant data to show: obtaining data on crime</a></li>
<li class="chapter" data-level="2.2.3" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#add-a-point-layer-to-your-basemap"><i class="fa fa-check"></i><b>2.2.3</b> Add a point layer to your basemap</a></li>
<li class="chapter" data-level="2.2.4" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#homework-1"><i class="fa fa-check"></i><b>2.2.4</b> HOMEWORK 1</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#from-dataframes-to-spatial-objects-finding-shapefiles"><i class="fa fa-check"></i><b>2.3</b> From dataframes to spatial objects: finding shapefiles</a></li>
<li class="chapter" data-level="2.4" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#reading-shapefiles-into-r-the-wonderful-world-of-sf-objects"><i class="fa fa-check"></i><b>2.4</b> Reading shapefiles into R: the wonderful world of sf objects</a><ul>
<li class="chapter" data-level="2.4.1" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#homework-2"><i class="fa fa-check"></i><b>2.4.1</b> <strong>HOMEWORK 2</strong></a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#add-some-data"><i class="fa fa-check"></i><b>2.5</b> Add some data</a><ul>
<li class="chapter" data-level="2.5.1" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>2.5.1</b> Data wrangling with dplyr</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#join-data-to-spatial-object"><i class="fa fa-check"></i><b>2.6</b> Join data to spatial object</a></li>
<li class="chapter" data-level="2.7" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#so-left_join-eh"><i class="fa fa-check"></i><b>2.7</b> So left_join(), eh?</a></li>
<li class="chapter" data-level="2.8" data-path="week-2-making-your-first-maps-in-r.html"><a href="week-2-making-your-first-maps-in-r.html#lets-make-this-prettier-a-quick-glance-at-tmap"><i class="fa fa-check"></i><b>2.8</b> Let’s make this prettier: a quick glance at tmap</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html"><i class="fa fa-check"></i><b>3</b> Week 3: Thematic maps in R</a><ul>
<li class="chapter" data-level="3.1" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#intro-and-recap"><i class="fa fa-check"></i><b>3.1</b> Intro and recap</a></li>
<li class="chapter" data-level="3.2" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#creating-choropleth-maps"><i class="fa fa-check"></i><b>3.2</b> Creating choropleth maps</a></li>
<li class="chapter" data-level="3.3" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#producing-small-multiples-to-compare-the-effect-of-different-classification-systems"><i class="fa fa-check"></i><b>3.3</b> Producing small multiples to compare the effect of different classification systems</a><ul>
<li class="chapter" data-level="3.3.1" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#homework-1-1"><i class="fa fa-check"></i><b>3.3.1</b> Homework 1</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#using-graduated-symbols"><i class="fa fa-check"></i><b>3.4</b> Using graduated symbols</a></li>
<li class="chapter" data-level="3.5" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#bringing-additional-census-data-in"><i class="fa fa-check"></i><b>3.5</b> Bringing additional census data in</a></li>
<li class="chapter" data-level="3.6" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#computing-and-mapping-crime-rates"><i class="fa fa-check"></i><b>3.6</b> Computing and mapping crime rates</a><ul>
<li class="chapter" data-level="3.6.1" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#homework-2-1"><i class="fa fa-check"></i><b>3.6.1</b> Homework 2</a></li>
<li class="chapter" data-level="3.6.2" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#homework-3"><i class="fa fa-check"></i><b>3.6.2</b> Homework 3</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="week-3-thematic-maps-in-r.html"><a href="week-3-thematic-maps-in-r.html#more-on-small-multiples-and-point-pattern-maps"><i class="fa fa-check"></i><b>3.7</b> More on small multiples and point pattern maps</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html"><i class="fa fa-check"></i><b>4</b> Week 4: Performing spatial operations in R</a><ul>
<li class="chapter" data-level="4.1" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#getting-some-more-data"><i class="fa fa-check"></i><b>4.1</b> Getting some (more) data</a><ul>
<li class="chapter" data-level="4.1.1" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#reading-data-in-from-the-web"><i class="fa fa-check"></i><b>4.1.1</b> Reading data in from the web</a></li>
<li class="chapter" data-level="4.1.2" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#subsetting-using-pattern-matching"><i class="fa fa-check"></i><b>4.1.2</b> Subsetting using pattern matching</a></li>
<li class="chapter" data-level="4.1.3" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#geocoding-from-an-address"><i class="fa fa-check"></i><b>4.1.3</b> Geocoding from an address</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#making-interactive-maps-with-leaflet"><i class="fa fa-check"></i><b>4.2</b> Making interactive maps with leaflet</a><ul>
<li class="chapter" data-level="4.2.1" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#making-a-map"><i class="fa fa-check"></i><b>4.2.1</b> Making a map</a></li>
<li class="chapter" data-level="4.2.2" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#adding-some-content"><i class="fa fa-check"></i><b>4.2.2</b> Adding some content:</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#adding-points-manually"><i class="fa fa-check"></i><b>4.3</b> Adding points manually:</a><ul>
<li class="chapter" data-level="4.3.1" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#change-the-basemap"><i class="fa fa-check"></i><b>4.3.1</b> Change the basemap</a></li>
<li class="chapter" data-level="4.3.2" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#adding-data-from-elsewhere"><i class="fa fa-check"></i><b>4.3.2</b> Adding data from elsewhere</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#spatial-operations"><i class="fa fa-check"></i><b>4.4</b> Spatial operations</a><ul>
<li class="chapter" data-level="4.4.1" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#coordinate-reference-systems-revisited"><i class="fa fa-check"></i><b>4.4.1</b> Coordinate reference systems revisited</a></li>
<li class="chapter" data-level="4.4.2" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#meet-a-new-format-of-shapefile-geojson"><i class="fa fa-check"></i><b>4.4.2</b> Meet a new format of shapefile: geojson</a></li>
<li class="chapter" data-level="4.4.3" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#subset-points-to-those-within-a-polygon"><i class="fa fa-check"></i><b>4.4.3</b> Subset points to those within a polygon</a></li>
<li class="chapter" data-level="4.4.4" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#spatial-operations-two-building-buffers"><i class="fa fa-check"></i><b>4.4.4</b> Spatial operations two: building buffers</a></li>
<li class="chapter" data-level="4.4.5" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#points-in-polygon"><i class="fa fa-check"></i><b>4.4.5</b> Points in Polygon</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#recap"><i class="fa fa-check"></i><b>4.5</b> Recap</a></li>
<li class="chapter" data-level="4.6" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#homework"><i class="fa fa-check"></i><b>4.6</b> Homework</a><ul>
<li class="chapter" data-level="4.6.1" data-path="week-4-performing-spatial-operations-in-r.html"><a href="week-4-performing-spatial-operations-in-r.html#geocode-the-addresses"><i class="fa fa-check"></i><b>4.6.1</b> <strong>Geocode the addresses:</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html"><i class="fa fa-check"></i><b>5</b> Week 5 : Studying spatial point patterns</a><ul>
<li class="chapter" data-level="5.1" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html#what-well-do-today"><i class="fa fa-check"></i><b>5.1</b> What we’ll do today</a></li>
<li class="chapter" data-level="5.2" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html#getting-the-data"><i class="fa fa-check"></i><b>5.2</b> Getting the data</a></li>
<li class="chapter" data-level="5.3" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html#getting-the-data-into-spatstat-the-problem-with-duplicates"><i class="fa fa-check"></i><b>5.3</b> Getting the data into spatstat: the problem with duplicates</a></li>
<li class="chapter" data-level="5.4" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html#inspecting-our-data-with-spatstat"><i class="fa fa-check"></i><b>5.4</b> Inspecting our data with spatstat</a></li>
<li class="chapter" data-level="5.5" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html#density-estimates"><i class="fa fa-check"></i><b>5.5</b> Density estimates</a></li>
<li class="chapter" data-level="5.6" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html#adding-some-context"><i class="fa fa-check"></i><b>5.6</b> Adding some context</a><ul>
<li class="chapter" data-level="5.6.1" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html#homework-1-2"><i class="fa fa-check"></i><b>5.6.1</b> Homework 1</a></li>
<li class="chapter" data-level="5.6.2" data-path="week-5-studying-spatial-point-patterns.html"><a href="week-5-studying-spatial-point-patterns.html#homework-2-2"><i class="fa fa-check"></i><b>5.6.2</b> Homework 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html"><i class="fa fa-check"></i><b>6</b> Week 6 : Spatial autocorrelation</a><ul>
<li class="chapter" data-level="6.1" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html#get-data"><i class="fa fa-check"></i><b>6.1</b> Get data</a></li>
<li class="chapter" data-level="6.2" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html#what-is-a-neighbour"><i class="fa fa-check"></i><b>6.2</b> What is a neighbour?</a><ul>
<li class="chapter" data-level="6.2.1" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html#homework-1-3"><i class="fa fa-check"></i><b>6.2.1</b> Homework 1</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html#creating-a-list-of-neighbours"><i class="fa fa-check"></i><b>6.3</b> Creating a list of neighbours</a></li>
<li class="chapter" data-level="6.4" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html#generating-the-weight-matrix"><i class="fa fa-check"></i><b>6.4</b> Generating the weight matrix</a><ul>
<li class="chapter" data-level="6.4.1" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html#homework-2-3"><i class="fa fa-check"></i><b>6.4.1</b> Homework 2</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html#compute-morans-i"><i class="fa fa-check"></i><b>6.5</b> Compute Moran’s I</a><ul>
<li class="chapter" data-level="6.5.1" data-path="week-6-spatial-autocorrelation.html"><a href="week-6-spatial-autocorrelation.html#homework-3-optional-practice"><i class="fa fa-check"></i><b>6.5.1</b> Homework 3 (Optional Practice)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7-local-spatial-autocorrelation.html"><a href="week-7-local-spatial-autocorrelation.html"><i class="fa fa-check"></i><b>7</b> Week 7 : Local spatial autocorrelation</a><ul>
<li class="chapter" data-level="7.1" data-path="week-7-local-spatial-autocorrelation.html"><a href="week-7-local-spatial-autocorrelation.html#prelude-1"><i class="fa fa-check"></i><b>7.1</b> Prelude</a></li>
<li class="chapter" data-level="7.2" data-path="week-7-local-spatial-autocorrelation.html"><a href="week-7-local-spatial-autocorrelation.html#get-data-and-built-the-weight-matrix"><i class="fa fa-check"></i><b>7.2</b> Get data and built the weight matrix</a></li>
<li class="chapter" data-level="7.3" data-path="week-7-local-spatial-autocorrelation.html"><a href="week-7-local-spatial-autocorrelation.html#generating-and-visualising-the-lisa-measures"><i class="fa fa-check"></i><b>7.3</b> Generating and visualising the LISA measures</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html"><i class="fa fa-check"></i><b>8</b> # Week 8 : Regression analysis (a refresher)</a><ul>
<li class="chapter" data-level="8.1" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#introduction-1"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#motivating-regression"><i class="fa fa-check"></i><b>8.2</b> Motivating regression</a></li>
<li class="chapter" data-level="8.3" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#fitting-a-simple-regression-model"><i class="fa fa-check"></i><b>8.3</b> Fitting a simple regression model</a></li>
<li class="chapter" data-level="8.4" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#residuals-revisited-r-squared"><i class="fa fa-check"></i><b>8.4</b> Residuals revisited: R squared</a></li>
<li class="chapter" data-level="8.5" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#inference-with-regression"><i class="fa fa-check"></i><b>8.5</b> Inference with regression</a></li>
<li class="chapter" data-level="8.6" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#fitting-regression-with-categorical-predictors"><i class="fa fa-check"></i><b>8.6</b> Fitting regression with categorical predictors</a></li>
<li class="chapter" data-level="8.7" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#motivating-multiple-regression"><i class="fa fa-check"></i><b>8.7</b> Motivating multiple regression</a></li>
<li class="chapter" data-level="8.8" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#fitting-and-interpreting-a-multiple-regression-model"><i class="fa fa-check"></i><b>8.8</b> Fitting and interpreting a multiple regression model</a></li>
<li class="chapter" data-level="8.9" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#presenting-your-regression-results."><i class="fa fa-check"></i><b>8.9</b> Presenting your regression results.</a></li>
<li class="chapter" data-level="8.10" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#rescaling-input-variables-to-assist-interpretation"><i class="fa fa-check"></i><b>8.10</b> Rescaling input variables to assist interpretation</a></li>
<li class="chapter" data-level="8.11" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#testing-conditional-hypothesis-interactions"><i class="fa fa-check"></i><b>8.11</b> Testing conditional hypothesis: interactions</a></li>
<li class="chapter" data-level="8.12" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#model-building-and-variable-selection"><i class="fa fa-check"></i><b>8.12</b> Model building and variable selection</a></li>
<li class="chapter" data-level="8.13" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#regression-assumptions"><i class="fa fa-check"></i><b>8.13</b> Regression assumptions</a><ul>
<li class="chapter" data-level="8.13.1" data-path="week-8-regression-analysis-a-refresher.html"><a href="week-8-regression-analysis-a-refresher.html#homework-4"><i class="fa fa-check"></i><b>8.13.1</b> HOMEWORK</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html"><i class="fa fa-check"></i><b>9</b> Week 9 : Spatial regression models</a><ul>
<li class="chapter" data-level="9.1" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#introduction-2"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#looking-at-the-residuals-and-testing-for-spatial-autocorrelation-in-regression"><i class="fa fa-check"></i><b>9.2</b> Looking at the residuals and testing for spatial autocorrelation in regression</a></li>
<li class="chapter" data-level="9.3" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#what-to-do-now"><i class="fa fa-check"></i><b>9.3</b> What to do now?</a></li>
<li class="chapter" data-level="9.4" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#spatial-regimes"><i class="fa fa-check"></i><b>9.4</b> Spatial Regimes</a><ul>
<li class="chapter" data-level="9.4.1" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#homework-1-4"><i class="fa fa-check"></i><b>9.4.1</b> HOMEWORK 1</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#lagrange-multipliers"><i class="fa fa-check"></i><b>9.5</b> Lagrange multipliers</a><ul>
<li class="chapter" data-level="9.5.1" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#homework-2-4"><i class="fa fa-check"></i><b>9.5.1</b> HOMEWORK 2</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#fitting-and-interpreting-a-spatially-lagged-model"><i class="fa fa-check"></i><b>9.6</b> Fitting and interpreting a spatially lagged model</a></li>
<li class="chapter" data-level="9.7" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#fitting-an-interpreting-a-spatial-error-model"><i class="fa fa-check"></i><b>9.7</b> Fitting an interpreting a spatial error model</a><ul>
<li class="chapter" data-level="9.7.1" data-path="week-9-spatial-regression-models.html"><a href="week-9-spatial-regression-models.html#homework-3-1"><i class="fa fa-check"></i><b>9.7.1</b> HOMEWORK 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-10.html"><a href="week-10.html"><i class="fa fa-check"></i><b>10</b> Week 10</a><ul>
<li class="chapter" data-level="10.1" data-path="week-10.html"><a href="week-10.html#introduction-3"><i class="fa fa-check"></i><b>10.1</b> Introduction</a><ul>
<li class="chapter" data-level="10.1.1" data-path="week-10.html"><a href="week-10.html#pro-tip-do-i-need-to-install-this-package"><i class="fa fa-check"></i><b>10.1.1</b> Pro-tip: do I need to install this package?</a></li>
<li class="chapter" data-level="10.1.2" data-path="week-10.html"><a href="week-10.html#data"><i class="fa fa-check"></i><b>10.1.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="week-10.html"><a href="week-10.html#interpreting-spatial-lag-coefficiences"><i class="fa fa-check"></i><b>10.2</b> Interpreting Spatial Lag Coefficiences</a></li>
<li class="chapter" data-level="10.3" data-path="week-10.html"><a href="week-10.html#mapping-rates-learning-from-disease-mapping"><i class="fa fa-check"></i><b>10.3</b> Mapping rates, learning from disease mapping</a></li>
<li class="chapter" data-level="10.4" data-path="week-10.html"><a href="week-10.html#binning"><i class="fa fa-check"></i><b>10.4</b> Binning</a><ul>
<li class="chapter" data-level="10.4.1" data-path="week-10.html"><a href="week-10.html#the-binning-process"><i class="fa fa-check"></i><b>10.4.1</b> The Binning Process</a></li>
<li class="chapter" data-level="10.4.2" data-path="week-10.html"><a href="week-10.html#different-binning-techniques"><i class="fa fa-check"></i><b>10.4.2</b> Different Binning Techniques</a></li>
<li class="chapter" data-level="10.4.3" data-path="week-10.html"><a href="week-10.html#homework-10.3"><i class="fa fa-check"></i><b>10.4.3</b> Homework 10.3</a></li>
<li class="chapter" data-level="10.4.4" data-path="week-10.html"><a href="week-10.html#multivariate-binning"><i class="fa fa-check"></i><b>10.4.4</b> Multivariate binning</a></li>
<li class="chapter" data-level="10.4.5" data-path="week-10.html"><a href="week-10.html#benefits-of-binning"><i class="fa fa-check"></i><b>10.4.5</b> Benefits of Binning</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="week-10.html"><a href="week-10.html#a-final-note-of-caution-maup"><i class="fa fa-check"></i><b>10.5</b> A final note of caution: MAUP</a><ul>
<li class="chapter" data-level="10.5.1" data-path="week-10.html"><a href="week-10.html#what-is-maup"><i class="fa fa-check"></i><b>10.5.1</b> What is MAUP?</a></li>
<li class="chapter" data-level="10.5.2" data-path="week-10.html"><a href="week-10.html#why-does-maup-matter"><i class="fa fa-check"></i><b>10.5.2</b> Why does MAUP matter?</a></li>
<li class="chapter" data-level="10.5.3" data-path="week-10.html"><a href="week-10.html#what-can-we-do"><i class="fa fa-check"></i><b>10.5.3</b> What can we do?</a></li>
<li class="chapter" data-level="10.5.4" data-path="week-10.html"><a href="week-10.html#homework-10.4"><i class="fa fa-check"></i><b>10.5.4</b> Homework 10.4</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="week-10.html"><a href="week-10.html#references-and-further-reading"><i class="fa fa-check"></i><b>10.6</b> References and further reading</a><ul>
<li class="chapter" data-level="10.6.1" data-path="week-10.html"><a href="week-10.html#binning-1"><i class="fa fa-check"></i><b>10.6.1</b> Binning</a></li>
<li class="chapter" data-level="10.6.2" data-path="week-10.html"><a href="week-10.html#maup"><i class="fa fa-check"></i><b>10.6.2</b> MAUP</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Crime Mapping in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-9-spatial-regression-models" class="section level1">
<h1><span class="header-section-number">Chapter 9</span> Week 9 : Spatial regression models</h1>
<div id="introduction-2" class="section level2">
<h2><span class="header-section-number">9.1</span> Introduction</h2>
<p>Last week we provided you with an introduction to regression analysis with R. the data we used had a spatial component. We were modelling the geographical distribution of homicide across US counties. However, we did not incorporated this spatial component into our models. As we have explained througout the semester criminal events often cluster geographically in space. So if we want to develop a regression model for crime we may have to recognise this spatial component. Remember as well, from last week, that regression models assume independence between the observations. That is, a regression model is formally assuming that what happens in area Xi is not in any way related (it is independent) of what happens in area Xii. But if those two areas are adjacent in geographical space we know that there is a good chance that this assumption may be violated. In previous weeks we covered formal tests for spatial autocorrelation, which allow us to test whether this assumption is met or not. So before we fit a regression model with spatial data we need to explore the issue of autocorrelation. We already know how to do this. In this session, we will examine the data from last week, explore whether autocorrelation is an issue, and then introduce models that allow us to take into account spatial autocorrelation. We will see that there are two basic ways of adjusting for spatial autocorrelation: through a spatial lag model or through a spatial error model.</p>
<p>Before we do any of this, we need to load the libraries we will use today:</p>
<div class="sourceCode" id="cb645"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb645-1" title="1"><span class="kw">library</span>(sf)</a></code></pre></div>
<pre><code>## Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3</code></pre>
<div class="sourceCode" id="cb647"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb647-1" title="1"><span class="kw">library</span>(tmap)</a>
<a class="sourceLine" id="cb647-2" title="2"><span class="kw">library</span>(sp)</a>
<a class="sourceLine" id="cb647-3" title="3"><span class="kw">library</span>(spdep)</a></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: spData</code></pre>
<pre><code>## To access larger datasets in this package, install the spDataLarge
## package with: `install.packages(&#39;spDataLarge&#39;,
## repos=&#39;https://nowosad.github.io/drat/&#39;, type=&#39;source&#39;))`</code></pre>
<p>Then we will bring back the data from last week:</p>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb651-1" title="1"><span class="co">##R in Windows have some problems with https addresses, that&#39;s why we need to do this first:</span></a>
<a class="sourceLine" id="cb651-2" title="2">urlfile&lt;-<span class="st">&#39;https://s3.amazonaws.com/geoda/data/ncovr.zip&#39;</span></a>
<a class="sourceLine" id="cb651-3" title="3"><span class="kw">download.file</span>(urlfile, <span class="st">&#39;ncovr.zip&#39;</span>)</a>
<a class="sourceLine" id="cb651-4" title="4"><span class="co">#Let&#39;s unzip and create a new directory (ncovr) in our working directory to place the files</span></a>
<a class="sourceLine" id="cb651-5" title="5"><span class="kw">unzip</span>(<span class="st">&#39;ncovr.zip&#39;</span>, <span class="dt">exdir =</span> <span class="st">&#39;ncovr&#39;</span>)</a></code></pre></div>
<p>Last week we did not treated the data as spatial and, consequently, relied on the csv file. But notice that in the unzip ncovr file there is also a shapefile that we can load as a spatial object into R:</p>
<div class="sourceCode" id="cb652"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb652-1" title="1">shp_name &lt;-<span class="st"> &quot;ncovr/ncovr/NAT.shp&quot;</span></a>
<a class="sourceLine" id="cb652-2" title="2">ncovr_sf &lt;-<span class="st"> </span><span class="kw">st_read</span>(shp_name)</a></code></pre></div>
<pre><code>## Reading layer `NAT&#39; from data source `/Users/reka/Dropbox (The University of Manchester)/crimemapping_textbook_bookdown/ncovr/ncovr/NAT.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 3085 features and 69 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -124.7314 ymin: 24.95597 xmax: -66.96985 ymax: 49.37173
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs</code></pre>
<p>We can indeed represent our variable of interest using a choropleth map.</p>
<div class="sourceCode" id="cb654"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb654-1" title="1">current_style &lt;-<span class="st"> </span><span class="kw">tmap_style</span>(<span class="st">&quot;col_blind&quot;</span>)</a></code></pre></div>
<pre><code>## tmap style set to &quot;col_blind&quot;</code></pre>
<pre><code>## other available styles are: &quot;white&quot;, &quot;gray&quot;, &quot;natural&quot;, &quot;cobalt&quot;, &quot;albatross&quot;, &quot;beaver&quot;, &quot;bw&quot;, &quot;classic&quot;, &quot;watercolor&quot;</code></pre>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb657-1" title="1"><span class="kw">tm_shape</span>(ncovr_sf) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb657-2" title="2"><span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&quot;HR90&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Homicide Rate (Quantiles)&quot;</span>, <span class="dt">style=</span><span class="st">&quot;quantile&quot;</span>, <span class="dt">palette =</span> <span class="st">&quot;Reds&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb657-3" title="3"><span class="st">  </span><span class="kw">tm_borders</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb657-4" title="4"><span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">main.title =</span> <span class="st">&quot;Homicide Rate across US Counties, 1990&quot;</span>, <span class="dt">main.title.size =</span> <span class="fl">0.7</span> ,</a>
<a class="sourceLine" id="cb657-5" title="5">            <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;bottom&quot;</span>), <span class="dt">legend.title.size =</span> <span class="fl">0.8</span>)</a></code></pre></div>
<p><img src="09-week9_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Do you think there is spatial patterning to homicide?</p>
</div>
<div id="looking-at-the-residuals-and-testing-for-spatial-autocorrelation-in-regression" class="section level2">
<h2><span class="header-section-number">9.2</span> Looking at the residuals and testing for spatial autocorrelation in regression</h2>
<p>Residuals, as we have explained, give you an idea of the distance between our observed Y values and the predicted Y values. So in essence they are deviations of reality from your model. Your regression line or hyperplane is optimised to be the one that best represent your data if those assumptions are met. Residuals are very helpful to diagnose, then, whether your model is a good representation of reality or not. Most diagnostics of the assumptions for OLS regression, which is if you remember from last year the technique we are using, rely on exploring the residuals.</p>
<p>In order to explore the residuals we need to fit our model first. Let’s look at one of the models from last week.</p>
<div class="sourceCode" id="cb658"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb658-1" title="1">fit_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR90 <span class="op">~</span><span class="st"> </span>RD90 <span class="op">+</span><span class="st"> </span>SOUTH <span class="op">+</span><span class="st"> </span>DV90 <span class="op">+</span><span class="st"> </span>MA90 <span class="op">+</span><span class="st"> </span>PS90 <span class="op">+</span>UE90, <span class="dt">data=</span>ncovr_sf)</a></code></pre></div>
<p>Now that we have fitted the model we can extract the residuals. If you look at the fit_1 object in your RStudio environment or if you run the str() function to look inside this object you will see that this object is a list with differet elements, one of which is the residuals. An element of this object then includes the residual for each of your observations (the difference between the observed value and the value predicted by your model). We can extract the residuals using the residuals() function and add them to our spatial data set.</p>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb659-1" title="1">ncovr_sf<span class="op">$</span>res_fit1 &lt;-<span class="st"> </span><span class="kw">residuals</span>(fit_<span class="dv">1</span>)</a></code></pre></div>
<p>If you now look at the dataset you will see that there is a new variable with the residuals. In those cases where the residual is negative this is telling us that the observed value is lower than the predicted (that is, our model is overpredicting the level of homicide for that observation) when the residual is positive the observed value is higher than the predicted (that is, our model is underpredicting the level of homicide for that observation).</p>
<p>We could also extract the predicted values if we wanted. We would use the fitted() function.</p>
<div class="sourceCode" id="cb660"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb660-1" title="1">ncovr_sf<span class="op">$</span>fitted_fit1 &lt;-<span class="st"> </span><span class="kw">fitted</span>(fit_<span class="dv">1</span>)</a></code></pre></div>
<p>Now look at the second county in the dataset. It has a homice rate in 1990 of 15.88. This is the observed value. If we look at the new column we have created (fitted_fit1), our model predicts a homicide rate of 2.41. That is, knowing the level unemployment, whether the county is North or South, the level of resource deprivation, etc., we are predicting a homicide rate of 2.41. Now, this is lower than the observed value, so our model is underpredicting the level of homicide in this case. If you observed the residual you will see that it has a value of 13.46, which is simply the difference between the observed and the predicted value.</p>
<p>With spatial data one useful thing to do is to look at any spatial patterning in the distribution of the residuals. Notice that the residuals are the difference between the observed values for homicide and the predicted values for homicide, so you want your residual to NOT display any spatial patterning. If, on the other hand, your model display a patterning in the areas of the study region where it performs predicts badly, then you may have a problem. This is telling your model is not a good representation of the social phenomena you are studying across the full study area: there is systematically more distortion in some areas than in others.</p>
<p>We are going to produce a choropleth map for the residuals, but we will use a common classification method we haven’t covered yet: standard deviations. Standard deviation is a statistical technique type of map based on how much the data differs from the mean. You measure the mean and standard deviation for your data. Then, each standard deviation becomes a class in your choropleth maps.</p>
<p>In order to do that we will compute the mean and the standard deviation for the variable we want to plot and break the variable according to these values. The following code creates a new variable in which we will express the residuals in terms of standard deviations away from the mean. So, for each observation, we substract the mean and divide by the standard deviation.</p>
<div class="sourceCode" id="cb661"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb661-1" title="1">ncovr_sf<span class="op">$</span>sd_breaks &lt;-<span class="st"> </span>(ncovr_sf<span class="op">$</span>res_fit1 <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(ncovr_sf<span class="op">$</span>res_fit1))<span class="op">/</span><span class="kw">sd</span>(ncovr_sf<span class="op">$</span>res_fit1)</a>
<a class="sourceLine" id="cb661-2" title="2"><span class="kw">summary</span>(ncovr_sf<span class="op">$</span>sd_breaks)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -3.5370 -0.5238 -0.1404  0.0000  0.3314 13.7407</code></pre>
<p>Next we use a new style, fixed, within the tm_fill function. When we break the variable into classes using the fixed argument we need to specify the boundaries of the classes. We do this using the breaks argument. In this case we are going to ask R to create 7 classes based on standard deviations away from the mean.</p>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb663-1" title="1">my_breaks &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">14</span>,<span class="op">-</span><span class="dv">3</span>,<span class="op">-</span><span class="dv">2</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">14</span>)</a>
<a class="sourceLine" id="cb663-2" title="2"></a>
<a class="sourceLine" id="cb663-3" title="3"><span class="kw">tm_shape</span>(ncovr_sf) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb663-4" title="4"><span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&quot;sd_breaks&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Residuals&quot;</span>, <span class="dt">style =</span> <span class="st">&quot;fixed&quot;</span>, <span class="dt">breaks =</span> my_breaks, <span class="dt">palette =</span> <span class="st">&quot;-RdBu&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb663-5" title="5"><span class="st">  </span><span class="kw">tm_borders</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb663-6" title="6"><span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">main.title =</span> <span class="st">&quot;Residuals&quot;</span>, <span class="dt">main.title.size =</span> <span class="fl">0.7</span> ,</a>
<a class="sourceLine" id="cb663-7" title="7">            <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;bottom&quot;</span>), <span class="dt">legend.title.size =</span> <span class="fl">0.8</span>)</a></code></pre></div>
<pre><code>## Variable &quot;sd_breaks&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="09-week9_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Notice the spatial patterning of areas of over-prediction (negative residuals, or blue tones) and under-prediction (positive residuals, or brown tones). This visual inspection of the residuals is telling you that spatial autocorrelation may be present here. This, however, would require a more formal test.</p>
<p>Remember from week 6 that in order to do this first we need to turn our sf object into a sp class object and then create the spatial weight matrix. If the code below and what it does is not clear to you, revise the notes from week 6 -when we first introduced it.</p>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb665-1" title="1"><span class="co">#We coerce the sf object into a new sp object</span></a>
<a class="sourceLine" id="cb665-2" title="2">ncovr_sp &lt;-<span class="st"> </span><span class="kw">as</span>(ncovr_sf, <span class="st">&quot;Spatial&quot;</span>)</a>
<a class="sourceLine" id="cb665-3" title="3"><span class="co">#Then we create a list of neighbours using the Queen criteria</span></a>
<a class="sourceLine" id="cb665-4" title="4">w &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(ncovr_sp, <span class="dt">row.names=</span>ncovr_sp<span class="op">$</span>FIPSNO)</a>
<a class="sourceLine" id="cb665-5" title="5"><span class="kw">summary</span>(w)</a></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 3085 
## Number of nonzero links: 18168 
## Percentage nonzero weights: 0.190896 
## Average number of links: 5.889141 
## Link number distribution:
## 
##    1    2    3    4    5    6    7    8    9   10   11   13   14 
##   24   36   91  281  620 1037  704  227   50   11    2    1    1 
## 24 least connected regions:
## 53009 53029 25001 44005 36103 51840 51660 6041 51790 51820 51540 51560 6075 51580 51530 51131 51115 51770 51720 51690 51590 27031 26083 55029 with 1 link
## 1 most connected region:
## 49037 with 14 links</code></pre>
<p>This should give you an idea of the distribution of connectedness across the data, with counties having on average nearly 6 neighbours. Now we can generate the row standardise spatial weight matrix and the Moran Scatterplot.</p>
<div class="sourceCode" id="cb667"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb667-1" title="1">wm &lt;-<span class="st"> </span><span class="kw">nb2mat</span>(w, <span class="dt">style=</span><span class="st">&#39;B&#39;</span>)</a>
<a class="sourceLine" id="cb667-2" title="2">rwm &lt;-<span class="st"> </span><span class="kw">mat2listw</span>(wm, <span class="dt">style=</span><span class="st">&#39;W&#39;</span>)</a></code></pre></div>
<p>We obtain the Moran’s test for regression residuals using the function lm.morantest() as below. It is important to realize that the Moran’s I test statistic for residual spatial autocorrelation takes into account the fact that the variable under consideration is a residual, computed from a regression. The usual Moran’s I test statistic does not. It is therefore incorrect to simply apply a Moran’s I test to the residuals from the regression without correcting for the fact that these are residuals.</p>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb668-1" title="1"><span class="kw">lm.morantest</span>(fit_<span class="dv">1</span>, rwm, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = HR90 ~ RD90 + SOUTH + DV90 + MA90 + PS90 +
## UE90, data = ncovr_sf)
## weights: rwm
## 
## Moran I statistic standard deviate = 10.321, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## sample estimates:
## Observed Moran I      Expectation         Variance 
##     0.1093062514    -0.0014498532     0.0001151682</code></pre>
<p>You will notice we obtain a statistically significant value for Moran’s I. The value of the Moran’s I test is not too high, but we still need to keep it in mind. If we diagnose that spatial autocorrelation is an issue, that is, that the errors (the residuals) are related systematically among themselves, then we have a problem and need to use a more appropriate approach: a spatial regression model.</p>
</div>
<div id="what-to-do-now" class="section level2">
<h2><span class="header-section-number">9.3</span> What to do now?</h2>
<p>If the test is significant (as in this case), then we possibly need
to think of a more suitable model to represent our data: a spatial regression model. Remember spatial dependence means that there will be areas of spatial clustering for the residuals in our regression model. So our predicted line (or hyperplane) will systematically under-predict or over-predict in areas that are close to each other. That’s not good. We want a better model that does not
display any spatial clustering in the residuals.</p>
<p>There are two general ways of incorporating spatial dependence in a regression model, through what we called a <strong>spatial error model</strong> or by means of a <strong>spatially lagged model</strong>. There are <em>spdep</em> functions that provides us with some tools to help us make a decision as to which of these two is most appropriate: the <strong>Lagrange Multiplier tests</strong>.</p>
<p>The difference between these two models is both technical and conceptual. The <strong>spatial error model</strong> treats the spatial autocorrelation as a nuisance that needs to be dealt with. A spatial error model basically implies that the:</p>
<p><em>spatial dependence observed in our data does not reflect a truly spatial process, but merely the geographical clustering of the sources of the behaviour of interest. For example, citizens in adjoining neighbohoods may favour the same (political) candidate not because they talk to their neighbors, but because citizens with similar incomes tend to cluster geographically, and income also predicts vote choice. Such spatial dependence can be termed attributional dependence&quot;</em> (Darmofal, 2015: 4)</p>
<p>The <strong>spatially lagged model</strong>, on the other hand, incorporates spatial dependence explicitly by adding a “spatially lagged” variable <em>y</em> on the right hand side of our regression equation. Its distinctive
characteristic is that it includes a spatially lagged “dependent” variable among the explanatory factors. It’s basically explicitly saying that the values of y in the neighbouring areas of observation <em>n~i</em> is an important predictor of y on each individual area <em>n~i</em> . This is one way of saying that the spatial dependence may be produced by a spatial process such as the diffusion of behaviour between neighboring units:</p>
<p><em>“If so the behaviour is likely to be highly social in nature, and understanding the interactions between interdependent units is critical to understanding the behaviour in question. For example, citizens may discuss politics across adjoining neighbours such that an increase in support for a candidate in one neighbourhood directly leads to an increase in support for the candidate in adjoining neighbourhoods”</em> (Darmofal, 2015: 4)</p>
</div>
<div id="spatial-regimes" class="section level2">
<h2><span class="header-section-number">9.4</span> Spatial Regimes</h2>
<p>Before we proceed to a more detailed description of these two models it is important that we examine another aspect of our model that also links to geography. Remember that when we brought up our data into R, we decided to test for the presence of an interaction. We looked at whether the role of unemployment was different in Southern and Northern states. We found that this interaction was indeed significant. Unemployment had a more significant effect in Southern than in Northern states. This was particularly obvious during the 1970s, when unemployment did not affected homicide rates in the Northern states, but it did led to a decrease in homicide in the Southern states.</p>
<p>We could have attempted to test other interaction effects between some of our other predictors and their geographical location in the South or the North. But we did not.</p>
<p>If you have read the Ballen et al. (2001) paper that we are replicating in last week and this week lab, you will have noticed that they decided that they needed to run separate models for the South and the North. This kind of situation, where sub-regions, seem to display different patterns often is alluded with the name of spatial regimes. In the context of regression analysis, spatial regimes relates to the possibility that we may need to split our data into two (or more sub-regions) in order to run our models, because we presume that the relationship of the predictors to the outcome may play out differently in these sub-regions (spatial regimes).</p>
<p>So how can we assess whether this is an issue in our data? As with many other diagnostics of regression, you may want to start by looking at your residuals. Look at the residual map we produced earlier. Do you think that the residuals look different in the South and in the North? If the pattern is not clear to you, you may want to run other forms of visualisation.</p>
<div class="sourceCode" id="cb670"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb670-1" title="1"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb670-2" title="2"></a>
<a class="sourceLine" id="cb670-3" title="3"><span class="kw">ggplot</span>(ncovr_sf, <span class="kw">aes</span>(<span class="dt">x =</span> res_fit1, <span class="dt">colour =</span> <span class="kw">as.factor</span>(SOUTH))) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb670-4" title="4"><span class="st">  </span><span class="kw">geom_density</span>() </a></code></pre></div>
<p><img src="09-week9_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div id="homework-1-4" class="section level3">
<h3><span class="header-section-number">9.4.1</span> HOMEWORK 1</h3>
<p><em>What do you see in this plot? And, critically, what does it mean? What is this telling you about the predicted values that result from our model? (Remember what a residual is: the difference between the observed values and the predicted values).</em></p>
<p>There are formal tests that one can use to further explore these issues. The paper by Bollen et al. (2001) mentions them (Chow tests). But those are beyond the scope of this course. Sufficient to say that, as Bollen et al. (2001), we are going to split our analysis and run them separately for the Southern and the Northern states. We have covered the filter() function from dplyr to split datasets based on values of a variable. But to split sf objects it is better to rely on the more generic subset function, since filter() doesn’t accommodate well the column with the geographic information that sf provides.</p>
<div class="sourceCode" id="cb671"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb671-1" title="1">ncovr_s_sf &lt;-<span class="st"> </span><span class="kw">subset</span>(ncovr_sf, SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb671-2" title="2">ncovr_n_sf &lt;-<span class="st"> </span><span class="kw">subset</span>(ncovr_sf, SOUTH <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)</a></code></pre></div>
</div>
</div>
<div id="lagrange-multipliers" class="section level2">
<h2><span class="header-section-number">9.5</span> Lagrange multipliers</h2>
<p>The Moran’s I test statistic has high power against a range of spatial alternatives. However, it does not provide much help in terms of which alternative model would be most appropriate. The Lagrange Multiplier test statistics do allow a distinction between spatial error models and spatial lag models.</p>
<p>In order to practice their computation and interpretation, let’s run two separate OLS regression models (one for the South and one for the North), using the same predictors as we used last week and, first, focusing on homicide in the northern counties in the earliest year for which we have data (1960). We have split the data in two, so that means that before we do this we need to create new files for the spatial weight matrix: in particular we will create one using first order queen criteria.</p>
<div class="sourceCode" id="cb672"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb672-1" title="1"><span class="co">#We coerce the sf object into a new sp object</span></a>
<a class="sourceLine" id="cb672-2" title="2">ncovr_n_sp &lt;-<span class="st"> </span><span class="kw">as</span>(ncovr_n_sf, <span class="st">&quot;Spatial&quot;</span>)</a>
<a class="sourceLine" id="cb672-3" title="3"><span class="co">#Then we create a list of neighbours using the Queen criteria</span></a>
<a class="sourceLine" id="cb672-4" title="4">w_n &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(ncovr_n_sp, <span class="dt">row.names=</span>ncovr_n_sp<span class="op">$</span>FIPSNO)</a>
<a class="sourceLine" id="cb672-5" title="5">wm_n &lt;-<span class="st"> </span><span class="kw">nb2mat</span>(w_n, <span class="dt">style=</span><span class="st">&#39;B&#39;</span>)</a>
<a class="sourceLine" id="cb672-6" title="6">rwm_n &lt;-<span class="st"> </span><span class="kw">mat2listw</span>(wm_n, <span class="dt">style=</span><span class="st">&#39;W&#39;</span>)</a>
<a class="sourceLine" id="cb672-7" title="7"></a>
<a class="sourceLine" id="cb672-8" title="8">fit_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(HR60 <span class="op">~</span><span class="st"> </span>RD60 <span class="op">+</span><span class="st"> </span>DV60 <span class="op">+</span><span class="st"> </span>MA60 <span class="op">+</span><span class="st"> </span>PS60 <span class="op">+</span>UE60, <span class="dt">data=</span>ncovr_n_sf)</a></code></pre></div>
<p>First look at the Moran’s I.</p>
<div class="sourceCode" id="cb673"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb673-1" title="1"><span class="kw">lm.morantest</span>(fit_<span class="dv">2</span>, rwm_n, <span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## Moran I statistic standard deviate = 2.84, p-value = 0.004511
## alternative hypothesis: two.sided
## sample estimates:
## Observed Moran I      Expectation         Variance 
##     0.0394654814    -0.0022539192     0.0002157889</code></pre>
<p>The p (probability) value associated with this Moran’s I is below our standard threshold. So we will say that we have an issue with spatial autocorrelation that we need to deal with. OLS regression won’t do. In order to decide whether to fit a spatial error or a spatially lagged model we need to run the Lagrange Multipliers.</p>
<p>Both Lagrange multiplier tests (for the error and the lagged models, LMerr and LMlag respectively), as well as their robust forms (RLMerr and RLMLag, also respectively) are included in the lm.LMtests function. Again, a regression object and a spatial listw object must be passed as arguments. In addition, the tests must be specified as a character vector (the default is only LMerror), using the c( ) operator (concatenate), as illustrated below.</p>
<div class="sourceCode" id="cb675"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb675-1" title="1"><span class="kw">lm.LMtests</span>(fit_<span class="dv">2</span>, rwm_n, <span class="dt">test =</span> <span class="kw">c</span>(<span class="st">&quot;LMerr&quot;</span>,<span class="st">&quot;LMlag&quot;</span>,<span class="st">&quot;RLMerr&quot;</span>,<span class="st">&quot;RLMlag&quot;</span>,<span class="st">&quot;SARMA&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## LMerr = 7.1326, df = 1, p-value = 0.007569
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## LMlag = 16.595, df = 1, p-value = 4.627e-05
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## RLMerr = 8.2906, df = 1, p-value = 0.003985
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## RLMlag = 17.753, df = 1, p-value = 2.515e-05
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data
## = ncovr_n_sf)
## weights: rwm_n
## 
## SARMA = 24.886, df = 2, p-value = 3.946e-06</code></pre>
<p>How do we interpret the Lagrange Multipliers? First we look at the standard ones (LMerr and LMlag). <strong>If both</strong> are below the .05 level this means we need to have a look at the robust version of these tests (Robust LM). If the non-robust version is not significant, the mathematical properties of the robust tests may not hold, so we don’t look at them in those scenarios. It is fairly common to find that both the lag (LMlag) and the error (LMerr) non-robust LM are significant. If only one of them were, problem solved we would choose a spatial lag or a spatial error model according to this (i.e., if the lag M was significant and the error LM was not we would run a spatial lag model or viceversa). Here we see that both are significant, thus, we need to inspect their robust versions.</p>
<p>Yet we look at the robust Lagrange multipliers (RLMlag and RLMerr) and encounter that both are significant again. What do we do? Luc Anselin (2008: 199-200) proposes the following criteria:</p>
<p><em>“When both LM test statistics reject the null hypothesis, proceed to the bottom part of the graph and consider the Robust forms of the test statistics. Typically, only one of them will be significant, or one will be orders of magnitude more significant than the other (e.g., p &lt; 0.00000 compared to p &lt; 0.03). In that case the decision is simple: estimate the spatial regression model matching the (most) significant” robust “statistic. In the rare instance that both would be highly significant, go with the model with the largest value for the test statistic. However, in this situation, some caution is needed, since there may be other sources of misspecification. One obvious action to take is to consider the results for different spatial weight and/or change the basic (i.e., not the spatial part) specification of the model. there are also rare instances where neither of the Robust LM test statistics are significant. In those cases, more serious specification problems are likely present and those should be addressed first”.</em></p>
<p>By other specification errors Prof. Anselin refers to problems with some of the other assumptions of regression that we covered last week.</p>
<p>Ok, so let’s go back to our results and keep this criteria in mind. Both Robust LM are significant, but we can see that the test for the lag model is several orders more significant than for the error model (p &lt; 0.0000251 vs p &lt; 0.004). Notice as well that the test value is higher for the lag model (18 versus 8). In this case we would say that the Lagrange Multiplier tests suggest we estimate a spatial lag model rather than a spatial error model.</p>
<div id="homework-2-4" class="section level3">
<h3><span class="header-section-number">9.5.1</span> HOMEWORK 2</h3>
<p><em>???Run a OLS regression model for homicide rate in 1980 for the Southern states using the covariates we have been using so far and make sure that you ask for the spatial dependence tests and the Lagrange Multipliers (attach the results). What model do you think need to be estimated in this case? The spatial lag or the spatial error model?</em></p>
</div>
</div>
<div id="fitting-and-interpreting-a-spatially-lagged-model" class="section level2">
<h2><span class="header-section-number">9.6</span> Fitting and interpreting a spatially lagged model</h2>
<p>Maximum Likelihood (ML) estimation of the spatial lag model is carried out with the lagsarlm() function. The required arguments are a regression “formula”, a data set and a listw spatial weights object. The default method uses Ord’s eigenvalue decomposition of the spatial weights matrix.</p>
<div class="sourceCode" id="cb677"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb677-1" title="1">fit_<span class="dv">2</span>_lag &lt;-<span class="st"> </span><span class="kw">lagsarlm</span>(HR60 <span class="op">~</span><span class="st"> </span>RD60 <span class="op">+</span><span class="st"> </span>DV60 <span class="op">+</span><span class="st"> </span>MA60 <span class="op">+</span><span class="st"> </span>PS60 <span class="op">+</span>UE60, <span class="dt">data=</span>ncovr_n_sf, rwm_n)</a>
<a class="sourceLine" id="cb677-2" title="2"><span class="kw">summary</span>(fit_<span class="dv">2</span>_lag)</a></code></pre></div>
<pre><code>## 
## Call:
## lagsarlm(formula = HR60 ~ RD60 + DV60 + MA60 + PS60 + UE60, data = ncovr_n_sf, 
##     listw = rwm_n)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -11.86076  -1.54308  -0.55531   0.76832  28.30435 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept)  5.802071   0.677236  8.5673 &lt; 2.2e-16
## RD60         1.734746   0.157771 10.9954 &lt; 2.2e-16
## DV60         1.002757   0.077951 12.8640 &lt; 2.2e-16
## MA60        -0.179328   0.020024 -8.9557 &lt; 2.2e-16
## PS60         0.382956   0.077193  4.9610 7.014e-07
## UE60         0.087963   0.030109  2.9215  0.003483
## 
## Rho: 0.13749, LR test value: 15.139, p-value: 9.9874e-05
## Asymptotic standard error: 0.035631
##     z-value: 3.8587, p-value: 0.000114
## Wald statistic: 14.89, p-value: 0.000114
## 
## Log likelihood: -4273.43 for lag model
## ML residual variance (sigma squared): 9.6542, (sigma: 3.1071)
## Number of observations: 1673 
## Number of parameters estimated: 8 
## AIC: 8562.9, (AIC for lm: 8576)
## LM test for residual autocorrelation
## test value: 10.659, p-value: 0.0010954</code></pre>
<p>As expected, the spatial autoregressive parameter (Rho) is highly significant, as indicated by the p-value of 0.000114 on an asymptotic t-test (based on the asymptotic variance matrix). The Likelihood Ratio test (LR) on this parameter is also highly significant (p value 9.9874e-05).</p>
<p>Just to reiterate, we run the spatial lag model not only because the Lagrange Multiplier suggests this may be appropriate, but also because in this case we believe that the values of y in one county, i, are directly influenced by the values of y that exist in the “neighbors” of i. This is an influence that goes beyond other explanatory variables that are specific to i. Remember what we said earlier in the spatial lag model we are simply adding as an additional explanatory variable the values of y in the surrounding area. What we mean by “surrounding” will be defined by our spatial weight matrix. It’s important to emphasise that one has to think very carefully and explore appropriate definitions of “surrounding” (as we discussed, though just superficially, in the section on spatial clustering a few weeks ago). We are using here the first order queen criteria, but in real practice you would need to explore whether this is the best definition and one that makes theoretical sense.</p>
<p>How do you interpret these results? First you need to look at the general measures of fit of the model. I know what you are thinking. Look at the R Square and compare them, right? Well, don’t. This R Square is not a real R Square, but a pseudo-R Square and therefore is not comparable to the one we obtain from the OLS regression model. Instead we can look at the Akaike Information Criterion. We see that the lag model has a AIC of 8562.9 whereas the linear model with no lags has a AIC of 8576, so this is telling us there is a better fit when we include the spatial lag.</p>
<p>In our spatial lag model you will notice that there is a new term Rho. What is this? This is our spatial lag. It is a variable that measures the homicide rate in the counties that are defined as surrounding each county in our spatial weight matrix. We are simply using this variable as an additional explanatory variable to our model, so that we can appropriately take into account the spatial clustering detected by our Moran’s I test. You will notice that the estimated coefficient for this termis both positive and statistically significant. In other words, when the homicide rate in surrounding areas increases, so does the homicide rate in each country, even when we adjust for the other explanatory variables in our model. The fact the lag is significant adds further evidence that this is a better model than the OLS regression specification.</p>
<p>You also see at the bottom further tests for spatial dependence, a likelihood ratio test. This is not a test for residual spatial autocorrelation after we introduce our spatial lag. What you want is for this test to be significant because in essence is further evidence that the spatial lag model is a good fit.</p>
<p>How about the coefficients? It may be tempting to look at the regression coefficients for the other explanatory variables for the original OLS model and compare them to those in the spatial lag model. But you should be careful when doing this. Their meaning now has changed:</p>
<p>“Interpreting the substantive effects of each predictor in a spatial lag model is much more complex than in a nonspatial model (or in a spatial error model) because of the presence of the spatial multiplier that links the independent variables to the dependent. In the nonspatial model, it does not matter which unit is experiencing the change on the independent variable. The effect” in the dependent variable “of a change” in the value of an independent variable “is constant across all observations” (Darmofal, 2015: 107). Remember we say, when interpreting a regression coefficient for variable X~i, that they indicate how much Y goes up or down for every one unit increase in X~i when holding all other variables in the model constant. In our example, for the nonspatial model this effect is the same for every county in our dataset. But in the spatial lag model things are not the same. We cannot interpret the regression coefficients for the substantive predictors in the same way because the “substantive effects of the independent variables vary by observation as a result of the different neighbors for each unit in the data” (Darmofal, 2015: 107).</p>
<p>In the OLS regression model, the coefficients for any of the explanatory variables measure the absolute impact of these variables. It is a simpler scenario. We look at the effect of X in Y within each county. So X in county A affects Y in count A. In the spatial lag model there are two components to how X affect Y. X affects Y within each county directly but remember we are also including the spatial, the measure of Y in the surrounding counties (call them B, C, and D). So our model includes not only the effect of X in county A in the level of Y in county A. By virtues of including the spatial lag (a measure of Y in county B, C and D) we are indirectly incorporating as well the effects that X has on Y in counties B, C, and D. So the effect of a covariate (independent variable) is the sum of two particular effects: a direct, local effect of the covariate in that unit, and an indirect, spillover effect due to the spatial lag.</p>
<p>In, other words, in the spatial lag model, the coefficients only focus on the “short-run impact” of x~i on y~i , rather than the net effect. As Ward and Gleditsch (2008) explain “Since the value of y~i will influence the level of” homicide “in other” counties y~j and these y~j , in turn, feedback on to y~i , we need to take into account the additional effects that the short impact of x~i exerts on y~i through its impact on the level of&quot; homicide “in other” counties. You can still read the coefficients in the same way but need to keep in mind that they are not measuring the net effect. Part of their effect will be captured by the spatial lag. Yet, you may still want to have a look at whether things change dramatically, particularly in terms of their significance (which is not the case in this example).</p>
</div>
<div id="fitting-an-interpreting-a-spatial-error-model" class="section level2">
<h2><span class="header-section-number">9.7</span> Fitting an interpreting a spatial error model</h2>
<p>We saw (well you should have seen!) that for the case of homicide in the 80s for Southern states the spatial error model was more appropriate when using the 1 st order contiguity queen criteria. In this case then, we need to run a spatial error model.</p>
<p>Maximum likelihood estimation of the spatial error model is similar to the lag procedure and implemented in the errorsarlm() function. Again, the formula, data set and a listw spatial weights object must be specified, as illustrated below.</p>
<div class="sourceCode" id="cb679"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb679-1" title="1"><span class="co">#We coerce the sf object into a new sp object</span></a>
<a class="sourceLine" id="cb679-2" title="2">ncovr_s_sp &lt;-<span class="st"> </span><span class="kw">as</span>(ncovr_s_sf, <span class="st">&quot;Spatial&quot;</span>)</a>
<a class="sourceLine" id="cb679-3" title="3"><span class="co">#Then we create a list of neighbours using the Queen criteria</span></a>
<a class="sourceLine" id="cb679-4" title="4">w_s &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(ncovr_s_sp, <span class="dt">row.names=</span>ncovr_s_sp<span class="op">$</span>FIPSNO)</a>
<a class="sourceLine" id="cb679-5" title="5">wm_s &lt;-<span class="st"> </span><span class="kw">nb2mat</span>(w_s, <span class="dt">style=</span><span class="st">&#39;B&#39;</span>)</a>
<a class="sourceLine" id="cb679-6" title="6">rwm_s &lt;-<span class="st"> </span><span class="kw">mat2listw</span>(wm_s, <span class="dt">style=</span><span class="st">&#39;W&#39;</span>)</a>
<a class="sourceLine" id="cb679-7" title="7"></a>
<a class="sourceLine" id="cb679-8" title="8">fit_<span class="dv">3</span>_err &lt;-<span class="st"> </span><span class="kw">errorsarlm</span>(HR80 <span class="op">~</span><span class="st"> </span>RD80 <span class="op">+</span><span class="st"> </span>DV80 <span class="op">+</span><span class="st"> </span>MA80 <span class="op">+</span><span class="st"> </span>PS80 <span class="op">+</span>UE80, <span class="dt">data=</span>ncovr_s_sf, rwm_s)</a>
<a class="sourceLine" id="cb679-9" title="9"><span class="kw">summary</span>(fit_<span class="dv">3</span>_err)</a></code></pre></div>
<pre><code>## 
## Call:errorsarlm(formula = HR80 ~ RD80 + DV80 + MA80 + PS80 + UE80, 
##     data = ncovr_s_sf, listw = rwm_s)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -17.70984  -3.46135  -0.56817   2.55031  24.84717 
## 
## Type: error 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) 11.395096   1.525679  7.4689 8.082e-14
## RD80         3.286154   0.189085 17.3793 &lt; 2.2e-16
## DV80         0.732640   0.133462  5.4895 4.030e-08
## MA80        -0.177938   0.044032 -4.0411 5.319e-05
## PS80         1.540084   0.214637  7.1753 7.216e-13
## UE80        -0.174869   0.066194 -2.6418  0.008248
## 
## Lambda: 0.3026, LR test value: 61.006, p-value: 5.6621e-15
## Asymptotic standard error: 0.037726
##     z-value: 8.0209, p-value: 1.1102e-15
## Wald statistic: 64.335, p-value: 9.992e-16
## 
## Log likelihood: -4384.823 for error model
## ML residual variance (sigma squared): 28.654, (sigma: 5.353)
## Number of observations: 1412 
## Number of parameters estimated: 8 
## AIC: 8785.6, (AIC for lm: 8844.7)</code></pre>
<p>The spatial lag model is probably the most common specification and maybe the most generally useful way to think about spatial dependence. But we can also enter the spatial dependence as, we mentioned trough the error term in our regression equation. Whereas the spatial lag model sees the spatial dependence as substantively meaningful (in that y, say homicide, in county i is influenced by homicide in its neighbours), the spatial error model simply treats the spatial dependence as a nuisance. This model focuses on estimating the regression parameters for the explanatory variables of interest and disregards the possibility that the spatial clustering, the spatial autocorrelation, may reflect something meaningful (other than attributional dependence as explained earlier). So instead of assuming that a spatial lag influences the dependent variable we estimate a model that relaxes the standard regression model assumption about the need for the errors to be independent. It’s beyond the scope of this introductory course to cover the mathematical details of this procedure, though you can use the suggested reading (particularly the highly accessible Ward and Gleditsch,2008, book or the more recent Darmofal, 2015) or some of the video lectures in the matter that are available in the GeoDa website.</p>
<p>As before the AIC is better for the spatial model (8786) than for the non spatial model (8845). In this case, you can compare the regression coefficients with those from the OLS model, since we don’t have a spatial lag capturing some of their effect. Notice how one of the most notable differences is the fact that unemployment nearly halves its impact in the new model. You will see the table includes a new parameter (lambda) but you don’t need to worry about this for the purpose of the course. It is something you would understand if you get into the mathematical estimation details.</p>
<div id="homework-3-1" class="section level3">
<h3><span class="header-section-number">9.7.1</span> HOMEWORK 3</h3>
<p><em>Estimate an appropriate regression model for the homicide rate for the 1970s for the Northern States. Justify and interpret the model that you have selected.</em></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-8-regression-analysis-a-refresher.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-10.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/09-week9.Rmd",
"text": "Edit"
},
"download": ["CrimeMapping.pdf", "CrimeMapping.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
